"""SystemVerilog backend -- modern style + SVA assertions.

Subclasses :class:`VerilogBackend` so all the wire / instance /
literal machinery is reused. Only the per-function module emit
and the file header differ:

  * ``wire`` / ``reg`` collapse into ``logic``
  * ``always @(posedge clk)`` becomes ``always_ff @(posedge clk)``
  * EML ``requires`` clauses lower to ``assume property (...)``
    (SVA "input contracts" — the simulation tool checks that the
    driver respects the precondition).
  * EML ``ensures`` clauses lower to ``assert property (...)``
    (SVA "output contracts" — the tool checks that the design
    respects the postcondition each cycle).

This means the same ``@verify`` annotation that produced a Lean
theorem now also produces a hardware-level runtime check. Both
target the same logical claim — formal verification on two axes.

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 2 backend roadmap.
"""

from __future__ import annotations

from hardware.allocator import AllocationPlan
from hardware.hdl_gen.verilog_backend import (
    VerilogBackend,
    _ModuleScope,
    _BINOP_TO_VERILOG,
    CompileError,
    _substitute_var,
    _var_names,
)
from hardware.hdl_gen.qformat import format_verilog_literal
from lang.parser.ast_nodes import ASTNode, EMLFunction, NodeKind


class SystemVerilogBackend(VerilogBackend):
    """SystemVerilog flavour of the Verilog HDL backend."""

    name = "systemverilog"

    def _header(self, mod, plan: AllocationPlan) -> str:
        return (
            f"// Generated by EML-lang SystemVerilog backend\n"
            f"// Source module: {mod.name or '(unnamed)'}\n"
            f"// Source file:   {mod.source_file}\n"
            f"//\n"
            f"// Target device: {plan.target_device}\n"
            f"// Pipeline depth: {plan.pipeline_depth} stages\n"
            f"// Estimated:    {plan.estimated_luts} LUTs, "
            f"{plan.estimated_dsps} DSPs, "
            f"{plan.estimated_bram_kb} KB BRAM\n"
            f"// Throughput:   {plan.throughput_msps:.1f} Msamples/s "
            f"@ {plan.clock_mhz} MHz\n"
            f"\n"
            f"`default_nettype none\n"
            f"`timescale 1ns / 1ps"
        )

    def _emit_function(
        self, fn: EMLFunction, plan: AllocationPlan,
    ) -> str:
        """SystemVerilog flavour of the per-function pipeline module.

        Same wire/instance build-out as the Verilog parent, then
        rewrites the result-register block to ``always_ff`` and
        appends SVA properties for the function's contracts.
        """
        width = self._design_precision(fn, plan)
        from hardware.hdl_gen.qformat import default_q
        qfmt = default_q(width)
        scope = _ModuleScope(width=width, qformat=qfmt)

        try:
            output_wire = self._emit_expr(self._final_expr(fn), scope)
        except CompileError as e:
            return (
                f"// {fn.name}: emission failed ({e})\n"
                f"// (function body has constructs the SystemVerilog "
                f"backend doesn't yet support)"
            )

        # Wire decls in SV use `logic`. Easiest path: rewrite the
        # decls collected by the parent class.
        sv_wire_decls = [
            ln.replace("wire signed", "logic signed")
            for ln in scope.wire_decls
        ]

        param_ports = ",\n    ".join(
            f"input  logic signed [WIDTH-1:0] {p.name}"
            for p in fn.params
        )

        co = (fn.profile or {}).get("chain_order", "?")
        cc = (fn.profile or {}).get("cost_class", "?")
        depth = (fn.profile or {}).get("eml_depth", "?")

        decls = "\n".join(sv_wire_decls)
        instances = "\n".join(scope.instances)
        assigns = "\n".join(scope.assigns)
        body_sections = [s for s in (decls, instances, assigns) if s]
        body_block = "\n\n".join(body_sections) if body_sections else (
            "    // (constant body -- no intermediates)"
        )

        sva_block = self._emit_sva_properties(fn, qfmt)
        # Phase E.5: refinement SVA assertions.
        ref_sva_block = self._emit_refinement_sva(fn, qfmt)

        return (
            f"// Pipeline: {fn.name}\n"
            f"// Chain order: {co}     Cost class: {cc}\n"
            f"// EML depth:   {depth}  Width: {width} bits\n"
            f"module {fn.name}_pipeline #(\n"
            f"    parameter int WIDTH = {width}\n"
            f") (\n"
            f"    input  logic                       clk,\n"
            f"    input  logic                       rst,\n"
            f"    input  logic                       valid_in,\n"
            f"    {param_ports},\n"
            f"    output logic                       valid_out,\n"
            f"    output logic signed [WIDTH-1:0]    result\n"
            f");\n"
            f"\n"
            f"{body_block}\n"
            f"\n"
            f"    // Registered output (modern always_ff form).\n"
            f"    always_ff @(posedge clk) begin\n"
            f"        if (rst) begin\n"
            f"            valid_out <= 1'b0;\n"
            f"            result    <= '0;\n"
            f"        end else begin\n"
            f"            valid_out <= valid_in;\n"
            f"            result    <= {output_wire};\n"
            f"        end\n"
            f"    end\n"
            f"{ref_sva_block}"
            f"{sva_block}"
            f"endmodule\n"
        )

    # ── Phase E.5: refinement SVA assertions ──────────────────

    def _emit_refinement_sva(self, fn: EMLFunction, qfmt) -> str:
        """Emit SVA assertions for refined parameters (Phase E.5).

        Idiom: assert property (cond) else $error("msg");
        Cross-param refinements emit a comment-only line.
        ABS uses $abs($signed(...)) per the existing SVA idiom.
        """
        param_names = {p.name for p in fn.params}
        lines: list[str] = []
        for p in fn.params:
            if p.refinement is None:
                continue
            ref = p.refinement
            pred = _substitute_var(ref.predicate, ref.binder, p.name)
            pred_vars = _var_names(pred)
            other_params = (pred_vars - {p.name}) & param_names
            if other_params:
                try:
                    cond_str = self._sva_expr(pred, qfmt)
                except CompileError as e:
                    cond_str = f"<unsupported: {e}>"
                lines.append(
                    f"    // refinement obligation: {fn.name}: {p.name}: {cond_str}"
                )
                continue
            try:
                cond = self._sva_expr(pred, qfmt)
                msg = f"{fn.name}: refinement violated on {p.name}: {cond}"
                lines.append(
                    f"    assert property ({cond})\n"
                    f'        else $error("{msg}");'
                )
            except CompileError as e:
                lines.append(f"    // refinement: unsupported ({e})")
        if not lines:
            return ""
        return (
            "\n"
            "    // ── Refinement guards (Phase E.5) ──\n"
            + "\n".join(lines)
            + "\n"
        )

    # ── SVA property emitter ───────────────────────────────────

    def _emit_sva_properties(
        self,
        fn: EMLFunction,
        qfmt,
    ) -> str:
        """Lower requires → assume property, ensures → assert property.

        The translator handles the boolean / arithmetic / abs /
        clamp subset cleanly; anything richer falls back to a
        comment so the human reviewer sees the contract was
        understood but not lowerable.
        """
        if not fn.requires and not fn.ensures:
            return ""

        lines: list[str] = [
            "",
            "    // ── SVA contracts (from @verify / requires / ensures) ──",
        ]

        for i, req in enumerate(fn.requires, start=1):
            try:
                expr = self._sva_expr(req, qfmt)
            except CompileError as e:
                lines.append(f"    // requires #{i}: unsupported ({e})")
                continue
            prop = f"pre_{fn.name}_{i}"
            lines.extend([
                f"    property {prop};",
                f"        @(posedge clk) disable iff (rst)",
                f"        valid_in |-> ({expr});",
                f"    endproperty",
                f"    assume property ({prop});",
            ])

        for i, ens in enumerate(fn.ensures, start=1):
            try:
                # SVA `valid_out |-> ...` fires on the cycle the
                # registered `result` is observable, so substitute
                # the EML `result` keyword with the module's output
                # port (not the combinational wire).
                expr = self._sva_expr(
                    ens, qfmt, result_subst="result",
                )
            except CompileError as e:
                lines.append(f"    // ensures #{i}: unsupported ({e})")
                continue
            prop = f"post_{fn.name}_{i}"
            lines.extend([
                f"    property {prop};",
                f"        @(posedge clk) disable iff (rst)",
                f"        valid_out |-> ({expr});",
                f"    endproperty",
                f"    assert property ({prop})",
                f"        else $error(\"{fn.name}: ensures #{i} violated\");",
            ])

        lines.append("")
        return "\n".join(lines)

    def _sva_expr(
        self,
        node: ASTNode,
        qfmt,
        *,
        result_subst: str | None = None,
    ) -> str:
        """Render an EML expression as a SystemVerilog boolean /
        arithmetic expression suitable for an SVA property body.

        Restricted to LITERAL / VAR / UNARYOP / BINOP / ABS /
        CLAMP / and the trivial CALL fallback. Anything else
        raises CompileError; the caller emits a comment.
        """
        kind = node.kind
        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "1'b1" if v else "1'b0"
            if isinstance(v, (int, float)):
                return format_verilog_literal(v, qfmt)
            raise CompileError(f"sva literal {v!r}")
        if kind == NodeKind.VAR:
            name = str(node.value)
            if name == "result":
                if result_subst is None:
                    return "result"
                return result_subst
            return name
        if kind == NodeKind.UNARYOP:
            sub = self._sva_expr(node.children[0], qfmt,
                                  result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"sva unary {node.value!r}")
        if kind == NodeKind.BINOP:
            left = self._sva_expr(node.children[0], qfmt,
                                   result_subst=result_subst)
            right = self._sva_expr(node.children[1], qfmt,
                                    result_subst=result_subst)
            op = _BINOP_TO_VERILOG.get(node.value)
            if op is None:
                raise CompileError(f"sva binop {node.value!r}")
            return f"({left} {op} {right})"
        if kind == NodeKind.ABS:
            sub = self._sva_expr(node.children[0], qfmt,
                                  result_subst=result_subst)
            # SystemVerilog's $abs is a system function on signed
            # operands; ($signed) keeps Verilator quiet about
            # signedness.
            return f"$abs($signed({sub}))"
        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._sva_expr(c, qfmt, result_subst=result_subst)
                for c in node.children
            )
            return (
                f"(({x} < {lo}) ? {lo} : "
                f"(({x} > {hi}) ? {hi} : {x}))"
            )
        raise CompileError(
            f"sva NodeKind {kind} (line {node.line}:{node.col})"
        )
