"""VHDL backend -- VHDL-2008 port of the Verilog backend.

Emits one `entity` + `architecture` per `@target(fpga)` function.
Same combinational AST translation as VerilogBackend; transcendentals
become component instantiations of `eml_<op>` -- a vendor-neutral
HDL library that ships in `hardware/modules/transcendental_vhd/`
(parallel to the existing Verilog modules).

Reference: lang/spec/EML_LANG_DESIGN.md section 3.2 (cross-cutting
deliverable: VHDL backend = subset of M3.2, same modules different syntax).
"""

from __future__ import annotations

from dataclasses import dataclass, field

from hardware.allocator import AllocationPlan
from hardware.hdl_gen.qformat import QFormat, default_q, format_verilog_literal
from lang.parser.ast_nodes import (
    ASTNode,
    EMLFunction,
    EMLModule,
    NodeKind,
)


_BINOP_TO_VHDL: dict[str, str] = {
    "+": "+", "-": "-", "*": "*", "/": "/",
    "<": "<", ">": ">", "<=": "<=", ">=": ">=",
    "==": "=", "!=": "/=",
    "&&": "and", "||": "or",
}


_TRANSCENDENTAL_TO_MODULE: dict[NodeKind, str] = {
    NodeKind.EXP:   "eml_exp",
    NodeKind.LN:    "eml_ln",
    NodeKind.SIN:   "eml_sin",
    NodeKind.COS:   "eml_cos",
    NodeKind.TAN:   "eml_tan",
    NodeKind.SQRT:  "eml_sqrt",
    NodeKind.SINH:  "eml_sinh",
    NodeKind.COSH:  "eml_cosh",
    NodeKind.TANH:  "eml_tanh",
    NodeKind.ASIN:  "eml_asin",
    NodeKind.ACOS:  "eml_acos",
    NodeKind.ATAN:  "eml_atan",
}


class CompileError(Exception):
    """Raised on a NodeKind the VHDL backend doesn't recognize."""


@dataclass
class _Scope:
    width: int
    qformat: QFormat
    instance_counter: int = 0
    signal_counter: int = 0
    signal_decls: list[str] = field(default_factory=list)
    assigns: list[str] = field(default_factory=list)
    instances: list[str] = field(default_factory=list)
    node_signals: dict[int, str] = field(default_factory=dict)

    def fresh_signal(self) -> str:
        self.signal_counter += 1
        name = f"s_w{self.signal_counter}"
        self.signal_decls.append(
            f"    signal {name} : signed(WIDTH-1 downto 0);"
        )
        return name

    def fresh_instance(self, prefix: str) -> str:
        self.instance_counter += 1
        return f"{prefix}_{self.instance_counter}"


class VHDLBackend:
    """Generate VHDL from a module + allocation plan."""

    name = "vhdl"

    def __init__(self, *, optimize: bool = True) -> None:
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule, plan: AllocationPlan) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        fpga_funcs = self._collect_fpga_functions(mod)

        chunks: list[str] = [self._header(mod, plan)]

        decls = self._transcendental_decls(plan)
        if decls:
            chunks.append(decls)

        for fn in fpga_funcs:
            chunks.append(self._emit_function(fn, plan))

        return "\n\n".join(chunks).rstrip() + "\n"

    # ── Helpers ───────────────────────────────────────────────

    def _collect_fpga_functions(
        self, mod: EMLModule,
    ) -> list[EMLFunction]:
        out: list[EMLFunction] = []
        for fn in mod.functions:
            for a in fn.annotations:
                if a.kind == "target" and a.args.get(0) == "fpga":
                    out.append(fn)
                    break
        return out

    def _header(self, mod: EMLModule, plan: AllocationPlan) -> str:
        return (
            f"-- Generated by EML-lang VHDL backend\n"
            f"-- Source module: {mod.name or '(unnamed)'}\n"
            f"-- Source file:   {mod.source_file}\n"
            f"--\n"
            f"-- Target device: {plan.target_device}\n"
            f"-- Pipeline depth: {plan.pipeline_depth} stages\n"
            f"-- Estimated:    {plan.estimated_luts} LUTs, "
            f"{plan.estimated_dsps} DSPs, "
            f"{plan.estimated_bram_kb} KB BRAM\n"
            f"-- Throughput:   {plan.throughput_msps:.1f} Msamples/s "
            f"@ {plan.clock_mhz} MHz\n"
            f"\n"
            f"library IEEE;\n"
            f"use IEEE.std_logic_1164.all;\n"
            f"use IEEE.numeric_std.all;"
        )

    def _transcendental_decls(self, plan: AllocationPlan) -> str:
        if not plan.transcendental_units:
            return ""
        lines = [
            "-- Transcendental components referenced by this design",
            "-- (bodies live in hardware/modules/transcendental_vhd/):",
        ]
        for u in plan.transcendental_units:
            lines.append(
                f"--   {u.op:<5}  count={u.count}  sharing={u.sharing}  "
                f"precision={u.precision_bits}-bit"
            )
        return "\n".join(lines)

    def _emit_function(
        self, fn: EMLFunction, plan: AllocationPlan,
    ) -> str:
        width = self._design_precision(fn, plan)
        qfmt = default_q(width)
        scope = _Scope(width=width, qformat=qfmt)

        try:
            output_signal = self._emit_expr(self._final_expr(fn), scope)
        except CompileError as e:
            return (
                f"-- {fn.name}: emission failed ({e})\n"
                f"-- (function body has constructs the VHDL backend "
                f"doesn't yet support)"
            )

        param_ports = ";\n        ".join(
            f"{p.name}     : in  signed(WIDTH-1 downto 0)"
            for p in fn.params
        )

        co = (fn.profile or {}).get("chain_order", "?")
        cc = (fn.profile or {}).get("cost_class", "?")
        depth = (fn.profile or {}).get("eml_depth", "?")

        decls = "\n".join(scope.signal_decls)
        instances = "\n".join(scope.instances)
        assigns = "\n".join(scope.assigns)
        body_sections = [s for s in (decls, instances, assigns) if s]
        body_block = "\n\n".join(body_sections) if body_sections else (
            "    -- (constant body -- no intermediates)"
        )

        return (
            f"-- Pipeline: {fn.name}\n"
            f"-- Chain order: {co}     Cost class: {cc}\n"
            f"-- EML depth:   {depth}  Width: {width} bits\n"
            f"entity {fn.name}_pipeline is\n"
            f"    generic (\n"
            f"        WIDTH : integer := {width}\n"
            f"    );\n"
            f"    port (\n"
            f"        clk       : in  std_logic;\n"
            f"        rst       : in  std_logic;\n"
            f"        valid_in  : in  std_logic;\n"
            f"        {param_ports};\n"
            f"        valid_out : out std_logic;\n"
            f"        result    : out signed(WIDTH-1 downto 0)\n"
            f"    );\n"
            f"end entity {fn.name}_pipeline;\n"
            f"\n"
            f"architecture rtl of {fn.name}_pipeline is\n"
            f"\n"
            f"{body_block}\n"
            f"\n"
            f"begin\n"
            f"    -- Registered output: one cycle latency between\n"
            f"    -- valid_in and valid_out (combinational body).\n"
            f"    process(clk)\n"
            f"    begin\n"
            f"        if rising_edge(clk) then\n"
            f"            if rst = '1' then\n"
            f"                valid_out <= '0';\n"
            f"                result    <= (others => '0');\n"
            f"            else\n"
            f"                valid_out <= valid_in;\n"
            f"                result    <= {output_signal};\n"
            f"            end if;\n"
            f"        end if;\n"
            f"    end process;\n"
            f"\n"
            f"end architecture rtl;\n"
        )

    @staticmethod
    def _final_expr(fn: EMLFunction) -> ASTNode:
        if fn.body is None or fn.body.kind != NodeKind.BLOCK:
            raise CompileError(f"function {fn.name} has no parsed body")
        bindings: dict[str, ASTNode] = {}
        final: ASTNode | None = None
        for stmt in fn.body.children:
            if stmt.kind == NodeKind.LET:
                bindings[stmt.value] = stmt.children[0]
            elif stmt.kind in (NodeKind.LET_MUT, NodeKind.WHILE,
                               NodeKind.ASSIGN, NodeKind.EXPR_STMT):
                continue
            else:
                final = stmt
        if final is None:
            raise CompileError(
                f"function {fn.name} has no final expression"
            )
        if bindings:
            final = _inline(final, bindings)
        return final

    def _design_precision(
        self, fn: EMLFunction, plan: AllocationPlan,
    ) -> int:
        if plan.transcendental_units:
            return max(u.precision_bits for u in plan.transcendental_units)
        co = (fn.profile or {}).get("chain_order", 0)
        if co >= 3:
            return 64
        if co >= 1:
            return 32
        return 32

    # ── Expression emission ──────────────────────────────────

    def _emit_expr(self, node: ASTNode, scope: _Scope) -> str:
        cache_key = id(node)
        if cache_key in scope.node_signals:
            return scope.node_signals[cache_key]

        kind = node.kind
        out_name: str

        if kind == NodeKind.LITERAL:
            out_name = self._literal(node, scope)
        elif kind == NodeKind.VAR:
            out_name = str(node.value)
        elif kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], scope)
            out_name = scope.fresh_signal()
            if node.value == "-":
                scope.assigns.append(f"    {out_name} <= -{sub};")
            elif node.value == "!":
                scope.assigns.append(f"    {out_name} <= not {sub};")
            else:
                raise CompileError(f"unary {node.value!r}")
        elif kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], scope)
            right = self._emit_expr(node.children[1], scope)
            op = _BINOP_TO_VHDL.get(node.value)
            if op is None:
                raise CompileError(f"binop {node.value!r}")
            out_name = scope.fresh_signal()
            scope.assigns.append(
                f"    {out_name} <= {left} {op} {right};"
            )
        elif kind in _TRANSCENDENTAL_TO_MODULE:
            out_name = self._instance(
                _TRANSCENDENTAL_TO_MODULE[kind],
                node.children, scope,
            )
        elif kind == NodeKind.EML:
            x_in = self._emit_expr(node.children[0], scope)
            y_in = self._emit_expr(node.children[1], scope)
            exp_out = self._instance_raw("eml_exp", [x_in], scope)
            ln_out = self._instance_raw("eml_ln", [y_in], scope)
            out_name = scope.fresh_signal()
            scope.assigns.append(
                f"    {out_name} <= {exp_out} - {ln_out};"
            )
        elif kind == NodeKind.CLAMP:
            x_w = self._emit_expr(node.children[0], scope)
            lo_w = self._emit_expr(node.children[1], scope)
            hi_w = self._emit_expr(node.children[2], scope)
            out_name = scope.fresh_signal()
            scope.assigns.append(
                f"    {out_name} <= {lo_w} when {x_w} < {lo_w} else "
                f"{hi_w} when {x_w} > {hi_w} else {x_w};"
            )
        elif kind == NodeKind.ABS:
            sub = self._emit_expr(node.children[0], scope)
            out_name = scope.fresh_signal()
            scope.assigns.append(
                f"    {out_name} <= -{sub} when {sub} < 0 else {sub};"
            )
        elif kind == NodeKind.POW:
            out_name = self._instance("eml_pow", node.children, scope)
        elif kind == NodeKind.CALL:
            arg_signals = [
                self._emit_expr(c, scope) for c in node.children
            ]
            out_name = self._instance_raw(
                f"{node.value}_pipeline", arg_signals, scope,
            )
        else:
            raise CompileError(
                f"NodeKind {kind} (line {node.line}:{node.col})"
            )

        scope.node_signals[cache_key] = out_name
        return out_name

    def _literal(self, node: ASTNode, scope: _Scope) -> str:
        v = node.value
        out = scope.fresh_signal()
        if isinstance(v, bool):
            scope.assigns.append(
                f"    {out} <= to_signed({1 if v else 0}, WIDTH);"
            )
            return out
        if isinstance(v, (int, float)):
            # Reuse Q-format encoder; emit as VHDL `to_signed(N, WIDTH)`.
            verilog_lit = format_verilog_literal(v, scope.qformat)
            # verilog literal looks like "<width>'sd<int>" or "<width>'sdN<int>";
            # extract the integer portion in the simplest case.
            int_part = _extract_signed_int(verilog_lit)
            scope.assigns.append(
                f"    {out} <= to_signed({int_part}, WIDTH);  -- {v}"
            )
            return out
        raise CompileError(f"literal {v!r}")

    def _instance(
        self, module_name: str, arg_nodes: list[ASTNode], scope: _Scope,
    ) -> str:
        arg_signals = [self._emit_expr(c, scope) for c in arg_nodes]
        return self._instance_raw(module_name, arg_signals, scope)

    def _instance_raw(
        self, module_name: str, arg_signals: list[str], scope: _Scope,
    ) -> str:
        out = scope.fresh_signal()
        inst_name = scope.fresh_instance(module_name)
        port_lines: list[str] = []
        for i, sig in enumerate(arg_signals):
            port_lines.append(f"            x{i} => {sig}")
        ports = ",\n".join(port_lines)
        scope.instances.append(
            f"    {inst_name} : entity work.{module_name}\n"
            f"        generic map (WIDTH => WIDTH)\n"
            f"        port map (\n"
            f"            clk => clk, rst => rst, valid_in => valid_in,\n"
            f"{ports},\n"
            f"            valid_out => open, result => {out}\n"
            f"        );"
        )
        return out


def _inline(node: ASTNode, bindings: dict[str, ASTNode]) -> ASTNode:
    if node.kind == NodeKind.VAR and node.value in bindings:
        return _inline(bindings[node.value], bindings)
    new_children = [_inline(c, bindings) for c in node.children]
    return ASTNode(
        kind=node.kind,
        value=node.value,
        children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line,
        col=node.col,
    )


def _extract_signed_int(verilog_literal: str) -> str:
    """Recover the integer portion of a Q-format Verilog literal so
    we can re-emit it as `to_signed(N, WIDTH)` in VHDL.

    Verilog literals from format_verilog_literal look like
    `32'sd12345`, `-32'sd12345`, `32'shFFFF`, etc. We accept the
    common decimal forms and fall back to 0 with a comment for
    anything exotic.
    """
    s = verilog_literal.strip()
    sign = ""
    if s.startswith("-"):
        sign = "-"
        s = s[1:]
    if "'sd" in s:
        return sign + s.split("'sd", 1)[1]
    if "'sh" in s:
        # Hex literal -- convert to decimal.
        hex_part = s.split("'sh", 1)[1]
        try:
            return sign + str(int(hex_part, 16))
        except ValueError:
            return "0"
    return sign + "0"
