"""AADL (Architecture Analysis & Design Language) backend.

Emits a single ``.aadl`` package describing the EML-lang module
as a system architecture: each verified function becomes a
``thread`` (or ``subprogram``, if no ``@target(fpga)`` rate is
declared) with ``in`` data ports for each parameter and an ``out``
data port for the result.

When the function carries ``@target(fpga, clock_mhz = N)``, the
period property is derived from the clock (``period = 1 / N MHz``
expressed in milliseconds). Otherwise ``Compute_Execution_Time``
is left as a placeholder for the integrator.

This is the artefact a defense systems-engineer drops into the
OSATE2 architecture model so the Forge-emitted controller
participates in the larger system's timing / latency / WCET
analysis.

Output shape
============

Single ``.aadl`` text block. ``compile()`` returns it directly --
no companion ARXML. Reference: AADL v2.2 (SAE AS5506C / 2024).

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 4 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    EMLConstant,
    EMLFunction,
    EMLModule,
)


def _package_name(mod: EMLModule) -> str:
    """AADL package names follow Title_Case convention."""
    base = mod.name or "Forge_Module"
    parts = base.split("_")
    return "_".join(p[:1].upper() + p[1:].lower() for p in parts) or "Forge_Module"


def _system_name(mod: EMLModule) -> str:
    return f"{_package_name(mod)}_System"


# EML type → AADL Base_Types library entry. AADL's Base_Types
# package ships with most stdlib distributions; we use Float_64
# for analytical types since AUTOSAR / DO-178C ECUs converge on
# IEEE-754 binary64 for control loops.
_TYPE_TO_AADL: dict[str, str] = {
    "Real": "Base_Types::Float_64",
    "f64":  "Base_Types::Float_64",
    "f32":  "Base_Types::Float_32",
    "f16":  "Base_Types::Float_32",
    "bf16": "Base_Types::Float_32",
    "u8":   "Base_Types::Unsigned_8",
    "u16":  "Base_Types::Unsigned_16",
    "u32":  "Base_Types::Unsigned_32",
    "u64":  "Base_Types::Unsigned_64",
    "i8":   "Base_Types::Integer_8",
    "i16":  "Base_Types::Integer_16",
    "i32":  "Base_Types::Integer_32",
    "i64":  "Base_Types::Integer_64",
    "bool": "Base_Types::Boolean",
}


def _aadl_type(eml_type: str) -> str:
    return _TYPE_TO_AADL.get(eml_type, "Base_Types::Float_64")


class CompileError(Exception):
    """Raised when no function in the module is wrappable."""


class AadlBackend:
    """Compile an EMLModule to an AADL architecture model."""

    name = "aadl"

    def __init__(self, indent: str = "  ", *, optimize: bool = True):
        # AADL conventionally uses 2-space indent (per OSATE2 examples).
        self.indent = indent
        self.optimize = optimize

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        threads = [f for f in mod.functions if not f.is_extern]
        if not threads:
            raise CompileError(
                "AADL backend: module has no functions to model "
                "as a system component."
            )

        pkg = _package_name(mod)
        sys_name = _system_name(mod)

        lines: list[str] = [
            f"-- Generated by EML-lang AADL backend",
            f"-- Source module: {mod.name or '(unnamed)'}",
            f"-- Source file:   {mod.source_file}",
            f"-- Threads:       {len(threads)}",
            "",
            f"package {pkg}",
            "public",
            "",
            "with Base_Types;",
            "",
        ]

        # Top-level system aggregating every thread.
        lines.append(f"system {sys_name}")
        sys_features = self._aggregate_features(threads)
        if sys_features:
            lines.append("features")
            for ln in sys_features:
                lines.append(self.indent + ln)
        lines.append(f"end {sys_name};")
        lines.append("")

        lines.append(f"system implementation {sys_name}.impl")
        lines.append("subcomponents")
        for fn in threads:
            lines.append(
                f"{self.indent}{fn.name} : thread {self._thread_type_name(fn)};"
            )
        lines.append(f"end {sys_name}.impl;")
        lines.append("")

        # Per-function thread types + implementations.
        for fn in threads:
            lines.extend(self._emit_thread_type(fn))
            lines.append("")
            lines.extend(self._emit_thread_impl(fn))
            lines.append("")

        lines.append(f"end {pkg};")
        return "\n".join(lines).rstrip() + "\n"

    # ── Aggregation ───────────────────────────────────────────

    def _aggregate_features(
        self, threads: list[EMLFunction],
    ) -> list[str]:
        """For the top-level system, expose every thread's ports
        with a `<thread>_<port>` prefix so the names are unique
        even when multiple threads share parameter names."""
        out: list[str] = []
        for fn in threads:
            for p in fn.params:
                out.append(
                    f"{fn.name}_{p.name} : in data port "
                    f"{_aadl_type(p.type_name)};"
                )
            out.append(
                f"{fn.name}_result : out data port "
                f"{_aadl_type(fn.return_type or 'Real')};"
            )
        return out

    # ── Per-thread emit ───────────────────────────────────────

    def _thread_type_name(self, fn: EMLFunction) -> str:
        parts = fn.name.split("_")
        return "".join(p[:1].upper() + p[1:].lower() for p in parts) + "_T"

    def _emit_thread_type(self, fn: EMLFunction) -> list[str]:
        ttype = self._thread_type_name(fn)
        out: list[str] = [f"thread {ttype}"]
        out.append("features")
        for p in fn.params:
            out.append(
                f"{self.indent}{p.name} : in data port "
                f"{_aadl_type(p.type_name)};"
            )
        out.append(
            f"{self.indent}result : out data port "
            f"{_aadl_type(fn.return_type or 'Real')};"
        )

        # Properties: period from @target(fpga, clock_mhz=N), or
        # placeholder if absent. Compute_Execution_Time is bounded
        # via the profile's FPGA estimate when available.
        props: list[str] = self._derive_properties(fn)
        if props:
            out.append("properties")
            for prop in props:
                out.append(self.indent + prop)
        out.append(f"end {ttype};")
        return out

    def _emit_thread_impl(self, fn: EMLFunction) -> list[str]:
        ttype = self._thread_type_name(fn)
        out: list[str] = [f"thread implementation {ttype}.impl"]

        # We don't model subprogram calls explicitly -- the thread
        # body is opaque to AADL. Forge supplies the actual
        # implementation via the C / Ada / etc. backends; AADL
        # captures the *contract*.
        out.append("properties")
        out.append(
            self.indent
            + 'Source_Language => (C);  '
              '-- the Forge C backend supplies the binary'
        )
        out.append(f"end {ttype}.impl;")
        return out

    # ── Property derivation ───────────────────────────────────

    def _derive_properties(self, fn: EMLFunction) -> list[str]:
        out: list[str] = []

        # Period from clock_mhz when present.
        for a in fn.annotations:
            if a.kind == "target" and a.args.get(0) == "fpga":
                clk = a.args.get("clock_mhz")
                if clk:
                    try:
                        ms = 1.0 / (float(clk))  # 1 / N MHz = 1/N μs in float
                        # 1/N μs = (1000/N) ns.  Express as μs.
                        period_us = 1.0 / float(clk)  # in microseconds
                        # Round to a sensible precision.
                        out.append(
                            f"Period => {period_us:.3f} us;"
                        )
                    except (TypeError, ValueError):
                        pass

        # Compute_Execution_Time bounds from the FPGA profile.
        if fn.profile is not None:
            fpga = fn.profile.get("fpga_estimate") or {}
            cycles = fpga.get("estimated_latency_cycles")
            if cycles:
                out.append(
                    f"Compute_Execution_Time => 0 us .. {cycles} us;  "
                    f"-- upper bound from chain-order pipeline depth"
                )

        # Dispatch protocol: periodic when @target(fpga); otherwise
        # leave to the integrator.
        if any(
            a.kind == "target" and a.args.get(0) == "fpga"
            for a in fn.annotations
        ):
            out.append("Dispatch_Protocol => Periodic;")

        return out
