"""C99 backend -- emits standalone .c files using libmonogate.h.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.1.
SCAFFOLD.
"""

from __future__ import annotations

from lang.parser.ast_nodes import ASTNode, EMLFunction, NodeKind


class CBackend:
    """Compile an EMLFunction list to C99 source."""

    name = "c"

    def compile(self, program: list[EMLFunction]) -> str:
        lines = [
            '#include "libmonogate.h"',
            '#include <math.h>',
            '',
            '/* Generated by EML-lang compiler */',
            f'/* Total functions: {len(program)} */',
            '',
        ]
        for func in program:
            lines.append(self.compile_function(func))
            lines.append('')
        return "\n".join(lines)

    def compile_function(self, func: EMLFunction) -> str:
        params = ", ".join(f"double {p['name']}" for p in func.params)
        header = f"double {func.name}({params})"
        comment = self._profile_comment(func)
        body = self.compile_expr(func.body)
        return f"{comment}\n{header} {{\n    return {body};\n}}"

    def compile_expr(self, node: ASTNode | None) -> str:
        if node is None:
            return "0.0  /* TODO: empty body */"
        # SCAFFOLD: dispatch on NodeKind. Real cases land in Phase 2.1.
        if node.kind == NodeKind.LITERAL:
            return repr(float(node.value))
        if node.kind == NodeKind.VAR:
            return str(node.value)
        if node.kind == NodeKind.EXP:
            return f"mg_exp({self.compile_expr(node.children[0])})"
        if node.kind == NodeKind.LN:
            return f"mg_ln({self.compile_expr(node.children[0])})"
        if node.kind == NodeKind.SIN:
            return f"mg_sin({self.compile_expr(node.children[0])})"
        if node.kind == NodeKind.COS:
            return f"mg_cos({self.compile_expr(node.children[0])})"
        if node.kind == NodeKind.SQRT:
            return f"mg_sqrt({self.compile_expr(node.children[0])})"
        if node.kind == NodeKind.EML:
            l = self.compile_expr(node.children[0])
            r = self.compile_expr(node.children[1])
            return f"mg_eml({l}, {r})"
        if node.kind == NodeKind.BINOP:
            l = self.compile_expr(node.children[0])
            r = self.compile_expr(node.children[1])
            return f"({l} {node.value} {r})"
        return f"/* TODO: NodeKind={node.kind} */ 0.0"

    def _profile_comment(self, func: EMLFunction) -> str:
        if not func.profile:
            return f"/* {func.name}: profile unavailable */"
        p = func.profile
        return (
            f"/*\n"
            f" * {func.name}\n"
            f" * Chain order: {p.get('chain_order')}\n"
            f" * Cost class: {p.get('cost_class')}\n"
            f" * Nodes: {p.get('node_count')} (SuperBEST optimal)\n"
            f" * Dynamics: {p.get('dynamics')}\n"
            f" * FPGA estimate: {p.get('fpga_estimate')}\n"
            f" */"
        )
