"""C++17 backend -- emits a single .cpp/.hpp combined header.

The C++ backend is the C backend's older sibling: same NodeKind
dispatch, same builtin map, but emits namespaced functions with
Doxygen contracts derived from `requires` / `ensures`. Functions
that the profiler marks as chain order 0 -- pure compile-time
expressions -- are emitted as `constexpr`, letting the C++ compiler
fold them into call sites.

Output shape
============

A single header-only `.cpp` file with::

    #pragma once
    #include <algorithm>  // std::clamp
    #include <cmath>      // std::exp, std::log, ...

    namespace forge::<module> {

      constexpr double KP = 2.5;
      ...

      /// @pre  std::abs(pitch_setpoint) < 1.5708
      /// @post std::abs(result) < ELEVATOR_MAX
      [[nodiscard]] constexpr double autopilot_step(
          double pitch_setpoint,
          double pitch_measured,
          double pitch_integral) noexcept;

    }  // namespace forge::<module>

Mapping
=======

Most of the Mapping section duplicates the C backend; the C++
specifics are:
  - `namespace forge::<module> { ... }` from EML module name
  - `constexpr` on chain-order-0 functions (compile-time foldable)
  - `[[nodiscard]]` on every function so callers can't silently
    drop a return value
  - `noexcept` on chain-order-0 (no math.h trap) -- omitted on
    higher chain orders since std::exp can throw FE_INVALID
  - `std::clamp(x, lo, hi)` for CLAMP, `std::abs` for ABS
  - `EML(x, y)` is `(std::exp(x) - std::log(y))` inlined since
    libmonogate isn't a C++ dependency yet

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 1 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> std::<fn>. C++17's <cmath> lifts every libm
# routine into namespace std with overloads for float / double /
# long double, so we don't need separate float/double maps.
_BUILTIN_TO_CPP: dict[NodeKind, str] = {
    NodeKind.EXP:   "std::exp",
    NodeKind.LN:    "std::log",
    NodeKind.SIN:   "std::sin",
    NodeKind.COS:   "std::cos",
    NodeKind.TAN:   "std::tan",
    NodeKind.SQRT:  "std::sqrt",
    NodeKind.ABS:   "std::abs",
    NodeKind.ASIN:  "std::asin",
    NodeKind.ACOS:  "std::acos",
    NodeKind.ATAN:  "std::atan",
    NodeKind.SINH:  "std::sinh",
    NodeKind.COSH:  "std::cosh",
    NodeKind.TANH:  "std::tanh",
    NodeKind.POW:   "std::pow",
}

# EML type -> C++ type. Default to double; explicit Real → double.
_TYPE_TO_CPP: dict[str, str] = {
    "Real":  "double",
    "f64":   "double",
    "f32":   "float",
    "f16":   "float",   # No portable f16 in C++17; promote
    "bf16":  "float",
    "u8":    "std::uint8_t",
    "u16":   "std::uint16_t",
    "u32":   "std::uint32_t",
    "u64":   "std::uint64_t",
    "i8":    "std::int8_t",
    "i16":   "std::int16_t",
    "i32":   "std::int32_t",
    "i64":   "std::int64_t",
    "bool":  "bool",
}


def _cpp_type(eml_type: str) -> str:
    return _TYPE_TO_CPP.get(eml_type, "double")


def _has_cmath_descendant(node: ASTNode | None) -> bool:
    """True if `node` or any of its descendants is a NodeKind
    that lowers to a <cmath> call. EML / CALL nodes are also
    treated as opaque (we can't prove the callee is constexpr),
    so we conservatively reject them too."""
    if node is None:
        return False
    if node.kind in _BUILTIN_TO_CPP:
        return True
    if node.kind in (NodeKind.EML, NodeKind.CALL):
        return True
    return any(_has_cmath_descendant(c) for c in node.children)


def _namespace(mod: EMLModule) -> str:
    """`forge::<module_name>` -- module names are kept snake_case
    so they're valid C++ identifiers without further mangling."""
    base = mod.name or "anon"
    return f"forge::{base}"


class CompileError(Exception):
    """Raised on a NodeKind the C++ backend doesn't recognize."""


class CppBackend:
    """Compile an EMLModule to header-only C++17 source."""

    name = "cpp"

    def __init__(self, indent: str = "  ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        ns = _namespace(mod)

        lines: list[str] = [
            "// Generated by EML-lang C++17 backend",
            f"// Source module: {mod.name or '(unnamed)'}",
            f"// Source file:   {mod.source_file}",
            f"// Functions:     {len(mod.functions)}",
            f"// Constants:     {len(mod.constants)}",
            "",
            "#pragma once",
            "",
            "#include <algorithm>",
            "#include <cmath>",
            "#include <cstdint>",
            "",
            f"namespace {ns} {{",
            "",
        ]

        # Constants — constexpr at namespace scope.
        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        # Functions
        for fn in mod.functions:
            if fn.is_extern:
                lines.extend(self._emit_extern(fn))
                lines.append("")
                continue
            lines.extend(self._emit_function(fn))
            lines.append("")

        lines.append(f"}}  // namespace {ns}")
        return "\n".join(lines).rstrip() + "\n"

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        cpp_type = _cpp_type(c.type_name)
        rhs = self._emit_expr(c.value)
        # `constexpr` makes them usable in template / array-size
        # contexts and lets the optimiser fold them at compile time.
        return [f"constexpr {cpp_type} {c.name} = {rhs};"]

    # ── Extern (FFI) functions ────────────────────────────────

    def _emit_extern(self, fn: EMLFunction) -> list[str]:
        ret_type = _cpp_type(fn.return_type or "Real")
        params = ", ".join(
            f"{_cpp_type(p.type_name)} {p.name}" for p in fn.params
        )
        return [
            f"// extern: {fn.name} -- linker-resolved declaration",
            f'extern "C" {ret_type} {fn.name}({params});',
        ]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._doxygen(fn)

        # constexpr eligibility: chain-order-0 means no exp / log /
        # sin / cos in the body, so we can mark constexpr safely.
        # `noexcept` rides along since libm-style traps can't fire
        # without those.
        is_pure = self._is_constexpr_eligible(fn)
        qualifiers: list[str] = ["[[nodiscard]]"]
        if is_pure:
            qualifiers.append("constexpr")
        ret_type = _cpp_type(fn.return_type or "Real")
        params = ", ".join(
            f"{_cpp_type(p.type_name)} {p.name}" for p in fn.params
        )
        head = " ".join(qualifiers) + f" {ret_type} {fn.name}({params})"
        if is_pure:
            head += " noexcept"

        out.append(head + " {")
        body = self._emit_block(fn.body, return_value=True)
        for ln in body:
            out.append(self.indent + ln)
        out.append("}")
        return out

    @staticmethod
    def _is_constexpr_eligible(fn: EMLFunction) -> bool:
        """C++17 forbids `constexpr` over <cmath> entry points
        (std::cos / std::exp / std::sqrt / etc.). C++23 relaxes
        most of them but we target C++17 to stay portable. So
        the test is structural: walk the body, reject if any
        descendant maps to a _BUILTIN_TO_CPP entry. This is more
        conservative than the profiler's chain_order metric
        because the optimiser can inline a transcendental into
        a chain-0 caller."""
        if fn.profile is None:
            return False
        if fn.profile.get("status") == "complex_body":
            return False
        return not _has_cmath_descendant(fn.body)

    # ── Doxygen / contract translation ────────────────────────

    def _doxygen(self, fn: EMLFunction) -> list[str]:
        out: list[str] = ["/**"]
        out.append(f" * @brief {fn.name}")

        if fn.profile is not None:
            p = fn.profile
            if p.get("status") == "complex_body":
                out.append(f" * @note  COMPLEX BODY: {p.get('note', '')}")
            else:
                cc = p.get("cost_class", "?")
                co = p.get("chain_order", "?")
                depth = p.get("eml_depth", "?")
                drift = p.get("fp16_drift_risk", "?")
                out.append(f" * @profile chain_order={co}  cost_class={cc}")
                out.append(f" *          eml_depth={depth}  drift_risk={drift}")
        out.append(" *")
        for r in fn.requires:
            try:
                out.append(f" * @pre  {self._emit_expr(r)}")
            except CompileError:
                out.append(f" * @pre  (unsupported)")
        for r in fn.ensures:
            try:
                expr = self._emit_expr(r, result_subst="result")
                out.append(f" * @post {expr}")
            except CompileError:
                out.append(f" * @post (unsupported)")
        for a in fn.annotations:
            if a.kind == "verify":
                tname = a.args.get("theorem", fn.name)
                out.append(f" * @verify lean theorem={tname}")
        out.append(" */")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["// empty block"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind == NodeKind.LET:
                cpp_type = _cpp_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"const {cpp_type} {stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.LET_MUT:
                cpp_type = _cpp_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{cpp_type} {stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"while ({cond}) {{")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("}")
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(f"{self._emit_expr(stmt.children[0])};")
            elif is_last and return_value:
                out.append(f"return {self._emit_expr(stmt)};")
            else:
                out.append(f"{self._emit_expr(stmt)};")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            return f"({left} {node.value} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"std::make_tuple({elems})"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"std::clamp({x}, {lo}, {hi})"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            # EML(x, y) = exp(x) - log(y); inline since libmonogate
            # is C-only today.
            return f"(std::exp({x}) - std::log({y}))"

        if kind in _BUILTIN_TO_CPP:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{_BUILTIN_TO_CPP[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{node.value}({args})"

        raise CompileError(
            f"C++ backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
