"""GDScript (Godot Engine) backend.

Produces a Godot 4.x GDScript source file from an `EMLModule`.
The output extends Node and exposes every kernel as a `static func`
so callers can attach the script to a Node and call methods on it,
or load it as an Autoload singleton (`Project Settings > Autoload`)
and call functions module-style (`MyModule.kernel_name(args)`).

Key differences from the Python backend:

  - `func` instead of `def`
  - Type hints in GDScript-style (`p: float -> float`)
  - Math functions are global (`sin(x)`, not `math.sin(x)`)
  - Boolean literals are lowercase (`true` / `false`)
  - Logical ops: `and` / `or` / `not`
  - File header carries `extends Node` + `class_name`
  - Functions are `static func` so the file works either as a
    Node script or as an Autoload singleton

Mirrors python_backend.py's direct-AST emit path. The SymPy bridge
is intentionally NOT used because Tool 5 emits `math.X(...)` calls
that would need post-processing -- the direct emitter is simpler
and handles every NodeKind the gaming verticals produce.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# ── Phase E.3: refinement-guard helpers (module-level, by convention) ─

def _substitute_var(node: ASTNode, old: str, new: str) -> ASTNode:
    """Return a new ASTNode with every VAR named `old` replaced by `new`."""
    if node.kind == NodeKind.VAR and node.value == old:
        return ASTNode(
            kind=node.kind, value=new, children=[],
            type_annotation=node.type_annotation,
            chain_constraint=node.chain_constraint,
            line=node.line, col=node.col,
        )
    new_children = [_substitute_var(c, old, new) for c in node.children]
    return ASTNode(
        kind=node.kind, value=node.value, children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line, col=node.col,
    )


def _var_names(node: ASTNode) -> set[str]:
    """Collect every VAR name appearing in `node`."""
    names: set[str] = set()
    if node.kind == NodeKind.VAR:
        names.add(node.value)
    for c in node.children:
        names.update(_var_names(c))
    return names


_BUILTIN_TO_GD: dict[NodeKind, str] = {
    NodeKind.EXP:   "exp",
    NodeKind.LN:    "log",
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.SQRT:  "sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "asin",
    NodeKind.ACOS:  "acos",
    NodeKind.ATAN:  "atan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
    NodeKind.POW:   "pow",
}


_GD_RESERVED: set[str] = {
    # GDScript 2.0 reserved words that would clash with EML
    # parameter / variable names. We rename collisions to `name_`.
    "and", "or", "not", "in", "is", "as", "if", "else", "elif",
    "for", "while", "return", "var", "const", "func", "class",
    "class_name", "extends", "static", "signal", "enum", "true",
    "false", "null", "self", "super", "match", "when", "break",
    "continue", "pass", "yield", "await", "void", "int", "float",
    "bool", "String", "Vector2", "Vector3", "preload", "load",
    "tool", "PI", "TAU", "INF", "NAN",
}


class CompileError(Exception):
    """Raised when the GDScript backend genuinely can't translate a node."""


def _safe_ident(name: str) -> str:
    if name in _GD_RESERVED:
        return f"{name}_"
    return name


class GDScriptBackend:
    """Compile an EMLModule to GDScript 2.0 (Godot 4.x) source.

    Generated file is ready to attach to a Node or register as an
    Autoload. `optimize=True` (default) runs the EML optimizer
    pipeline (inline / CSE / SuperBEST / shake-imports) before emit.
    """

    name = "gdscript"

    def __init__(self, indent: str = "\t", *, optimize: bool = True):
        # GDScript style guide says use TAB for indent.
        self.indent = indent
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        class_name = self._class_name_for(mod)
        src_file = str(mod.source_file).replace("\\", "/")

        lines: list[str] = [
            f"# Generated by EML-lang GDScript backend.",
            f"# Source module: {mod.name or '(unnamed)'}",
            f"# Source file:   {src_file}",
            f"# Functions:     {len(mod.functions)}",
            f"# Constants:     {len(mod.constants)}",
            f"#",
            f"# Attach this script to a Node, or register it as an",
            f"# Autoload singleton (Project Settings > Autoload) to",
            f"# call its kernels module-style: {class_name}.kernel(args).",
            "",
            "extends Node",
            f"class_name {class_name}",
            "",
        ]

        if mod.constants:
            for c in mod.constants:
                lines.extend(self._emit_constant(c))
            lines.append("")

        for fn in mod.functions:
            lines.extend(self._emit_function(fn))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    # ── Class name from module name ───────────────────────────

    @staticmethod
    def _class_name_for(mod: EMLModule) -> str:
        """`my_module` -> `MyModule`. Falls back to `EmlModule`."""
        raw = mod.name or "eml_module"
        parts = [p for p in raw.split("_") if p]
        if not parts:
            return "EmlModule"
        return "".join(p[:1].upper() + p[1:] for p in parts)

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        return [f"const {c.name}: float = {self._emit_expr(c.value)}"]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._profile_comment(fn)

        params = ", ".join(
            f"{_safe_ident(p.name)}: float" for p in fn.params
        )
        # All gaming kernels return Real (-> float). EML has no
        # other scalar type today; tuple returns become an Array.
        ret_ty = "Array" if self._returns_tuple(fn) else "float"
        out.append(f"static func {fn.name}({params}) -> {ret_ty}:")

        # Phase E.3: refinement guards fire BEFORE requires guards.
        for ln in self._emit_refinement_guards(fn):
            out.append(self.indent + ln)

        # `requires` clauses lower to GDScript native assert(cond, "msg").
        for r in fn.requires:
            try:
                cond = self._emit_expr(r)
                msg = f"{fn.name}: requires ({cond})"
                out.append(f'{self.indent}assert({cond}, "{msg}")')
            except CompileError as e:
                out.append(f"{self.indent}# requires: unsupported ({e})")

        # Phase G: `assume` clauses -- trusted hypotheses, zero runtime cost.
        for a in fn.assumes:
            try:
                out.append(f"{self.indent}# assume: {self._emit_expr(a)}")
            except CompileError as e:
                out.append(f"{self.indent}# assume: unsupported ({e})")

        body = self._emit_body(fn)
        for ln in body:
            out.append(self.indent + ln)
        return out

    # ── Phase E.3: refinement guards ─────────────────────────────

    def _emit_refinement_guards(self, fn: EMLFunction) -> list[str]:
        """Return one assert() line per refined parameter.

        Cross-param refinements emit a comment-only obligation line.
        """
        out: list[str] = []
        param_names = {p.name for p in fn.params}
        for p in fn.params:
            if p.refinement is None:
                continue
            ref = p.refinement
            pred = _substitute_var(ref.predicate, ref.binder, p.name)
            pred_vars = _var_names(pred)
            other_params_in_pred = (pred_vars - {p.name}) & param_names
            if other_params_in_pred:
                try:
                    cond_str = self._emit_expr(pred)
                except CompileError as e:
                    cond_str = f"<unsupported: {e}>"
                out.append(
                    f"# refinement obligation: {fn.name}: {p.name}: {cond_str}"
                )
                continue
            try:
                cond = self._emit_expr(pred)
                msg = f"{fn.name}: refinement violated on {p.name}: {cond}"
                out.append(f'assert({cond}, "{msg}")')
            except CompileError as e:
                out.append(f"# refinement: unsupported ({e})")
        return out

    @staticmethod
    def _returns_tuple(fn: EMLFunction) -> bool:
        if fn.body is None:
            return False
        # Walk the block to find the trailing expression.
        if fn.body.kind != NodeKind.BLOCK or not fn.body.children:
            return False
        last = fn.body.children[-1]
        return last.kind == NodeKind.TUPLE

    def _emit_body(self, fn: EMLFunction) -> list[str]:
        if fn.body is None or fn.body.kind != NodeKind.BLOCK:
            return ["pass"]
        return self._emit_block(fn.body, return_value=True)

    def _emit_block(
        self,
        block: ASTNode,
        *,
        return_value: bool,
    ) -> list[str]:
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind in (NodeKind.LET, NodeKind.LET_MUT):
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"var {_safe_ident(stmt.value)} = {rhs}")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{_safe_ident(stmt.value)} = {rhs}")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"while {cond}:")
                for ln in inner:
                    out.append(self.indent + ln)
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(self._emit_expr(stmt.children[0]))
            elif is_last:
                expr = self._emit_expr(stmt)
                out.append(f"return {expr}" if return_value else expr)
            else:
                out.append(self._emit_expr(stmt))
        return out or ["pass"]

    # ── Expression emit ───────────────────────────────────────

    def _emit_expr(self, node: ASTNode) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                # GDScript distinguishes int/float; emit as float
                # so arithmetic with float constants stays consistent.
                return f"{float(v)!r}"
            if isinstance(v, float):
                return repr(v)
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            return _safe_ident(str(node.value))

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0])
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(not {sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0])
            right = self._emit_expr(node.children[1])
            op = node.value
            if op == "&&":
                op = "and"
            elif op == "||":
                op = "or"
            return f"({left} {op} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(self._emit_expr(c) for c in node.children)
            return f"[{elems}]"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (self._emit_expr(c) for c in node.children)
            # GDScript's built-in clamp does the right thing.
            return f"clamp({x}, {lo}, {hi})"

        if kind in _BUILTIN_TO_GD:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            return f"{_BUILTIN_TO_GD[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            # In-module calls dispatch via `self.fn(...)` for instance
            # but `static func` requires the class-qualified form.
            # Static methods can call each other with bare `fn(...)`
            # inside the same script, so leave it bare.
            return f"{node.value}({args})"

        raise CompileError(
            f"GDScript backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )

    # ── Profile comment ───────────────────────────────────────

    def _profile_comment(self, fn: EMLFunction) -> list[str]:
        if fn.profile is None:
            return [f"# {fn.name}: no profile available"]
        p = fn.profile
        if p.get("status") == "complex_body":
            return [
                f"# {fn.name} -- COMPLEX BODY",
                f"# note: {p.get('note', '')}",
            ]
        cc = p.get("cost_class", "?")
        co = p.get("chain_order", "?")
        depth = p.get("eml_depth", "?")
        return [
            f"# {fn.name}",
            f"# Chain order: {co}    Cost class: {cc}    EML depth: {depth}",
        ]
