"""Go 1.21 backend.

Emits a single ``.go`` file with one ``package`` declaration plus
the EML module's functions and constants. Math routines route
through the standard ``math`` package (``math.Exp``, ``math.Log``,
etc. -- Go capitalises exported names).

Mapping
=======

  EML AST kind        →  Go output
  ─────────────────────────────────────
  LITERAL int         →  "42"
  LITERAL float       →  "42.0"
  LITERAL bool        →  "true" / "false"
  VAR                 →  identifier
  BINOP comparisons   →  Go comparison (yields bool)
  BINOP &&/||         →  Go && / ||
  EXP/LN/SIN/COS/...  →  math.Exp/math.Log/math.Sin/...
  ABS(x)              →  math.Abs(x)
  CLAMP(x, lo, hi)    →  math.Max(lo, math.Min(hi, x))
  POW(x, y)           →  math.Pow(x, y)
  EML(x, y)           →  (math.Exp(x) - math.Log(y))
  LET name = expr     →  "name := <expr>"
  LET_MUT name = expr →  "name := <expr>"   (Go has no const distinction
                          inside functions; mutability comes from later
                          assignment)
  ASSIGN name = expr  →  "name = <expr>"
  WHILE cond block    →  "for <cond> { ... }"
  BLOCK               →  brace block; final expression returned
  requires            →  guard + panic; idiomatic Go has no Pre/Post
                          aspects, so we surface the contract as a
                          runtime check at function entry.
  ensures             →  doc-comment annotation only (no auto-assert
                          before return; tools like gocheck cover that).
  @verify(lean, ...)  →  doc-comment cross-link

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 4 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# ── Phase E.1: refinement guard helpers ──────────────────────────────────────


def _substitute_var(node: ASTNode, old: str, new: str) -> ASTNode:
    """Return a new ASTNode tree with every VAR named *old* replaced by *new*.

    Immutable: the original tree is never modified.
    """
    if node.kind == NodeKind.VAR and node.value == old:
        return ASTNode(
            kind=NodeKind.VAR, value=new, children=[],
            type_annotation=node.type_annotation,
            chain_constraint=node.chain_constraint,
            line=node.line, col=node.col,
        )
    new_children = [_substitute_var(c, old, new) for c in node.children]
    return ASTNode(
        kind=node.kind, value=node.value, children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line, col=node.col,
    )


def _var_names(node: ASTNode) -> set[str]:
    """Collect every VAR name that appears anywhere in *node*."""
    names: set[str] = set()
    if node.kind == NodeKind.VAR:
        names.add(str(node.value))
    for c in node.children:
        names.update(_var_names(c))
    return names


# Builtin NodeKind -> Go math package function (note Go capitalises).
_BUILTIN_TO_GO: dict[NodeKind, str] = {
    NodeKind.EXP:   "math.Exp",
    NodeKind.LN:    "math.Log",
    NodeKind.SIN:   "math.Sin",
    NodeKind.COS:   "math.Cos",
    NodeKind.TAN:   "math.Tan",
    NodeKind.SQRT:  "math.Sqrt",
    NodeKind.ABS:   "math.Abs",
    NodeKind.ASIN:  "math.Asin",
    NodeKind.ACOS:  "math.Acos",
    NodeKind.ATAN:  "math.Atan",
    NodeKind.SINH:  "math.Sinh",
    NodeKind.COSH:  "math.Cosh",
    NodeKind.TANH:  "math.Tanh",
    NodeKind.POW:   "math.Pow",
}


_TYPE_TO_GO: dict[str, str] = {
    "Real": "float64",
    "f64":  "float64",
    "f32":  "float32",
    "f16":  "float32",
    "bf16": "float32",
    "u8":   "uint8",
    "u16":  "uint16",
    "u32":  "uint32",
    "u64":  "uint64",
    "i8":   "int8",
    "i16":  "int16",
    "i32":  "int32",
    "i64":  "int64",
    "bool": "bool",
}


def _go_type(eml_type: str) -> str:
    return _TYPE_TO_GO.get(eml_type, "float64")


def _package_name(mod: EMLModule) -> str:
    """Go package names are short, lowercase, and live at the file
    root. We use the EML module name directly (lowercase, no
    underscores ideally -- Go style guide -- but EML modules can
    have underscores so we strip them)."""
    base = mod.name or "forge"
    return base.replace("_", "").lower()


class CompileError(Exception):
    """Raised on a NodeKind the Go backend doesn't recognize."""


class GoBackend:
    """Compile an EMLModule to a single Go source file."""

    name = "go"

    def __init__(self, indent: str = "\t", *, optimize: bool = True):
        # Go's canonical indent is a tab; gofmt enforces it.
        self.indent = indent
        self.optimize = optimize

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        pkg = _package_name(mod)
        lines: list[str] = [
            f"// Generated by EML-lang Go backend",
            f"// Source module: {mod.name or '(unnamed)'}",
            f"// Source file:   {mod.source_file}",
            f"// Functions:     {len(mod.functions)}",
            f"// Constants:     {len(mod.constants)}",
            "",
            f"package {pkg}",
            "",
            'import (',
            f'{self.indent}"math"',
            ')',
            "",
        ]

        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        # Track whether we used `_ = math.Inf` to silence "imported
        # and not used" if there happens to be no math reference;
        # for our generated code this never triggers since profile
        # comments + numeric helpers always cite math.X. But guard
        # against constants-only modules.
        for fn in mod.functions:
            if fn.is_extern:
                lines.extend(self._emit_extern(fn))
            else:
                lines.extend(self._emit_function(fn))
            lines.append("")

        # If neither a function body nor a constant references the
        # math package we'd hit an "imported and not used" error
        # at `go build`. Inject a no-op blank-identifier reference
        # to be safe.
        full = "\n".join(lines)
        if "math." not in full[full.find("import"):]:
            lines.append("var _ = math.Pi  // suppress unused-import on bodyless modules")
            full = "\n".join(lines)
        return full.rstrip() + "\n"

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        go_type = _go_type(c.type_name)
        rhs = self._emit_expr(c.value)
        # Go's `const` requires a constant expression. Unary minus
        # on a literal is constant; arithmetic on other constants is
        # constant. To stay safe with the optimiser's outputs we use
        # `var` instead of `const` for anything past pure literals.
        if c.value.kind == NodeKind.LITERAL:
            return [f"const {c.name} {go_type} = {rhs}"]
        return [f"var {c.name} {go_type} = {rhs}"]

    # ── Extern (FFI) ──────────────────────────────────────────

    def _emit_extern(self, fn: EMLFunction) -> list[str]:
        ret = _go_type(fn.return_type or "Real")
        params = ", ".join(
            f"{p.name} {_go_type(p.type_name)}" for p in fn.params
        )
        return [
            f"// extern: {fn.name} -- supply via cgo / linker",
            f"func {fn.name}({params}) {ret} {{",
            f'{self.indent}panic("{fn.name}: extern not bound")',
            f"}}",
        ]

    # ── Function emit ─────────────────────────────────────────

    def _emit_refinement_guards(self, fn: EMLFunction) -> list[str]:
        """Return one guard line per refined parameter (Phase E.1).

        Binder-substitution: the refinement's binder (p, x, e, …) is
        alpha-renamed to the parameter name before emission so the guard
        operates on the in-scope variable.

        Cross-param refinements (predicate references another parameter)
        are emitted as a comment-only obligation line; a runtime check is
        intractable without value tracking.
        """
        out: list[str] = []
        param_names = {p.name for p in fn.params}
        for p in fn.params:
            if p.refinement is None:
                continue
            ref = p.refinement
            # Substitute binder -> parameter name in the predicate.
            pred = _substitute_var(ref.predicate, ref.binder, p.name)
            # Detect cross-param references: VAR names in the (renamed)
            # predicate that are OTHER parameters.
            pred_vars = _var_names(pred)
            other_params_in_pred = (pred_vars - {p.name}) & param_names
            if other_params_in_pred:
                # Hard Contract #4: emit comment only, no executable guard.
                try:
                    cond_str = self._emit_expr(pred)
                except CompileError as e:
                    cond_str = f"<unsupported: {e}>"
                out.append(
                    f"{self.indent}// refinement obligation: "
                    f"{fn.name}: {p.name}: {cond_str}"
                )
                continue
            try:
                cond = self._emit_expr(pred)
                msg = f"{fn.name}: refinement violated on {p.name}: {cond}"
                out.append(
                    f"{self.indent}if !({cond}) "
                    f'{{ panic("{msg}") }}'
                )
            except CompileError as e:
                out.append(
                    f"{self.indent}// refinement: unsupported ({e})"
                )
        return out

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._doc(fn)
        ret = _go_type(fn.return_type or "Real")
        params = ", ".join(
            f"{p.name} {_go_type(p.type_name)}" for p in fn.params
        )
        out.append(f"func {fn.name}({params}) {ret} {{")

        # Phase E.1: refinement-derived guards fire BEFORE requires guards
        # (refinements correspond to parameter types; requires clauses are
        # user-specified cross-cutting contracts).
        out.extend(self._emit_refinement_guards(fn))

        # `requires` lower to runtime guards via `panic`. Idiomatic
        # Go uses error returns, but Forge contracts are precondition-
        # style so a panic is the closest match (matches Kotlin's
        # require() semantics).
        for r in fn.requires:
            try:
                cond = self._emit_expr(r)
                out.append(
                    f"{self.indent}if !({cond}) "
                    f'{{ panic("{fn.name}: requires {cond}") }}'
                )
            except CompileError as e:
                out.append(f"{self.indent}// require: unsupported ({e})")

        body = self._emit_block(fn.body, return_value=True)
        for ln in body:
            out.append(self.indent + ln)
        out.append("}")
        return out

    # ── Doc comment ───────────────────────────────────────────

    def _doc(self, fn: EMLFunction) -> list[str]:
        out: list[str] = []
        out.append(f"// {fn.name} -- compiled from EML-lang.")
        if fn.profile is not None and fn.profile.get("status") != "complex_body":
            cc = fn.profile.get("cost_class", "?")
            co = fn.profile.get("chain_order", "?")
            drift = fn.profile.get("fp16_drift_risk", "?")
            out.append(
                f"// Pfaffian profile: chain_order={co}, "
                f"cost_class={cc}, drift_risk={drift}."
            )
        for r in fn.requires:
            try:
                out.append(f"// requires: {self._emit_expr(r)}")
            except CompileError:
                pass
        for r in fn.ensures:
            try:
                out.append(
                    f"// ensures:  {self._emit_expr(r, result_subst='result')}"
                )
            except CompileError:
                pass
        for a in fn.annotations:
            if a.kind == "verify":
                tname = a.args.get("theorem", fn.name)
                out.append(f"// @verify lean theorem={tname}")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["// empty body"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind in (NodeKind.LET, NodeKind.LET_MUT):
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} := {rhs}")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"for {cond} {{")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("}")
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(f"{self._emit_expr(stmt.children[0])}")
            elif is_last and return_value:
                out.append(f"return {self._emit_expr(stmt)}")
            else:
                out.append(f"{self._emit_expr(stmt)}")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            return f"({left} {node.value} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            # Go has multi-return; safe to emit as a comma list when
            # in return position. For other positions Go has no
            # tuple literal -- caller needs to use a struct.
            return elems

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"math.Max({lo}, math.Min({hi}, {x}))"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"(math.Exp({x}) - math.Log({y}))"

        if kind in _BUILTIN_TO_GO:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{_BUILTIN_TO_GO[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{node.value}({args})"

        raise CompileError(
            f"Go backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
