"""Java 17 backend.

Emits a single ``.java`` file containing one ``public final class``
per EML module. Functions become ``public static`` methods; module
constants become ``public static final double`` fields. Math
routines route through ``java.lang.Math`` (or ``StrictMath`` if
deterministic cross-platform behaviour is required, but the
default is the platform-tuned ``Math``).

Mapping
=======

  EML AST kind        →  Java output
  ─────────────────────────────────────
  LITERAL int         →  "42"
  LITERAL float       →  "42.0"
  LITERAL bool        →  "true" / "false"
  VAR                 →  identifier (snake_case preserved -- Java
                          allows it; we don't camel-case to keep
                          source-to-source diffability with C/Rust)
  BINOP +/-/*//       →  Java arithmetic
  BINOP comparisons   →  Java comparison (yields boolean)
  BINOP &&/||         →  Java && / ||
  UNARYOP -           →  Java unary minus
  UNARYOP !           →  Java !
  EXP/LN/SIN/COS/...  →  Math.exp/Math.log/Math.sin/...
  ABS(x)              →  Math.abs(x)
  CLAMP(x, lo, hi)    →  Math.max(lo, Math.min(hi, x))
  POW(x, y)           →  Math.pow(x, y)
  EML(x, y)           →  (Math.exp(x) - Math.log(y))
  CALL                →  static method call
  LET name = expr     →  "final double name = <expr>;"
  LET_MUT name = expr →  "double name = <expr>;"
  ASSIGN name = expr  →  "name = <expr>;"
  WHILE cond block    →  while (<cond>) { <block> }
  BLOCK               →  brace-enclosed sequence; final expression
                          becomes a `return <expr>;`
  requires            →  Javadoc @param tag (informational)
  ensures             →  Javadoc @return tag (informational)
  @verify(lean, ...)  →  Javadoc @forge.verify line

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 4 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> java.lang.Math method name.
_BUILTIN_TO_JAVA: dict[NodeKind, str] = {
    NodeKind.EXP:   "Math.exp",
    NodeKind.LN:    "Math.log",
    NodeKind.SIN:   "Math.sin",
    NodeKind.COS:   "Math.cos",
    NodeKind.TAN:   "Math.tan",
    NodeKind.SQRT:  "Math.sqrt",
    NodeKind.ABS:   "Math.abs",
    NodeKind.ASIN:  "Math.asin",
    NodeKind.ACOS:  "Math.acos",
    NodeKind.ATAN:  "Math.atan",
    NodeKind.SINH:  "Math.sinh",
    NodeKind.COSH:  "Math.cosh",
    NodeKind.TANH:  "Math.tanh",
    NodeKind.POW:   "Math.pow",
}

_TYPE_TO_JAVA: dict[str, str] = {
    "Real": "double",
    "f64":  "double",
    "f32":  "float",
    "f16":  "float",   # No native f16; promote
    "bf16": "float",
    "u8":   "byte",
    "u16":  "short",
    "u32":  "int",
    "u64":  "long",
    "i8":   "byte",
    "i16":  "short",
    "i32":  "int",
    "i64":  "long",
    "bool": "boolean",
}


def _java_type(eml_type: str) -> str:
    return _TYPE_TO_JAVA.get(eml_type, "double")


def _class_name(mod: EMLModule) -> str:
    """Java class names use UpperCamelCase. Convert from snake_case."""
    base = mod.name or "ForgeModule"
    parts = base.split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts) or "ForgeModule"


class CompileError(Exception):
    """Raised on a NodeKind the Java backend doesn't recognize."""


class JavaBackend:
    """Compile an EMLModule to a single .java source file."""

    name = "java"

    def __init__(self, indent: str = "    ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        cls = _class_name(mod)
        lines: list[str] = [
            f"// Generated by EML-lang Java backend",
            f"// Source module: {mod.name or '(unnamed)'}",
            f"// Source file:   {mod.source_file}",
            f"// Functions:     {len(mod.functions)}",
            f"// Constants:     {len(mod.constants)}",
            "",
            f"public final class {cls} {{",
            "",
            f"{self.indent}private {cls}() {{}}  // utility class -- no instances",
            "",
        ]

        for c in mod.constants:
            lines.extend(self.indent + ln for ln in self._emit_constant(c))
        if mod.constants:
            lines.append("")

        # Tuple-returning functions get a generated nested record class.
        # Field names mirror the C backend: e0, e1, e2, ... (positional,
        # since the IR carries types but no field names).
        for fn in mod.functions:
            if fn.return_tuple_types:
                rec = self._tuple_record_name(fn.name)
                fields = ", ".join(
                    f"{_java_type(t)} e{i}"
                    for i, t in enumerate(fn.return_tuple_types)
                )
                lines.append(f"{self.indent}public record {rec}({fields}) {{}}")
        if any(fn.return_tuple_types for fn in mod.functions):
            lines.append("")

        for fn in mod.functions:
            if fn.is_extern:
                lines.extend(self.indent + ln for ln in self._emit_extern(fn))
            else:
                lines.extend(self.indent + ln for ln in self._emit_function(fn))
            lines.append("")

        lines.append("}")
        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _tuple_record_name(fn_name: str) -> str:
        # Mirror the C `{fn_name}_result_t` convention but in Java
        # naming style: PascalCase ending in `Result`.
        parts = fn_name.split("_")
        camel = "".join(p[:1].upper() + p[1:] for p in parts) or "Anon"
        return f"{camel}Result"

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        java_type = _java_type(c.type_name)
        rhs = self._emit_expr(c.value)
        return [f"public static final {java_type} {c.name} = {rhs};"]

    # ── Extern (FFI) ──────────────────────────────────────────

    def _emit_extern(self, fn: EMLFunction) -> list[str]:
        if fn.return_tuple_types:
            ret = self._tuple_record_name(fn.name)
        else:
            ret = _java_type(fn.return_type or "Real")
        params = ", ".join(
            f"{_java_type(p.type_name)} {p.name}" for p in fn.params
        )
        return [
            f"// extern: {fn.name} -- supply via JNI / interface impl",
            f"public static {ret} {fn.name}({params}) {{",
            f"{self.indent}throw new UnsupportedOperationException("
            f"\"{fn.name}: extern not bound\");",
            f"}}",
        ]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._javadoc(fn)
        if fn.return_tuple_types:
            ret = self._tuple_record_name(fn.name)
        else:
            ret = _java_type(fn.return_type or "Real")
        params = ", ".join(
            f"{_java_type(p.type_name)} {p.name}" for p in fn.params
        )
        out.append(f"public static {ret} {fn.name}({params}) {{")
        # Tell _emit_block which record-class constructor to wrap the
        # final TUPLE expression in (None for scalar-return functions).
        record = (
            self._tuple_record_name(fn.name) if fn.return_tuple_types else None
        )
        body = self._emit_block(fn.body, return_value=True, tuple_record=record)
        for ln in body:
            out.append(self.indent + ln)
        out.append("}")
        return out

    # ── Javadoc ───────────────────────────────────────────────

    def _javadoc(self, fn: EMLFunction) -> list[str]:
        out: list[str] = ["/**"]
        out.append(f" * {fn.name}")

        if fn.profile is not None:
            p = fn.profile
            if p.get("status") != "complex_body":
                cc = p.get("cost_class", "?")
                co = p.get("chain_order", "?")
                drift = p.get("fp16_drift_risk", "?")
                out.append(
                    f" * <p>Pfaffian profile: chain_order={co}, "
                    f"cost_class={cc}, drift_risk={drift}.</p>"
                )

        out.append(" *")
        for p in fn.params:
            out.append(f" * @param {p.name} (type {p.type_name})")
        out.append(f" * @return {fn.return_type or 'Real'}")

        for r in fn.requires:
            try:
                out.append(f" * @forge.requires {self._emit_expr(r)}")
            except CompileError:
                pass
        for r in fn.ensures:
            try:
                out.append(
                    f" * @forge.ensures {self._emit_expr(r, result_subst='result')}"
                )
            except CompileError:
                pass
        for a in fn.annotations:
            if a.kind == "verify":
                tname = a.args.get("theorem", fn.name)
                out.append(f" * @forge.verify lean theorem={tname}")
        out.append(" */")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
        tuple_record: str | None = None,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["// empty body"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind == NodeKind.LET:
                java_type = _java_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"final {java_type} {stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.LET_MUT:
                java_type = _java_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{java_type} {stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(
                    stmt.children[1], return_value=False, tuple_record=None,
                )
                out.append(f"while ({cond}) {{")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("}")
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(f"{self._emit_expr(stmt.children[0])};")
            elif (
                is_last and return_value
                and stmt.kind == NodeKind.TUPLE
                and tuple_record is not None
            ):
                # Tuple-return: wrap the final TUPLE in `new
                # RecordName(elem0, elem1, ...)`.
                elems = ", ".join(self._emit_expr(c) for c in stmt.children)
                out.append(f"return new {tuple_record}({elems});")
            elif is_last and return_value:
                out.append(f"return {self._emit_expr(stmt)};")
            else:
                out.append(f"{self._emit_expr(stmt)};")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            return f"({left} {node.value} {right})"

        if kind == NodeKind.TUPLE:
            # Java has no first-class tuples; emit as a comma list.
            # Forge tuple-return functions should ideally use a
            # generated record class; left for a follow-up.
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            raise CompileError(
                f"Java backend: tuple return needs a generated record "
                f"class (not yet implemented; got {elems})"
            )

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"Math.max({lo}, Math.min({hi}, {x}))"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"(Math.exp({x}) - Math.log({y}))"

        if kind in _BUILTIN_TO_JAVA:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{_BUILTIN_TO_JAVA[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{node.value}({args})"

        raise CompileError(
            f"Java backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
