"""Kotlin backend.

Emits a single ``.kt`` file. Functions become top-level (file-scope)
``fun`` declarations; module constants become top-level ``const val``
or ``val`` properties; math routines route through ``kotlin.math``.

Functions whose body is a single expression land as Kotlin
*expression bodies* (``fun f(...) = expr``), which is the
idiomatic form. Bodies that need ``let``-bindings use the standard
block form with ``return``.

Mapping
=======

  EML AST kind        →  Kotlin output
  ─────────────────────────────────────
  LITERAL int         →  "42"
  LITERAL float       →  "42.0"
  LITERAL bool        →  "true" / "false"
  VAR                 →  identifier
  BINOP comparisons   →  Kotlin comparison (yields Boolean)
  BINOP &&/||         →  Kotlin && / ||
  EXP/LN/SIN/COS/...  →  exp/ln/sin/cos/...   (kotlin.math wildcard)
  ABS(x)              →  abs(x)
  CLAMP(x, lo, hi)    →  x.coerceIn(lo, hi)
  POW(x, y)           →  x.pow(y)
  EML(x, y)           →  (exp(x) - ln(y))
  LET name = expr     →  "val name = <expr>"
  LET_MUT name = expr →  "var name = <expr>"
  ASSIGN name = expr  →  "name = <expr>"
  WHILE cond block    →  while (cond) { ... }
  BLOCK               →  brace block; final expression returned
  requires            →  KDoc + `require(...)` precondition
  ensures             →  KDoc only (Kotlin's `check` would assert
                          mid-fn; we don't auto-emit that to keep
                          the contract advisory)
  @verify(lean, ...)  →  KDoc @forge.verify line

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 4 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> kotlin.math function. After
# `import kotlin.math.*` these are all in scope.
_BUILTIN_TO_KOTLIN: dict[NodeKind, str] = {
    NodeKind.EXP:   "exp",
    NodeKind.LN:    "ln",
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.SQRT:  "sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "asin",
    NodeKind.ACOS:  "acos",
    NodeKind.ATAN:  "atan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
}


_TYPE_TO_KOTLIN: dict[str, str] = {
    "Real": "Double",
    "f64":  "Double",
    "f32":  "Float",
    "f16":  "Float",
    "bf16": "Float",
    "u8":   "Byte",
    "u16":  "Short",
    "u32":  "Int",
    "u64":  "Long",
    "i8":   "Byte",
    "i16":  "Short",
    "i32":  "Int",
    "i64":  "Long",
    "bool": "Boolean",
}


def _kotlin_type(eml_type: str) -> str:
    return _TYPE_TO_KOTLIN.get(eml_type, "Double")


def _package_name(mod: EMLModule) -> str:
    """Kotlin package names follow Java reverse-DNS convention.
    For Forge output we use `forge.<module>` -- a flat namespace
    that matches our C++ namespace pattern."""
    return f"forge.{mod.name or 'anon'}"


class CompileError(Exception):
    """Raised on a NodeKind the Kotlin backend doesn't recognize."""


class KotlinBackend:
    """Compile an EMLModule to a single .kt source file."""

    name = "kotlin"

    def __init__(self, indent: str = "    ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        lines: list[str] = [
            f"// Generated by EML-lang Kotlin backend",
            f"// Source module: {mod.name or '(unnamed)'}",
            f"// Source file:   {mod.source_file}",
            f"// Functions:     {len(mod.functions)}",
            f"// Constants:     {len(mod.constants)}",
            "",
            f"package {_package_name(mod)}",
            "",
            "import kotlin.math.*",
            "",
        ]

        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        # Tuple-returning functions get an idiomatic Kotlin data class.
        # Field names mirror the C / Java convention: e0, e1, e2, ...
        for fn in mod.functions:
            if fn.return_tuple_types:
                rec = self._tuple_data_class_name(fn.name)
                fields = ", ".join(
                    f"val e{i}: {_kotlin_type(t)}"
                    for i, t in enumerate(fn.return_tuple_types)
                )
                lines.append(f"data class {rec}({fields})")
        if any(fn.return_tuple_types for fn in mod.functions):
            lines.append("")

        for fn in mod.functions:
            if fn.is_extern:
                lines.extend(self._emit_extern(fn))
            else:
                lines.extend(self._emit_function(fn))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _tuple_data_class_name(fn_name: str) -> str:
        # PascalCase + `Result` suffix, matching the Java backend.
        parts = fn_name.split("_")
        camel = "".join(p[:1].upper() + p[1:] for p in parts) or "Anon"
        return f"{camel}Result"

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        kt_type = _kotlin_type(c.type_name)
        rhs = self._emit_expr(c.value)
        # `const val` requires a compile-time constant of a primitive
        # or String type. Arithmetic expressions like `(-0.349)` are
        # not const expressions in Kotlin, so we use plain `val`.
        # (`const val` would be nicer for true literals but the
        # parser folds `-0.349` into a unary-minus AST.)
        return [f"val {c.name}: {kt_type} = {rhs}"]

    # ── Extern (FFI) ──────────────────────────────────────────

    def _emit_extern(self, fn: EMLFunction) -> list[str]:
        if fn.return_tuple_types:
            ret = self._tuple_data_class_name(fn.name)
        else:
            ret = _kotlin_type(fn.return_type or "Real")
        params = ", ".join(
            f"{p.name}: {_kotlin_type(p.type_name)}" for p in fn.params
        )
        return [
            f"// extern: {fn.name} -- supply via JNI / external impl",
            f"external fun {fn.name}({params}): {ret}",
        ]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._kdoc(fn)
        if fn.return_tuple_types:
            ret = self._tuple_data_class_name(fn.name)
        else:
            ret = _kotlin_type(fn.return_type or "Real")
        params = ", ".join(
            f"{p.name}: {_kotlin_type(p.type_name)}" for p in fn.params
        )

        # Try expression-body form first -- the idiomatic Kotlin
        # shape for pure expression functions. Emit `require(...)`
        # preconditions inside a block when contracts are present
        # (we can't put them in an expression body).
        is_pure_expr = self._is_pure_expression_body(fn.body)
        has_requires = bool(fn.requires)

        if is_pure_expr and not has_requires and not fn.return_tuple_types:
            try:
                expr = self._emit_expr(self._final_expression(fn.body))
                out.append(f"fun {fn.name}({params}): {ret} = {expr}")
                return out
            except CompileError:
                pass  # Fall through to block form.

        out.append(f"fun {fn.name}({params}): {ret} {{")
        # Preconditions via Kotlin's `require()` (throws
        # IllegalArgumentException). The contract advisory matches
        # the Ada SPARK Pre / C++ Doxygen @pre intent.
        for r in fn.requires:
            try:
                cond = self._emit_expr(r)
                out.append(f"{self.indent}require({cond}) "
                           f'{{ "{fn.name}: requires {cond}" }}')
            except CompileError as e:
                out.append(f"{self.indent}// require: unsupported ({e})")

        record = (
            self._tuple_data_class_name(fn.name)
            if fn.return_tuple_types else None
        )
        body = self._emit_block(
            fn.body, return_value=True, tuple_record=record,
        )
        for ln in body:
            out.append(self.indent + ln)
        out.append("}")
        return out

    @staticmethod
    def _is_pure_expression_body(body: ASTNode | None) -> bool:
        if body is None or body.kind != NodeKind.BLOCK:
            return False
        return (
            len(body.children) == 1
            and body.children[0].kind not in (
                NodeKind.LET, NodeKind.LET_MUT,
                NodeKind.ASSIGN, NodeKind.WHILE,
                NodeKind.EXPR_STMT,
            )
        )

    @staticmethod
    def _final_expression(body: ASTNode) -> ASTNode:
        return body.children[-1]

    # ── KDoc ──────────────────────────────────────────────────

    def _kdoc(self, fn: EMLFunction) -> list[str]:
        out: list[str] = ["/**"]
        out.append(f" * {fn.name}")
        if fn.profile is not None and fn.profile.get("status") != "complex_body":
            cc = fn.profile.get("cost_class", "?")
            co = fn.profile.get("chain_order", "?")
            drift = fn.profile.get("fp16_drift_risk", "?")
            out.append(f" *")
            out.append(
                f" * Pfaffian profile: chain_order={co}, "
                f"cost_class={cc}, drift_risk={drift}."
            )
        for r in fn.requires:
            try:
                out.append(f" * @forge.requires {self._emit_expr(r)}")
            except CompileError:
                pass
        for r in fn.ensures:
            try:
                out.append(
                    f" * @forge.ensures {self._emit_expr(r, result_subst='result')}"
                )
            except CompileError:
                pass
        for a in fn.annotations:
            if a.kind == "verify":
                tname = a.args.get("theorem", fn.name)
                out.append(f" * @forge.verify lean theorem={tname}")
        out.append(" */")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
        tuple_record: str | None = None,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["// empty body"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind == NodeKind.LET:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"val {stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.LET_MUT:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"var {stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(
                    stmt.children[1], return_value=False, tuple_record=None,
                )
                out.append(f"while ({cond}) {{")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("}")
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(f"{self._emit_expr(stmt.children[0])}")
            elif (
                is_last and return_value
                and stmt.kind == NodeKind.TUPLE
                and tuple_record is not None
            ):
                # Tuple-return: wrap the final TUPLE in the data
                # class constructor `RecordName(elem0, elem1, ...)`.
                elems = ", ".join(self._emit_expr(c) for c in stmt.children)
                out.append(f"return {tuple_record}({elems})")
            elif is_last and return_value:
                out.append(f"return {self._emit_expr(stmt)}")
            else:
                out.append(f"{self._emit_expr(stmt)}")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            return f"({left} {node.value} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            # Kotlin's Pair / Triple cover up to three elements; for
            # arbitrary arity we'd need data classes. Forge tuple-
            # return functions are typically pairs, so use Pair.
            if len(node.children) == 2:
                return f"Pair({elems})"
            if len(node.children) == 3:
                return f"Triple({elems})"
            raise CompileError(
                f"Kotlin backend: arity-{len(node.children)} tuple needs a "
                f"generated data class (got {elems})"
            )

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({x}).coerceIn({lo}, {hi})"

        if kind == NodeKind.POW:
            base, exp_node = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({base}).pow({exp_node})"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"(exp({x}) - ln({y}))"

        if kind in _BUILTIN_TO_KOTLIN:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{_BUILTIN_TO_KOTLIN[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{node.value}({args})"

        raise CompileError(
            f"Kotlin backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
