"""LLVM IR backend -- portable target via the LLVM ecosystem.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.3.
SCAFFOLD.
"""

from __future__ import annotations

from lang.parser.ast_nodes import EMLFunction


class LLVMBackend:
    """Compile an EMLFunction list to LLVM IR text."""

    name = "llvm"

    def compile(self, program: list[EMLFunction]) -> str:
        return (
            "; LLVM IR generated by EML-lang compiler\n"
            "; SCAFFOLD -- backend body lands in Phase 2.3\n"
        )
