"""MATLAB / Simulink-compatible .m backend.

Emits a single MATLAB ``.m`` file -- one function per EML
function plus a top-level main function with the same name as
the source module. Suitable for opening in Simulink as a MATLAB
Function block, for unit testing in MATLAB, and for the
hand-translation-elimination workflow described in the Phase 2
backend roadmap.

Mapping
=======

  EML AST kind        →  MATLAB output
  ─────────────────────────────────────
  LITERAL int         →  "42"
  LITERAL float       →  "42.0"
  LITERAL bool        →  "true" / "false"
  VAR                 →  identifier (snake_case preserved)
  BINOP +/-/*//       →  MATLAB arithmetic
  BINOP comparisons   →  MATLAB comparison (yields logical)
  BINOP &&/||         →  MATLAB short-circuit && / ||
  UNARYOP -           →  unary minus
  UNARYOP !           →  ~
  EXP/LN/SIN/COS/...  →  exp/log/sin/cos/...
  ABS(x)              →  abs(x)
  CLAMP(x, lo, hi)    →  min(hi, max(lo, x))   (no native clamp)
  POW(x, y)           →  x.^y
  EML(x, y)           →  exp(x) - log(y)
  CALL                →  user-function call
  LET name = expr     →  "name = <expr>;"
  LET_MUT name = expr →  "name = <expr>;"   (no const distinction)
  ASSIGN name = expr  →  "name = <expr>;"
  WHILE cond block    →  while cond ... end
  BLOCK               →  semicolon-separated statements; final
                          expression assigned to the function
                          output variable
  requires            →  assert(<expr>);  at function entry
  ensures             →  assert(<expr>);  before return
  @verify(lean, ...)  →  comment-only cross-link to the Lean theorem

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 2 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> MATLAB function name. MATLAB's elementary
# math functions live in the global namespace.
_BUILTIN_TO_MATLAB: dict[NodeKind, str] = {
    NodeKind.EXP:   "exp",
    NodeKind.LN:    "log",
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.SQRT:  "sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "asin",
    NodeKind.ACOS:  "acos",
    NodeKind.ATAN:  "atan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
}


# MATLAB has no compound BINOP for `==` -- it uses `==` for
# elementwise equality and `&&` / `||` for short-circuit. The
# default mapping keeps these symbols as-is; only `!=` and the
# logical NOT need rewriting.
_BINOP_REWRITE: dict[str, str] = {
    "!=": "~=",
}


class CompileError(Exception):
    """Raised on a NodeKind the MATLAB backend doesn't recognize."""


class MatlabBackend:
    """Compile an EMLModule to a single MATLAB .m source file."""

    name = "matlab"

    def __init__(self, indent: str = "    ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize
        # Populated per compile() call; lets _emit_expr inline
        # module-level constant values at use-sites since MATLAB
        # has no clean module-scope const facility.
        self._consts: dict[str, str] = {}

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        # MATLAB requires the file's first function to share its
        # name with the file itself. We use the EML module name
        # (snake_case is fine -- MATLAB accepts it). When the
        # module has no name we fall back to "forge_module".
        primary = mod.name or "forge_module"

        # Build the constant-inlining table BEFORE emitting any
        # function body. MATLAB has no clean module-scope const,
        # so we substitute literal values at every VAR reference
        # whose name matches a module-level constant.
        self._consts = {
            c.name: self._emit_expr(c.value) for c in mod.constants
        }

        lines: list[str] = [
            f"% Generated by EML-lang MATLAB backend",
            f"% Source module: {mod.name or '(unnamed)'}",
            f"% Source file:   {mod.source_file}",
            f"% Functions:     {len(mod.functions)}",
            f"% Constants:     {len(mod.constants)} (inlined at use-sites)",
            "",
        ]

        if mod.constants:
            lines.append("% ── Constants (inlined into function bodies) ─────────")
            for c in mod.constants:
                lines.append(f"%   {c.name} = {self._consts[c.name]}")
            lines.append("")

        # Functions: emit each as a MATLAB local function. The first
        # one defines the file (its name = primary). If none of the
        # EML functions matches the module name, prepend a thin
        # wrapper that just calls the last @target/@verify function
        # so the file remains valid MATLAB.
        if mod.functions:
            primary_fn = next(
                (f for f in mod.functions if f.name == primary), None,
            )
            if primary_fn is None:
                # Synthesize a wrapper around the last function so
                # the file's primary function matches the filename.
                last = mod.functions[-1]
                wrapper = self._synth_primary_wrapper(primary, last)
                lines.extend(wrapper)
                lines.append("")

            for fn in mod.functions:
                if fn.is_extern:
                    lines.extend(self._emit_extern(fn))
                else:
                    lines.extend(self._emit_function(fn))
                lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    # ── Extern (FFI) ──────────────────────────────────────────

    def _emit_extern(self, fn: EMLFunction) -> list[str]:
        # MATLAB has no FFI declaration syntax that translates to
        # the AST; emit a stub so the file remains valid.
        params = ", ".join(p.name for p in fn.params)
        return [
            f"function r = {fn.name}({params})",
            f"{self.indent}% extern: replace this stub with your "
            f"MATLAB / Simulink implementation.",
            f"{self.indent}r = 0.0;",
            f"end",
        ]

    # ── Synth primary wrapper ─────────────────────────────────

    def _synth_primary_wrapper(
        self, primary: str, last_fn: EMLFunction,
    ) -> list[str]:
        params = ", ".join(p.name for p in last_fn.params)
        return [
            f"function r = {primary}({params})",
            f"{self.indent}% Primary entry point -- delegates to {last_fn.name}.",
            f"{self.indent}% MATLAB requires the file's first function to share",
            f"{self.indent}% the file name; the actual implementation is below.",
            f"{self.indent}r = {last_fn.name}({params});",
            f"end",
        ]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        out: list[str] = self._profile_comment(fn)
        params = ", ".join(p.name for p in fn.params)
        # Single return variable named `r` for simplicity. MATLAB
        # tuple returns use `[a, b] = f(...)` syntax which we'll
        # add when an EML function has return_tuple_types.
        if fn.return_tuple_types:
            ret_vars = ", ".join(f"r{i}" for i in range(len(fn.return_tuple_types)))
            head = f"function [{ret_vars}] = {fn.name}({params})"
        else:
            head = f"function r = {fn.name}({params})"
        out.append(head)

        # @verify cross-link as comment.
        for a in fn.annotations:
            if a.kind == "verify":
                tname = a.args.get("theorem", fn.name)
                out.append(self.indent + f"% @verify(lean, theorem = \"{tname}\")")

        # requires → assert at entry.
        for r in fn.requires:
            try:
                expr = self._emit_expr(r)
                out.append(self.indent + f"assert({expr}, '{fn.name}: requires violated');")
            except CompileError as e:
                out.append(self.indent + f"% requires: unsupported ({e})")

        body = self._emit_block(fn.body, return_value=True,
                                 ensures=fn.ensures, fn=fn)
        for ln in body:
            out.append(self.indent + ln)
        out.append("end")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
        ensures: list[ASTNode] | None = None,
        fn: EMLFunction | None = None,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["% empty block"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind in (NodeKind.LET, NodeKind.LET_MUT):
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"while {cond}")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("end")
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(f"{self._emit_expr(stmt.children[0])};")
            elif is_last and return_value:
                expr = self._emit_expr(stmt)
                out.append(f"r = {expr};")
                # ensures fire after the assignment so `r` is in
                # scope for the assertion.
                if ensures and fn is not None:
                    for e in ensures:
                        try:
                            ens = self._emit_expr(e, result_subst="r")
                            out.append(
                                f"assert({ens}, "
                                f"'{fn.name}: ensures violated');"
                            )
                        except CompileError as ce:
                            out.append(f"% ensures: unsupported ({ce})")
            else:
                out.append(f"{self._emit_expr(stmt)};")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            # Module-level constant? Inline its value directly so
            # the body doesn't reference an unbound MATLAB name.
            if name in self._consts:
                return self._consts[name]
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(~{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            op = _BINOP_REWRITE.get(node.value, node.value)
            return f"({left} {op} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            return f"[{elems}]"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            # MATLAB has no native clamp -- emit min/max nest.
            return f"min({hi}, max({lo}, {x}))"

        if kind == NodeKind.POW:
            base, exp = (
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            # `.^` is element-wise; safe for scalars too.
            return f"({base}).^({exp})"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            return f"(exp({x}) - log({y}))"

        if kind in _BUILTIN_TO_MATLAB:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            return f"{_BUILTIN_TO_MATLAB[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(
                self._emit_expr(c, result_subst=result_subst) for c in node.children
            )
            return f"{node.value}({args})"

        raise CompileError(
            f"MATLAB backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )

    # ── Profile comment ───────────────────────────────────────

    def _profile_comment(self, fn: EMLFunction) -> list[str]:
        if fn.profile is None:
            return [f"% {fn.name}: profile unavailable"]
        p = fn.profile
        if p.get("status") == "complex_body":
            return [
                f"% {fn.name} -- COMPLEX BODY",
                f"% note: {p.get('note', '')}",
            ]
        cc = p.get("cost_class", "?")
        co = p.get("chain_order", "?")
        depth = p.get("eml_depth", "?")
        drift = p.get("fp16_drift_risk", "?")
        return [
            f"% {fn.name}",
            f"% Chain order: {co}    Cost class: {cc}",
            f"% EML depth:   {depth}    Drift risk: {drift}",
        ]
