"""Python / NumPy backend -- reuses the eml-cost Tool 5 transpiler
(`eml_cost.transpile.eml_tree_to_python`) so we don't duplicate
that work here.

Reference: lang/spec/EML_LANG_DESIGN.md (Phase 2 cross-cutting).
SCAFFOLD: wires the AST -> SymPy -> Tool 5 path; full integration
in Phase 2.
"""

from __future__ import annotations

from lang.parser.ast_nodes import EMLFunction


class PythonBackend:
    """Compile an EMLFunction list to Python source via Tool 5."""

    name = "python"

    def compile(self, program: list[EMLFunction]) -> str:
        return (
            "# Python source generated by EML-lang compiler\n"
            "# SCAFFOLD -- delegates to eml_cost.transpile.eml_tree_to_python\n"
            "# in the full Phase 2 implementation.\n"
        )
