"""Python / NumPy backend.

Produces a self-contained Python module from an `EMLModule`. Each
function's body is converted to a SymPy expression by the profiler
bridge (`lang/profiler/ast_to_sympy.py`), then handed to the
eml-cost Tool 5 transpiler (`eml_cost.transpile.eml_tree_to_python`)
which emits idiomatic `math.*` source.

Functions whose body lies outside the SymPy-arithmetic subset
(mut + while loops, branching, tuple destructure) fall back to a
direct AST -> Python emitter so we still produce runnable source.

Phase E.3: refinement-aware lowering.
  - `requires` clauses lower to `if not (cond): raise ValueError("msg")`.
  - Refined parameters lower to the same pattern, BEFORE requires guards.
  - ABS maps to the bare `abs()` built-in (no prefix), consistent with the
    existing _BUILTIN_TO_PY mapping.
  - Guards are injected at the START of every function body (after the def
    line), before the SymPy-transpiled or direct body.

Reference: lang/spec/EML_LANG_DESIGN.md (Phase 2 cross-cutting).
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)
from lang.profiler.ast_to_sympy import convert_function_body
from tools.equivalence.python_runner import constants_from_module


# Built-in NodeKind -> Python `math` function. Used by the fallback
# emitter that walks the AST directly when the SymPy bridge can't
# represent the function (mut / while / tuple destructure).
_BUILTIN_TO_PY: dict[NodeKind, str] = {
    NodeKind.EXP:   "math.exp",
    NodeKind.LN:    "math.log",
    NodeKind.SIN:   "math.sin",
    NodeKind.COS:   "math.cos",
    NodeKind.TAN:   "math.tan",
    NodeKind.SQRT:  "math.sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "math.asin",
    NodeKind.ACOS:  "math.acos",
    NodeKind.ATAN:  "math.atan",
    NodeKind.SINH:  "math.sinh",
    NodeKind.COSH:  "math.cosh",
    NodeKind.TANH:  "math.tanh",
    NodeKind.POW:   "math.pow",
}


# ── Phase E.3: refinement-guard helpers (module-level, by convention)─

def _substitute_var(node: ASTNode, old: str, new: str) -> ASTNode:
    """Return a new ASTNode tree with every VAR named `old` replaced by `new`."""
    if node.kind == NodeKind.VAR and node.value == old:
        return ASTNode(
            kind=node.kind, value=new, children=[],
            type_annotation=node.type_annotation,
            chain_constraint=node.chain_constraint,
            line=node.line, col=node.col,
        )
    new_children = [_substitute_var(c, old, new) for c in node.children]
    return ASTNode(
        kind=node.kind, value=node.value, children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line, col=node.col,
    )


def _var_names(node: ASTNode) -> set[str]:
    """Collect every VAR name that appears anywhere in `node`."""
    names: set[str] = set()
    if node.kind == NodeKind.VAR:
        names.add(node.value)
    for c in node.children:
        names.update(_var_names(c))
    return names


class CompileError(Exception):
    """Raised when the Python backend genuinely can't translate a node."""


class PythonBackend:
    """Compile an EMLModule to Python 3 source.

    Generated source has no third-party deps -- only `math` from the
    stdlib. `optimize=True` (default) runs the EML optimizer pipeline
    (inline / CSE / SuperBEST / shake-imports) before emit.
    """

    name = "python"

    def __init__(self, indent: str = "    ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)

        consts = constants_from_module(mod)

        # Normalize backslashes so the embedded path doesn't trigger
        # SyntaxWarning ("\s" etc.) when the generated module is loaded.
        src_file = str(mod.source_file).replace("\\", "/")
        lines: list[str] = [
            '"""',
            f"Generated by EML-lang Python backend.",
            f"Source module: {mod.name or '(unnamed)'}",
            f"Source file:   {src_file}",
            f"Functions:     {len(mod.functions)}",
            f"Constants:     {len(mod.constants)}",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "import math",
            "",
        ]

        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        for fn in mod.functions:
            lines.extend(self._emit_function(fn, consts))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        return [f"{c.name} = {self._emit_expr(c.value)}"]

    # ── Function emit ─────────────────────────────────────────

    def _emit_function(
        self,
        fn: EMLFunction,
        consts: dict[str, float | int | bool],
    ) -> list[str]:
        out: list[str] = self._profile_comment(fn)

        params = ", ".join(p.name for p in fn.params)
        out.append(f"def {fn.name}({params}):")

        # Phase E.3: refinement guards fire BEFORE requires guards.
        # Refinements correspond to parameter types; requires clauses
        # are user-specified cross-cutting contracts.
        guard_lines = self._emit_refinement_guards(fn)
        for ln in guard_lines:
            out.append(self.indent + ln)

        # `requires` clauses lower to runtime ValueError raises
        # (always-on; Python has no debug-vs-release distinction).
        for r in fn.requires:
            try:
                cond = self._emit_expr(r)
                msg = f"{fn.name}: requires ({cond})"
                out.append(
                    f"{self.indent}if not ({cond}): raise ValueError({msg!r})"
                )
            except CompileError as e:
                out.append(f"{self.indent}# requires: unsupported ({e})")

        # Phase G: `assume` clauses -- trusted hypotheses, zero runtime cost.
        for a in fn.assumes:
            try:
                out.append(f"{self.indent}# assume: {self._emit_expr(a)}")
            except CompileError as e:
                out.append(f"{self.indent}# assume: unsupported ({e})")

        # Try the SymPy bridge first -- gives us optimal idiomatic
        # math.* source via Tool 5. Falls back to direct AST emit
        # for complex_body (mut / while / branching) functions.
        body = self._emit_body_via_sympy(fn, consts)
        if body is None:
            body = self._emit_body_direct(fn)

        for ln in body:
            out.append(self.indent + ln)
        return out

    # ── Phase E.3: refinement guards ─────────────────────────────

    def _emit_refinement_guards(self, fn: EMLFunction) -> list[str]:
        """Return one guard line per refined parameter.

        Cross-param refinements emit a comment-only obligation line
        (runtime check is intractable without value tracking).
        """
        out: list[str] = []
        param_names = {p.name for p in fn.params}
        for p in fn.params:
            if p.refinement is None:
                continue
            ref = p.refinement
            pred = _substitute_var(ref.predicate, ref.binder, p.name)
            pred_vars = _var_names(pred)
            other_params_in_pred = (pred_vars - {p.name}) & param_names
            if other_params_in_pred:
                try:
                    cond_str = self._emit_expr(pred)
                except CompileError as e:
                    cond_str = f"<unsupported: {e}>"
                out.append(
                    f"# refinement obligation: {fn.name}: {p.name}: {cond_str}"
                )
                continue
            try:
                cond = self._emit_expr(pred)
                msg = f"{fn.name}: refinement violated on {p.name}: {cond}"
                out.append(
                    f"if not ({cond}): raise ValueError({msg!r})"
                )
            except CompileError as e:
                out.append(f"# refinement: unsupported ({e})")
        return out

    def _emit_body_via_sympy(
        self,
        fn: EMLFunction,
        consts: dict[str, float | int | bool],
    ) -> list[str] | None:
        """Use eml_cost.transpile.eml_tree_to_python on the SymPy form."""
        from eml_cost.transpile import eml_tree_to_python

        cr = convert_function_body(fn, constants=consts)
        if cr.status not in ("ok", "tuple"):
            return None

        var_names = tuple(p.name for p in fn.params)

        try:
            if cr.status == "ok":
                tr = eml_tree_to_python(
                    cr.expression, function_name=fn.name, var_names=var_names,
                )
                # tr.code is `def f(x): return ...\n` -- strip the def line
                # and indent so we get just the body.
                return self._strip_def_line(tr.code)

            # tuple: emit a return tuple expression by transpiling each
            # component, then stitch.
            parts: list[str] = []
            for i, expr in enumerate(cr.expression):
                tr = eml_tree_to_python(
                    expr, function_name=f"{fn.name}_e{i}", var_names=var_names,
                )
                parts.append(self._strip_return_expr(tr.code))
            return [f"return ({', '.join(parts)})"]
        except Exception:
            # Tool 5's printer can't represent free SymPy `Function`
            # placeholders (i.e. user-function calls that didn't get
            # inlined). Drop to the direct AST emitter, which handles
            # NodeKind.CALL natively.
            return None

    @staticmethod
    def _strip_def_line(code: str) -> list[str]:
        """Drop the `def f(...):` header from Tool 5 output, return
        the body lines (de-indented by 4)."""
        lines = code.splitlines()
        body: list[str] = []
        for ln in lines[1:]:  # skip `def` line
            if ln.startswith("    "):
                body.append(ln[4:])
            elif ln.strip() == "":
                continue
            else:
                body.append(ln)
        return body or ["pass"]

    @staticmethod
    def _strip_return_expr(code: str) -> str:
        """From a Tool 5 `def f(x): return EXPR` block, return the
        bare EXPR string."""
        for ln in code.splitlines():
            s = ln.strip()
            if s.startswith("return "):
                return s[len("return "):]
        return "0.0"

    # ── Direct AST emit (fallback for mut / while bodies) ─────

    def _emit_body_direct(self, fn: EMLFunction) -> list[str]:
        if fn.body is None or fn.body.kind != NodeKind.BLOCK:
            return ["pass"]
        return self._emit_block(fn.body, return_value=True)

    def _emit_block(
        self,
        block: ASTNode,
        *,
        return_value: bool,
    ) -> list[str]:
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind in (NodeKind.LET, NodeKind.LET_MUT):
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs}")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"while {cond}:")
                for ln in inner:
                    out.append(self.indent + ln)
            elif stmt.kind == NodeKind.EXPR_STMT:
                out.append(self._emit_expr(stmt.children[0]))
            elif is_last:
                expr = self._emit_expr(stmt)
                out.append(f"return {expr}" if return_value else expr)
            else:
                out.append(self._emit_expr(stmt))
        return out or ["pass"]

    # ── Expression emit (used by direct fallback) ─────────────

    def _emit_expr(self, node: ASTNode) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "True" if v else "False"
            if isinstance(v, (int, float)):
                return repr(v)
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            return str(node.value)

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0])
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(not {sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0])
            right = self._emit_expr(node.children[1])
            op = node.value
            if op == "&&":
                op = "and"
            elif op == "||":
                op = "or"
            return f"({left} {op} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(self._emit_expr(c) for c in node.children)
            return f"({elems})"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (self._emit_expr(c) for c in node.children)
            return f"max({lo}, min({hi}, {x}))"

        if kind in _BUILTIN_TO_PY:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            return f"{_BUILTIN_TO_PY[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            return f"{node.value}({args})"

        raise CompileError(
            f"Python backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )

    # ── Profile comment ───────────────────────────────────────

    def _profile_comment(self, fn: EMLFunction) -> list[str]:
        if fn.profile is None:
            return [f"# {fn.name}: no profile available"]
        p = fn.profile
        if p.get("status") == "complex_body":
            return [
                f"# {fn.name} -- COMPLEX BODY",
                f"# note: {p.get('note', '')}",
            ]
        cc = p.get("cost_class", "?")
        co = p.get("chain_order", "?")
        depth = p.get("eml_depth", "?")
        return [
            f"# {fn.name}",
            f"# Chain order: {co}    Cost class: {cc}    EML depth: {depth}",
        ]
