"""Rust backend -- emits Rust source consuming the monogate-sys crate.

Mirrors the C backend's structure (NodeKind dispatch, profile
comment header, tuple struct generation) but emits Rust syntax:
`fn name(params) -> ret_type` blocks, `let mut`, `while`,
`monogate_sys::mg_*` calls.

Phase E.3: refinement-aware lowering.
  - `requires` clauses lower to `assert!(cond, "msg")` runtime guards.
  - Refined parameters lower to `assert!(pred, "msg")` guards before the
    requires guards.
  - `assert!` (always-on panicking macro) is used for both, matching the
    "safety precondition" semantics. `debug_assert!` would be stripped in
    release builds, which is inappropriate for domain-enforcing contracts.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.2.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# ── Phase E.3: refinement guard helpers ──────────────────────────────────────


def _substitute_var(node: ASTNode, old: str, new: str) -> ASTNode:
    """Return a new ASTNode tree with every VAR named *old* replaced by *new*.

    Immutable: the original tree is never modified.
    """
    if node.kind == NodeKind.VAR and node.value == old:
        return ASTNode(
            kind=NodeKind.VAR, value=new, children=[],
            type_annotation=node.type_annotation,
            chain_constraint=node.chain_constraint,
            line=node.line, col=node.col,
        )
    new_children = [_substitute_var(c, old, new) for c in node.children]
    return ASTNode(
        kind=node.kind, value=node.value, children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line, col=node.col,
    )


def _var_names(node: ASTNode) -> set[str]:
    """Collect every VAR name that appears anywhere in *node*."""
    names: set[str] = set()
    if node.kind == NodeKind.VAR:
        names.add(str(node.value))
    for c in node.children:
        names.update(_var_names(c))
    return names


# Builtin NodeKind -> monogate_sys function name (without crate prefix).
_BUILTIN_TO_RUST: dict[NodeKind, str] = {
    NodeKind.EXP:   "mg_exp",
    NodeKind.LN:    "mg_ln",
    NodeKind.SIN:   "mg_sin",
    NodeKind.COS:   "mg_cos",
    NodeKind.TAN:   "mg_tan",
    NodeKind.SQRT:  "mg_sqrt",
    NodeKind.ABS:   "mg_abs",
    NodeKind.ASIN:  "mg_asin",
    NodeKind.ACOS:  "mg_acos",
    NodeKind.ATAN:  "mg_atan",
    NodeKind.SINH:  "mg_sinh",
    NodeKind.COSH:  "mg_cosh",
    NodeKind.TANH:  "mg_tanh",
    NodeKind.POW:   "mg_pow",
    NodeKind.EML:   "mg_eml",
    NodeKind.CLAMP: "mg_clamp",
}


# EML-lang -> Rust type names. Aliases default to f64.
_TYPE_TO_RUST: dict[str, str] = {
    "Real": "f64",
    "f64":  "f64",
    "f32":  "f32",
    "f16":  "f32",   # Rust stable has no native f16; promote to f32
    "bf16": "f32",
    "u8":   "u8",
    "u16":  "u16",
    "u32":  "u32",
    "u64":  "u64",
    "i8":   "i8",
    "i16":  "i16",
    "i32":  "i32",
    "i64":  "i64",
    "bool": "bool",
}


def _rewrite_var_names(node: ASTNode, rename: dict[str, str]) -> None:
    """Walk `node` in place: every VAR or LET / LET_MUT / ASSIGN
    whose name is in `rename` is renamed to the mapped value."""
    if node.kind == NodeKind.VAR and node.value in rename:
        node.value = rename[node.value]
    if (
        node.kind in (NodeKind.LET, NodeKind.LET_MUT, NodeKind.ASSIGN)
        and node.value in rename
    ):
        node.value = rename[node.value]
    for c in node.children:
        _rewrite_var_names(c, rename)


def _rust_type(eml_type: str) -> str:
    return _TYPE_TO_RUST.get(eml_type, "f64")


class CompileError(Exception):
    """Raised on a NodeKind the Rust backend doesn't recognize."""


class RustBackend:
    """Compile an EMLModule to Rust source."""

    name = "rust"

    def __init__(self, indent: str = "    ", *, optimize: bool = True):
        self.indent = indent
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        # Rust treats a parameter name that matches a module-level
        # `const` as a constant pattern (refutable -- E0005), not a
        # fresh binding. Rename any colliding params before emit so
        # imported stdlib functions like `pid_integrate(... dt: f64)`
        # work in modules that define their own `const dt`.
        mod = self._rename_param_collisions(mod)
        lines: list[str] = [
            "// Generated by EML-lang Rust backend",
            f"// Source module: {mod.name or '(unnamed)'}",
            f"// Source file:   {mod.source_file}",
            f"// Functions:     {len(mod.functions)}",
            f"// Constants:     {len(mod.constants)}",
            "",
            "#![allow(non_snake_case)]",
            "#![allow(unused_imports)]",
            "use monogate_sys::*;",
            "",
        ]

        # Tuple-return structs.
        struct_lines = self._emit_tuple_structs(mod.functions)
        if struct_lines:
            lines.extend(struct_lines)
            lines.append("")

        # Module-level constants.
        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        # Functions.
        for fn in mod.functions:
            lines.extend(self._emit_function(fn))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    # ── Tuple structs ─────────────────────────────────────────

    def _emit_tuple_structs(self, funcs: list[EMLFunction]) -> list[str]:
        out: list[str] = []
        for fn in funcs:
            if not fn.return_tuple_types:
                continue
            type_name = self._tuple_type_name(fn.name)
            fields = ", ".join(
                f"pub e{i}: {_rust_type(t)}"
                for i, t in enumerate(fn.return_tuple_types)
            )
            out.append("#[derive(Clone, Copy, Debug)]")
            out.append(f"pub struct {type_name} {{ {fields} }}")
        return out

    @staticmethod
    def _tuple_type_name(fn_name: str) -> str:
        # CamelCase struct name from snake_case function name.
        parts = fn_name.split("_")
        return "".join(p[:1].upper() + p[1:] for p in parts) + "Result"

    # ── Constants + functions ─────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        return [
            f"pub const {c.name}: {_rust_type(c.type_name)} = "
            f"{self._emit_expr(c.value)};"
        ]

    def _rename_param_collisions(self, mod: EMLModule) -> EMLModule:
        """Return a deep copy of `mod` with every function-parameter
        name that collides with a module-level const renamed to
        `<name>_p`. Body VAR references to the same name are
        rewritten in tandem.

        Why: in Rust 2021, `pub fn f(dt: f64)` where `dt` is also a
        module-level const becomes a refutable const-pattern match
        (E0005) -- the param shadow doesn't apply at the binding
        position. Rather than ban the (legal in EML) shadowing,
        we rename in the emit AST."""
        from copy import deepcopy
        const_names = {c.name for c in mod.constants}
        if not const_names:
            return mod
        out = deepcopy(mod)
        for fn in out.functions:
            collisions = {
                p.name for p in fn.params if p.name in const_names
            }
            if not collisions:
                continue
            rename = {name: f"{name}_p" for name in collisions}
            for p in fn.params:
                if p.name in rename:
                    p.name = rename[p.name]
            if fn.body is not None:
                _rewrite_var_names(fn.body, rename)
        return out

    # ── Phase E.3: refinement guards ─────────────────────────────

    def _emit_refinement_guards(self, fn: EMLFunction) -> list[str]:
        """Return one assert!() line per refined parameter (Phase E.3).

        Binder-substitution: the refinement's binder is alpha-renamed to
        the actual parameter name before emission.

        Cross-param refinements (predicate references another parameter)
        are emitted as comment-only obligation lines.
        """
        out: list[str] = []
        param_names = {p.name for p in fn.params}
        for p in fn.params:
            if p.refinement is None:
                continue
            ref = p.refinement
            pred = _substitute_var(ref.predicate, ref.binder, p.name)
            pred_vars = _var_names(pred)
            other_params_in_pred = (pred_vars - {p.name}) & param_names
            if other_params_in_pred:
                try:
                    cond_str = self._emit_expr(pred)
                except CompileError as e:
                    cond_str = f"<unsupported: {e}>"
                out.append(
                    f"{self.indent}// refinement obligation: "
                    f"{fn.name}: {p.name}: {cond_str}"
                )
                continue
            try:
                cond = self._emit_expr(pred)
                msg = f"{fn.name}: refinement violated on {p.name}: {cond}"
                out.append(
                    f'{self.indent}assert!({cond}, "{msg}");'
                )
            except CompileError as e:
                out.append(
                    f"{self.indent}// refinement: unsupported ({e})"
                )
        return out

    def _emit_function(self, fn: EMLFunction) -> list[str]:
        # Extern fns are FFI declarations -- the implementation is
        # provided by another crate or linked .a/.so/.dll.
        if fn.is_extern:
            if fn.return_tuple_types:
                ret_type = self._tuple_type_name(fn.name)
            else:
                ret_type = _rust_type(fn.return_type or "Real")
            params_rust = ", ".join(
                f"{p.name}: {_rust_type(p.type_name)}" for p in fn.params
            )
            return [
                f"// extern: {fn.name} -- FFI declaration only",
                f'extern "C" {{ pub fn {fn.name}({params_rust}) -> {ret_type}; }}',
            ]

        out: list[str] = self._profile_comment(fn)

        if fn.return_tuple_types:
            ret_type = self._tuple_type_name(fn.name)
        else:
            ret_type = _rust_type(fn.return_type or "Real")
        params_rust = ", ".join(
            f"{p.name}: {_rust_type(p.type_name)}" for p in fn.params
        )
        out.append(f"pub fn {fn.name}({params_rust}) -> {ret_type} {{")

        # Phase E.3: refinement-derived guards fire BEFORE requires guards.
        # Refinements correspond to parameter types; requires clauses are
        # user-specified cross-cutting contracts.
        out.extend(self._emit_refinement_guards(fn))

        # `requires` lower to assert!() guards (always-on panicking macro).
        for r in fn.requires:
            try:
                cond = self._emit_expr(r)
                out.append(
                    f'{self.indent}assert!({cond}, "{fn.name}: requires ({cond})");'
                )
            except CompileError as e:
                out.append(f"{self.indent}// requires: unsupported ({e})")

        struct_name = (
            self._tuple_type_name(fn.name) if fn.return_tuple_types else None
        )
        body_lines = self._emit_block(
            fn.body, return_value=True, tuple_struct=struct_name,
        )
        for ln in body_lines:
            out.append(self.indent + ln)
        out.append("}")
        return out

    def _profile_comment(self, fn: EMLFunction) -> list[str]:
        if fn.profile is None:
            return [f"// {fn.name}: profile unavailable"]
        p = fn.profile
        if p.get("status") == "complex_body":
            return [
                f"/// {fn.name} -- COMPLEX BODY (Phase 2 will analyze)",
                f"/// note: {p.get('note', '')}",
            ]
        cc = p.get("cost_class", "?")
        co = p.get("chain_order", "?")
        depth = p.get("eml_depth", "?")
        drift = p.get("fp16_drift_risk", "?")
        dyn = p.get("dynamics", {})
        fp = p.get("fpga_estimate", {})
        out = [
            f"/// {fn.name}",
            f"/// Chain order: {co}     Cost class: {cc}",
            f"/// EML depth:   {depth}  Drift risk: {drift}",
        ]
        if dyn:
            out.append(
                f"/// Dynamics:    {dyn.get('oscillations', 0)} osc, "
                f"{dyn.get('decays', 0)} decay  "
                f"(predicted_r={dyn.get('predicted_r', 0)})"
            )
        if fp:
            out.append(
                f"/// FPGA est:   {fp.get('mac_units', 0)} MAC, "
                f"{fp.get('exp_units', 0)} exp, "
                f"{fp.get('ln_units', 0)} ln, "
                f"{fp.get('trig_units', 0)} trig "
                f"-> {fp.get('estimated_latency_cycles', 0)} cy "
                f"@ {fp.get('precision_bits_needed', 32)}-bit"
            )
        for w in p.get("stability_warnings", []):
            out.append(f"/// WARNING: {w}")
        return out

    # ── Statements ────────────────────────────────────────────

    def _emit_block(
        self,
        block: ASTNode | None,
        *,
        return_value: bool,
        tuple_struct: str | None = None,
    ) -> list[str]:
        if block is None or block.kind != NodeKind.BLOCK:
            return ["// empty block"]
        out: list[str] = []
        for i, stmt in enumerate(block.children):
            is_last = (i == len(block.children) - 1)
            if stmt.kind == NodeKind.LET:
                rty = _rust_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"let {stmt.value}: {rty} = {rhs};")
            elif stmt.kind == NodeKind.LET_MUT:
                rty = _rust_type(stmt.type_annotation or "Real")
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"let mut {stmt.value}: {rty} = {rhs};")
            elif stmt.kind == NodeKind.ASSIGN:
                rhs = self._emit_expr(stmt.children[0])
                out.append(f"{stmt.value} = {rhs};")
            elif stmt.kind == NodeKind.WHILE:
                cond = self._emit_expr(stmt.children[0])
                inner = self._emit_block(stmt.children[1], return_value=False)
                out.append(f"while {cond} {{")
                for ln in inner:
                    out.append(self.indent + ln)
                out.append("}")
            elif stmt.kind == NodeKind.EXPR_STMT:
                expr = self._emit_expr(stmt.children[0])
                out.append(f"{expr};")
            elif is_last:
                # Final expression -- Rust uses a tail expression
                # without a trailing semicolon as the block's value.
                if (return_value
                        and stmt.kind == NodeKind.TUPLE
                        and tuple_struct is not None):
                    elems = ", ".join(
                        f"e{j}: {self._emit_expr(c)}"
                        for j, c in enumerate(stmt.children)
                    )
                    out.append(f"{tuple_struct} {{ {elems} }}")
                else:
                    expr = self._emit_expr(stmt)
                    out.append(expr if return_value else f"{expr};")
            else:
                expr = self._emit_expr(stmt)
                out.append(f"{expr};")
        return out

    # ── Expressions ───────────────────────────────────────────

    def _emit_expr(self, node: ASTNode) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            return str(node.value)

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0])
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(!{sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0])
            right = self._emit_expr(node.children[1])
            return f"({left} {node.value} {right})"

        if kind == NodeKind.TUPLE:
            # Bare tuple literal outside return position -- Rust's
            # native tuple syntax.
            elems = ", ".join(self._emit_expr(c) for c in node.children)
            return f"({elems})"

        if kind in _BUILTIN_TO_RUST:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            return f"{_BUILTIN_TO_RUST[kind]}({args})"

        if kind == NodeKind.CALL:
            args = ", ".join(self._emit_expr(c) for c in node.children)
            return f"{node.value}({args})"

        raise CompileError(
            f"Rust backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
