"""Rust backend -- emits Rust source consuming the monogate-sys crate.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.2.
SCAFFOLD.
"""

from __future__ import annotations

from lang.parser.ast_nodes import EMLFunction


class RustBackend:
    """Compile an EMLFunction list to Rust source."""

    name = "rust"

    def compile(self, program: list[EMLFunction]) -> str:
        lines = [
            "// Generated by EML-lang compiler",
            "use monogate_sys::*;",
            "",
        ]
        for func in program:
            lines.append(self._compile_function(func))
            lines.append("")
        return "\n".join(lines)

    def _compile_function(self, func: EMLFunction) -> str:
        params = ", ".join(f"{p['name']}: f64" for p in func.params)
        return (
            f"/// {func.name}\n"
            f"/// Chain order: {func.profile.get('chain_order') if func.profile else '?'}\n"
            f"pub fn {func.name}({params}) -> f64 {{\n"
            f"    todo!(\"backend body lands in Phase 2.2\")\n"
            f"}}"
        )
