"""TrigSD59x18 library emitter.

PRBMath SD59x18 covers exp/ln/sqrt/abs/pow but not trig. This module
emits a companion ``TrigSD59x18.sol`` library that fills the gap so
EML kernels using sin/cos/tan/asin/acos/atan/sinh/cosh/tanh can be
deployed end-to-end.

Implementation strategy
-----------------------
Hyperbolic functions are exact compositions of PRBMath ``exp``::

    sinh(x) = (exp(x) - exp(-x)) / 2
    cosh(x) = (exp(x) + exp(-x)) / 2
    tanh(x) = sinh(x) / cosh(x)

Circular trig uses Taylor / Maclaurin series with range reduction
into the convergence sweet spot. Coefficients are precomputed; the
emitted Solidity uses Horner's method to minimize the number of
fixed-point multiplications.

  sin(x): reduce to [-π/2, π/2] via 2π and π identities, then a
          7-term Horner Taylor series.
  cos(x) = sin(π/2 - x).
  tan(x) = sin(x) / cos(x), with a div-by-zero check.
  atan(x): reduce |x| > 1 via atan(x) = π/2*sign(x) - atan(1/x); use
           a 12-term Maclaurin in [-1, 1].
  asin(x) = atan(x / sqrt(1 - x²)) (uses PRBMath ``sqrt``).
  acos(x) = π/2 - asin(x).

Numerical caveats
-----------------
Precision: targeted ~14 decimal digits — comfortably below SD59x18's
18-digit fixed-point precision but conservative for the Taylor term
budget. atan's Maclaurin convergence is slow near |x|=1; if your
kernel needs sub-ULP atan precision in that region, drop in a more
careful library (e.g. ABDK) by overriding the override.

Gas: ~30k gas for sin/cos, ~50k for tan, ~80k for atan/asin/acos,
~25k for hyperbolics (one exp per inverse). Document these in the
parent contract's NatSpec via the existing solidity_gas overrides.
"""

from __future__ import annotations

from dataclasses import dataclass

from lang.parser.ast_nodes import NodeKind


# Builtin → TrigSD59x18 library function name.
_BUILTIN_TO_TRIG: dict[NodeKind, str] = {
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.ASIN:  "asin",
    NodeKind.ACOS:  "acos",
    NodeKind.ATAN:  "atan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
}


# ── Result type ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class TrigLibrary:
    """The emitted TrigSD59x18.sol library + the overridden builtins."""
    library_name: str
    source: str
    overridden: tuple[NodeKind, ...]


# ── Public API ──────────────────────────────────────────────────────


TRIG_BUILTINS: frozenset[NodeKind] = frozenset(_BUILTIN_TO_TRIG)


def overrides_supported_by_trig(used_builtins: set[NodeKind]) -> set[NodeKind]:
    """Return the subset of ``used_builtins`` that TrigSD59x18 covers."""
    return {k for k in used_builtins if k in _BUILTIN_TO_TRIG}


def trig_function_name(kind: NodeKind) -> str:
    """The library-side function name for one trig builtin."""
    return _BUILTIN_TO_TRIG[kind]


def emit_trig_library(used_builtins: set[NodeKind]) -> TrigLibrary | None:
    """Emit the ``TrigSD59x18.sol`` library if any trig builtin is used.

    Returns ``None`` when no trig functions are needed — the caller
    should skip writing the library file in that case.
    """
    overridden = tuple(sorted(
        overrides_supported_by_trig(used_builtins),
        key=lambda k: k.name,
    ))
    if not overridden:
        return None
    return TrigLibrary(
        library_name="TrigSD59x18",
        source=_LIBRARY_SOURCE,
        overridden=overridden,
    )


# ── Static library source ───────────────────────────────────────────


_LIBRARY_SOURCE = """\
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// TrigSD59x18 — circular + hyperbolic trig in PRBMath SD59x18 fixed-point.
//
// PRBMath SD59x18 supplies exp/ln/sqrt/abs/pow but not trig. This library
// fills the gap so monogate-forge Solidity kernels with sin/cos/atan/etc.
// are deployable without a third-party trig dependency.
//
// Generated by monogate-forge --target solidity --with-prbmath. The math
// is documented in the comments above each function; Foundry tests in the
// audit bundle exercise every function on random inputs.
//
// Precision: ~14 decimal digits over the typical kernel input range.
// Gas: O(10k-80k) per call depending on the function. Override in a
// derived library if you need a tighter implementation.

import { SD59x18, sd, unwrap } from \"@prb/math/src/SD59x18.sol\";
import { exp, sqrt } from \"@prb/math/src/sd59x18/Math.sol\";

library TrigSD59x18 {
    // ── Constants (SD59x18 = 18 decimal fixed-point) ──
    // PI ≈ 3.141592653589793238
    int256 internal constant PI         = 3_141592653589793238;
    int256 internal constant TWO_PI     = 6_283185307179586477;
    int256 internal constant HALF_PI    = 1_570796326794896619;
    int256 internal constant QUARTER_PI =   785398163397448310;
    int256 internal constant ONE        = 1_000000000000000000;
    int256 internal constant TWO        = 2_000000000000000000;

    // ── Circular trig ────────────────────────────────────────────

    /// @notice sin(x), x in any real range. Uses 2π + π/2 reduction
    /// then 7-term Horner Taylor in [-π/2, π/2].
    function sin(SD59x18 x) internal pure returns (SD59x18) {
        int256 xi = unwrap(x);
        // Reduce mod 2π into (-π, π].
        xi = _reduceInto(xi, TWO_PI);
        if (xi > PI)  xi -= TWO_PI;
        if (xi < -PI) xi += TWO_PI;
        // Reflect into [-π/2, π/2] using sin(π - x) = sin(x).
        if (xi > HALF_PI)  xi = PI - xi;
        if (xi < -HALF_PI) xi = -PI - xi;
        return _sinTaylor(xi);
    }

    /// @notice cos(x) = sin(π/2 - x).
    function cos(SD59x18 x) internal pure returns (SD59x18) {
        return sin(sd(HALF_PI - unwrap(x)));
    }

    /// @notice tan(x) = sin(x) / cos(x). Reverts when cos(x) == 0.
    function tan(SD59x18 x) internal pure returns (SD59x18) {
        SD59x18 c = cos(x);
        require(unwrap(c) != 0, \"TrigSD59x18: tan() singularity\");
        return _div(sin(x), c);
    }

    /// @notice atan(x) for any real x. Uses Maclaurin in [-1, 1] and
    /// the identity atan(x) = π/2*sign(x) - atan(1/x) for |x| > 1.
    function atan(SD59x18 x) internal pure returns (SD59x18) {
        int256 xi = unwrap(x);
        bool inverted = false;
        bool negate   = false;
        if (xi < 0) { xi = -xi; negate = true; }
        if (xi > ONE) {
            // atan(1/x) is in [0, π/4]; result = π/2 - atan(1/x).
            xi = _divRaw(ONE, xi);
            inverted = true;
        }
        int256 r = _atanMaclaurin(xi);
        if (inverted) r = HALF_PI - r;
        if (negate)   r = -r;
        return sd(r);
    }

    /// @notice asin(x) for x in [-1, 1]. asin(x) = atan(x / sqrt(1-x²)).
    function asin(SD59x18 x) internal pure returns (SD59x18) {
        int256 xi = unwrap(x);
        require(xi >= -ONE && xi <= ONE, \"TrigSD59x18: asin |x|>1\");
        if (xi == ONE)  return sd(HALF_PI);
        if (xi == -ONE) return sd(-HALF_PI);
        // sqrt(1 - x²) via PRBMath sqrt; x² done in fixed-point.
        int256 xsq      = _mulRaw(xi, xi);
        int256 oneMinus = ONE - xsq;
        SD59x18 root    = sqrt(sd(oneMinus));
        SD59x18 ratio   = _div(x, root);
        return atan(ratio);
    }

    /// @notice acos(x) = π/2 - asin(x).
    function acos(SD59x18 x) internal pure returns (SD59x18) {
        return sd(HALF_PI - unwrap(asin(x)));
    }

    // ── Hyperbolic trig (exact via PRBMath exp) ──────────────────

    /// @notice sinh(x) = (exp(x) - exp(-x)) / 2.
    function sinh(SD59x18 x) internal pure returns (SD59x18) {
        SD59x18 ex   = exp(x);
        SD59x18 emx  = exp(sd(-unwrap(x)));
        int256 diff  = unwrap(ex) - unwrap(emx);
        return sd(diff / 2);
    }

    /// @notice cosh(x) = (exp(x) + exp(-x)) / 2.
    function cosh(SD59x18 x) internal pure returns (SD59x18) {
        SD59x18 ex   = exp(x);
        SD59x18 emx  = exp(sd(-unwrap(x)));
        int256 sum   = unwrap(ex) + unwrap(emx);
        return sd(sum / 2);
    }

    /// @notice tanh(x) = sinh(x) / cosh(x). Numerically stable form.
    function tanh(SD59x18 x) internal pure returns (SD59x18) {
        return _div(sinh(x), cosh(x));
    }

    // ── Internal: Taylor / Maclaurin series ──────────────────────

    /// @dev sin(x) Horner Taylor for x in [-π/2, π/2]. 7 terms ⇒
    /// max error ≈ 1e-14 across the reduced range.
    function _sinTaylor(int256 x) private pure returns (SD59x18) {
        int256 x2 = _mulRaw(x, x);
        // sin(x) = x * (1 - x²/6 * (1 - x²/20 * (1 - x²/42 *
        //          (1 - x²/72 * (1 - x²/110 * (1 - x²/156)))))
        int256 t = ONE - _mulRaw(x2, _divRaw(ONE, 156 * ONE));
        t = ONE - _mulRaw(x2, _divRaw(t,   110 * ONE));
        t = ONE - _mulRaw(x2, _divRaw(t,    72 * ONE));
        t = ONE - _mulRaw(x2, _divRaw(t,    42 * ONE));
        t = ONE - _mulRaw(x2, _divRaw(t,    20 * ONE));
        t = ONE - _mulRaw(x2, _divRaw(t,     6 * ONE));
        return sd(_mulRaw(x, t));
    }

    /// @dev atan(x) Maclaurin for x in [0, 1]. 12 odd terms ⇒
    /// max error ≈ 1e-13 at x=1; tighter inside.
    function _atanMaclaurin(int256 x) private pure returns (int256) {
        int256 x2 = _mulRaw(x, x);
        // atan(x) = x * (1 - x²/3 + x⁴/5 - x⁶/7 + x⁸/9 - ...)
        int256 sum   = 0;
        int256 term  = x;
        int256 sign  = 1;
        for (uint256 k = 0; k < 12; k++) {
            int256 denom = int256(2 * k + 1);
            sum += sign * _divRaw(term, denom * ONE);
            term = _mulRaw(term, x2);
            sign = -sign;
        }
        return sum;
    }

    // ── Internal: SD59x18 raw arithmetic ─────────────────────────

    /// @dev (a*b)/ONE in int256, with overflow guarded by Solidity 0.8.
    function _mulRaw(int256 a, int256 b) private pure returns (int256) {
        return (a * b) / ONE;
    }

    /// @dev (a*ONE)/b in int256.
    function _divRaw(int256 a, int256 b) private pure returns (int256) {
        return (a * ONE) / b;
    }

    /// @dev SD59x18 wrapped div helper.
    function _div(SD59x18 a, SD59x18 b) private pure returns (SD59x18) {
        return sd(_divRaw(unwrap(a), unwrap(b)));
    }

    /// @dev x mod m for int256 — handles negative dividends so the
    /// result is in [0, m).
    function _reduceInto(int256 x, int256 m) private pure returns (int256) {
        int256 r = x % m;
        if (r < 0) r += m;
        return r;
    }
}
"""
