"""Foundry test scaffold emitter for Solidity-compiled EML kernels.

Reads the structured spec produced by ``solidity_spec.build_spec``
and generates a ``<Contract>Test.t.sol`` Foundry test contract plus
a minimal ``foundry.toml`` so the user can run ``forge test`` on
the override contract immediately.

For each function in the spec:

  * **External (verified) functions** — fuzz test that takes a
    matching parameter tuple, ``vm.assume()`s every Solidity-rendered
    precondition, calls the function on the override contract, and
    asserts every postcondition. The fuzz test exercises the
    contract's contract-level invariants on random inputs the way a
    Lean theorem would.

  * **Internal (helper) functions** — gas-snapshot test only. Helpers
    aren't on the contract ABI so the test contract derives from the
    override and exposes a thin pass-through wrapper for benchmarking.

The emitted file compiles against forge-std v1.x and PRBMath v4.x
and assumes ``forge install foundry-rs/forge-std PaulRBerg/prb-math``
has been run in the destination project.

The scaffold is intentionally minimal — the goal is to give an
auditor a working ``forge test`` invocation, not to ship a full
property-testing harness. The user is expected to extend the
generated tests with kernel-specific oracles, equivalence tests vs
the reference Python implementation, etc.
"""

from __future__ import annotations

from dataclasses import dataclass


# ── Result type ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class FoundryScaffold:
    """One compile-ready test file + foundry.toml."""
    test_contract_name: str
    test_source: str
    foundry_toml: str


# ── Public API ──────────────────────────────────────────────────────


def emit_foundry_scaffold(
    *,
    spec: dict,
    override_contract: str,
    override_path: str = "./{contract}.sol",
    indent: str = "    ",
) -> FoundryScaffold:
    """Build a Foundry test scaffold from a structured spec dict.

    Parameters
    ----------
    spec
        Output of ``solidity_spec.build_spec``.
    override_contract
        Name of the deployable contract under test (typically the
        ``<Parent>WithPRBMath`` from the PRBMath generator).
    override_path
        Solidity import path of the override contract.
    """
    test_contract_name = f"{spec['contract']}Test"
    src = _render_test_source(
        test_contract=test_contract_name,
        override_contract=override_contract,
        override_path=override_path.format(contract=override_contract),
        spec=spec,
        indent=indent,
    )
    return FoundryScaffold(
        test_contract_name=test_contract_name,
        test_source=src,
        foundry_toml=_FOUNDRY_TOML,
    )


# ── foundry.toml ────────────────────────────────────────────────────

# Minimal config the audit bundle ships next to the .t.sol. Pins
# Solidity, enables fuzzing with a reasonable runs count, and points
# at the standard Foundry layout (src/, test/, lib/).
_FOUNDRY_TOML = """\
[profile.default]
src        = "src"
test       = "test"
out        = "out"
libs       = ["lib"]
solc       = "0.8.20"
optimizer  = true
optimizer_runs = 200

[fuzz]
runs       = 256
max_test_rejects = 65536

[invariant]
runs       = 64
depth      = 64

# Generated by monogate-forge --target solidity --with-foundry-tests.
# Run `forge install foundry-rs/forge-std PaulRBerg/prb-math` before
# the first `forge test`.
"""


# ── Test contract rendering ─────────────────────────────────────────


def _render_test_source(
    *,
    test_contract: str,
    override_contract: str,
    override_path: str,
    spec: dict,
    indent: str,
) -> str:
    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: MIT")
    lines.append("pragma solidity ^0.8.20;")
    lines.append("")
    lines.append(
        f"// {test_contract} — Foundry scaffold for "
        f"{override_contract}."
    )
    lines.append(
        "// Generated by monogate-forge --target solidity --with-foundry-tests."
    )
    lines.append("//")
    lines.append(
        '// Run with `forge test`. Requires `forge install '
        'foundry-rs/forge-std`'
    )
    lines.append("// and `forge install PaulRBerg/prb-math` in the host project.")
    lines.append("")
    lines.append('import { Test } from "forge-std/Test.sol";')
    lines.append(f'import {{ {override_contract} }} from "{override_path}";')
    lines.append("")
    # Helper subcontract that exposes internal functions for gas
    # benchmarking. Only emitted if there's at least one internal fn.
    has_internal = any(
        not fn.get("verified") for fn in spec.get("functions", [])
        if not fn.get("solidity_name", "").startswith("_")
    )
    if has_internal:
        lines.extend(_render_harness_contract(
            override_contract=override_contract,
            spec=spec, indent=indent,
        ))
        deployed_contract = f"{spec['contract']}Harness"
    else:
        deployed_contract = override_contract
    lines.append(
        f"contract {test_contract} is Test {{"
    )
    lines.append(
        f"{indent}{deployed_contract} private kernel;"
    )
    lines.append("")
    lines.append(
        f"{indent}function setUp() public {{"
    )
    lines.append(
        f"{indent}{indent}kernel = new {deployed_contract}();"
    )
    lines.append(f"{indent}}}")
    for fn in spec.get("functions", []):
        lines.append("")
        if fn.get("verified"):
            lines.extend(_render_fuzz_test(
                fn, deployed_contract=deployed_contract, indent=indent,
            ))
        else:
            lines.extend(_render_gas_snapshot_test(
                fn, deployed_contract=deployed_contract, indent=indent,
            ))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_harness_contract(
    *,
    override_contract: str,
    spec: dict,
    indent: str,
) -> list[str]:
    """Expose internal helpers as external thunks for gas benchmarking.
    Lives inside the same file so the test contract can deploy it."""
    lines: list[str] = []
    lines.append(
        f"// Test harness exposes internal helpers as external thunks "
        f"so Foundry"
    )
    lines.append("// can measure their gas in isolation.")
    lines.append(
        f"contract {spec['contract']}Harness is {override_contract} {{"
    )
    for fn in spec.get("functions", []):
        if fn.get("verified"):
            continue
        sig = ", ".join(
            f"{p['solidity_type']} {p['solidity_name']}"
            for p in fn["params"]
        )
        ret = _returns_type(fn["returns"])
        call_args = ", ".join(p["solidity_name"] for p in fn["params"])
        lines.append(
            f"{indent}function harness_{fn['solidity_name']}({sig}) "
            f"external pure returns ({ret}) {{"
        )
        lines.append(
            f"{indent}{indent}return {fn['solidity_name']}({call_args});"
        )
        lines.append(f"{indent}}}")
    lines.append("}")
    lines.append("")
    return lines


def _render_fuzz_test(
    fn: dict, *, deployed_contract: str, indent: str,
) -> list[str]:
    """Property-style fuzz test driven by the spec's pre/postconditions."""
    sig = ", ".join(
        f"{p['solidity_type']} {p['solidity_name']}"
        for p in fn["params"]
    )
    call_args = ", ".join(p["solidity_name"] for p in fn["params"])
    lines: list[str] = []
    theorem = (
        fn.get("verification", {}).get("theorem", fn["name"])
    )
    lines.append(
        f"{indent}/// @notice Fuzz test for {fn['solidity_name']} "
        f"(theorem `{theorem}`)."
    )
    lines.append(
        f"{indent}function testFuzz_{fn['solidity_name']}({sig}) public {{"
    )
    for pre in fn.get("preconditions", []):
        if "solidity_require" not in pre:
            continue
        lines.append(
            f"{indent}{indent}vm.assume({pre['solidity_require']});"
        )
    ret = _returns_type(fn["returns"])
    if ret == "":
        lines.append(
            f"{indent}{indent}kernel.{fn['solidity_name']}({call_args});"
        )
    else:
        lines.append(
            f"{indent}{indent}{ret} result = "
            f"kernel.{fn['solidity_name']}({call_args});"
        )
    for post in fn.get("postconditions", []):
        expr = post.get("expression")
        if not expr:
            continue
        lines.append(
            f"{indent}{indent}assertTrue({expr}, "
            f'"postcondition: {post.get("natspec_dev", expr)}");'
        )
    if not fn.get("postconditions"):
        # No postconditions in the spec — at minimum confirm the call
        # didn't revert. The implicit assertion is the absence of a
        # reverting kernel call above.
        lines.append(
            f"{indent}{indent}// no spec postconditions; absence of "
            f"revert is the test."
        )
    lines.append(f"{indent}}}")
    return lines


def _render_gas_snapshot_test(
    fn: dict, *, deployed_contract: str, indent: str,
) -> list[str]:
    """Bench an internal helper through the harness wrapper."""
    sig = ", ".join(
        f"{p['solidity_type']} {p['solidity_name']}"
        for p in fn["params"]
    )
    call_args = ", ".join(p["solidity_name"] for p in fn["params"])
    # Pick zero values for each param so the test compiles without
    # requiring the user to invent inputs. The point of this test
    # is the gas number, not the result correctness.
    zero_args = ", ".join(_zero_for(p["solidity_type"]) for p in fn["params"])
    lines: list[str] = []
    gas = fn.get("gas_estimate", 0)
    lines.append(
        f"{indent}/// @notice Gas snapshot for "
        f"{fn['solidity_name']} (estimated ~{gas} gas)."
    )
    lines.append(
        f"{indent}function test_gas_{fn['solidity_name']}() public view {{"
    )
    lines.append(
        f"{indent}{indent}uint256 gasBefore = gasleft();"
    )
    lines.append(
        f"{indent}{indent}kernel.harness_{fn['solidity_name']}({zero_args});"
    )
    lines.append(
        f"{indent}{indent}uint256 gasUsed = gasBefore - gasleft();"
    )
    lines.append(
        f"{indent}{indent}emit log_named_uint(\"gas\", gasUsed);"
    )
    lines.append(f"{indent}}}")
    return lines


# ── Type / literal helpers ──────────────────────────────────────────


def _returns_type(returns_spec: dict) -> str:
    if returns_spec.get("kind") == "tuple":
        inner = ", ".join(returns_spec.get("solidity_types", []))
        return f"({inner})"
    return returns_spec.get("solidity_type", "int256")


def _zero_for(sol_type: str) -> str:
    """A minimal valid literal for a Solidity type — used in gas
    snapshots where only the gas count matters, not the inputs."""
    if sol_type == "bool":
        return "false"
    if sol_type.startswith("uint"):
        return "0"
    return "int256(0)" if sol_type == "int256" else "0"
