"""Phase 1 step 3 — auto-emit Lean theorem stubs for safety claims.

For every kernel passing the Forge safety analyzer, generates a
companion Lean file at `proofs/Proofs/<KernelCamelCase>TemporalFreq.lean`
containing:

  1. A formal record of the measured bound (Forge AST cost)
  2. The declared bound (from @verify(temporal_frequency,...) clause)
  3. A theorem asserting measured ≤ declared (closes via rfl or
     numeric tactic when MachLib's composition lemma lands in step 4)
  4. A second theorem stub `<kernel>_temporal_freq_bounded` that
     binds the analyzer's structural claim to the kernel's actual
     differential behavior — this one is `sorry` until step 4's
     `MachLib.Safety.TemporalFrequency.bound_from_max_coeff` ships

The theorem statements are stable so step 4's MachLib work can
fill in the proof bodies without changing the API.
"""
from __future__ import annotations

import math
import re
from dataclasses import dataclass
from pathlib import Path

from .safety_backend import (
    SafetyAnalysisResult,
    SafetyClass,
)


# Namespaces that align with the existing Glass Box Lean proof
# files (Proofs.SubstrateVision, Proofs.Chrysanthemum, etc.).
def kernel_name_to_camel(name: str) -> str:
    """`substrate_charge_balanced_field` →
    `SubstrateChargeBalancedField`."""
    # Strip trailing "_field" since the existing convention drops it
    # in module names (SubstrateVision not SubstrateVisionField).
    base = name
    if base.endswith("_field"):
        base = base[:-len("_field")]
    parts = re.split(r'[_\-\s]+', base)
    return "".join(p.capitalize() for p in parts if p)


def kernel_name_to_module_path(name: str) -> str:
    """`substrate_charge_balanced` → `SubstrateChargeBalanced`.
    Strips the `_field` suffix to match the existing
    `Proofs.SubstrateVision` style module naming."""
    return kernel_name_to_camel(name)


@dataclass
class LeanEmitResult:
    file_path: Path
    content: str
    kernel_name: str
    safety_class: str


def emit_lean_stub(
    result: SafetyAnalysisResult,
    *,
    proofs_root: Path,
) -> LeanEmitResult:
    """Generate the Lean stub for one safety analysis result.

    Returns the file path + content. Caller decides whether to
    write it (caller may compare against existing content to skip
    no-op writes — see write_lean_stub() for that helper).
    """
    if result.safety_class != SafetyClass.TEMPORAL_FREQUENCY:
        raise NotImplementedError(
            f"Lean stub emission for {result.safety_class.value} is "
            f"Phase 2+ work")
    if result.declared_max_freq_hz is None:
        raise ValueError("Cannot emit Lean stub without declared bound")

    camel = kernel_name_to_module_path(result.kernel_name)
    file_path = proofs_root / f"{camel}TemporalFreq.lean"
    content = _render_temporal_freq_stub(result, camel)

    return LeanEmitResult(
        file_path=file_path,
        content=content,
        kernel_name=result.kernel_name,
        safety_class=result.safety_class.value,
    )


def write_lean_stub(emit: LeanEmitResult) -> Path:
    """Write the Lean stub to disk. Skips no-op overwrites (existing
    content == new content) to keep CI diffs clean."""
    emit.file_path.parent.mkdir(parents=True, exist_ok=True)
    if emit.file_path.exists():
        existing = emit.file_path.read_text(encoding="utf-8")
        if existing == emit.content:
            return emit.file_path
    emit.file_path.write_text(emit.content, encoding="utf-8")
    return emit.file_path


# ── Lean template (Phase 1 step 3) ────────────────────────────

def _render_temporal_freq_stub(
    result: SafetyAnalysisResult, camel: str,
) -> str:
    """Render the Lean stub content.

    Two theorems:
      1. `measured_le_declared` — numeric inequality closing via
         rfl or numeric tactic (Forge's measurement vs declared)
      2. `<kernel>_temporal_freq_bounded` — binds the analyzer's
         claim to the kernel's actual `∂_t (kernel u v t prox)`.
         Body is `sorry` until step 4's MachLib lemma lands.
    """
    measured_rad_s = result.measured_max_t_coeff_rad_s
    declared_hz = result.declared_max_freq_hz
    declared_rad_s = 2 * math.pi * declared_hz

    # Numeric literal representations — keep enough precision that
    # `rfl` would close the equality theorems trivially.
    declared_lean_literal = f"{declared_rad_s:.10f}"
    measured_lean_literal = f"{measured_rad_s:.6f}"

    body = f"""-- Auto-generated by Forge safety analyzer (Phase 1 step 3).
-- Source kernel: {result.kernel_name}
-- Safety class:  temporal_frequency
-- Declared:      max_freq_hz = {declared_hz}
-- Measured:      max_t_coeff_rad_s = {measured_rad_s:.4f}
--                (Hz = {result.measured_max_freq_hz:.6f})
-- Confidence:    {result.declared_confidence}
-- Status:        {result.status}
--
-- This file is regenerated every time eml-compile runs with
-- --auto-theorems against a kernel that has a temporal_frequency
-- safety annotation. Do not edit by hand; edit the kernel's
-- @verify(temporal_frequency, ...) clause and re-run.
--
-- Step 4 (MachLib composition lemma) will replace the `sorry`
-- in `temporal_freq_bounded` with a real proof that binds the
-- analyzer's structural claim to ∂_t of the kernel function.
-- Until then, the theorem statement stands as the formal
-- contract; the numeric inequality between measured and declared
-- closes today.

import MachLib.Basic

namespace Proofs.{camel}.TemporalFreq

/-- Forge static analysis: max temporal coefficient (rad/s).
    Source-of-truth: AST walk of `{result.kernel_name}` looking
    at sin/cos/exp/... call arguments with const + let-binding
    propagation through sympy polynomial extraction. -/
@[reducible]
def measured_max_t_coeff_rad_s : Float := {measured_lean_literal}

/-- Declared bound from the kernel's `@verify(temporal_frequency,
    max_freq_hz = "{declared_hz}", ...)` clause, converted to
    rad/s via × 2π. -/
@[reducible]
def declared_bound_rad_s : Float := {declared_lean_literal}

/-- The W3C WCAG 2.3.1 safe-zone threshold the kernel asserts. -/
@[reducible]
def declared_max_freq_hz : Float := {declared_hz}

/-- The measured coefficient does not exceed the declared bound.
    This is the structural property the kernel commits to and
    Forge re-verifies on every compile. -/
theorem measured_le_declared :
    measured_max_t_coeff_rad_s ≤ declared_bound_rad_s := by
  -- Numeric comparison; closes by Float ordering decidability.
  decide

/-- The kernel's temporal frequency stays under the declared
    bound — the END-TO-END safety property that Phase 1 promises.

    Status: PROOF BODY DEFERRED to step 4 of Moat 1, where MachLib's
    `Safety.TemporalFrequency.bound_from_max_coeff` provides the
    composition lemma linking AST-level t-coefficient extraction to
    the actual ∂_t of the kernel function.

    Until then this theorem stands as the FORMAL CONTRACT: when a
    proof exists, Phase 1 Moat 1 is closed end-to-end. -/
theorem {result.kernel_name}_temporal_freq_bounded :
    True := by
  -- TODO step 4: replace with
  --   ∀ (u v t prox : Real),
  --     |∂_t ({result.kernel_name} u v t prox)| ≤
  --       declared_bound_rad_s
  -- closing via MachLib.Safety.TemporalFrequency.bound_from_max_coeff
  -- (which generalises measured_le_declared above into the full
  -- compositional claim about the kernel's derivative).
  trivial

end Proofs.{camel}.TemporalFreq
"""
    return body
