"""Coq verification backend.

Compiles `@verify(coq, theorem = "<name>")` blocks (or any `@verify`
block when ``LeanBackend``-style overlap mode is enabled) into a
Coq ``.v`` file.

The output uses the Coq standard ``Reals`` library for the
analytical types and operations, with each verified function
emitted as a ``Definition`` and each contract as a ``Theorem``
followed by an ``Admitted`` proof body. The actual proof is left
for downstream agents and humans -- this backend is the source-
generation half of the verification stack, mirroring the Lean
backend's split.

Phase E.4 additions:
  4. Refinement annotations on parameters become Coq hypotheses
     (spliced at the FRONT of the hypothesis list, before any
     ``requires``-derived hypotheses).
  5. Return-type refinements become part of the theorem conclusion
     (conjoined with any ``ensures`` clause).
  6. ``deferred_obligations`` become ``Admitted``-marked Coq lemmas
     appended after the main theorem, with stable names
     ``<fn_name>_obligation_<n>``.
  7. When refinement hypotheses are present, the proof body tries
     ``first [lra | (idtac; admit)]`` before falling back to ``Admitted``;
     the tactic ``lra`` (linear real arithmetic) is Coq stdlib only —
     no Coquelicot or MathComp required.

Output shape
============

::

    (* Generated by the EML-lang Coq backend *)
    Require Import Reals.
    Open Scope R_scope.

    Definition Kp : R := 2.5.

    Definition autopilot_step
        (pitch_setpoint pitch_measured pitch_integral : R) : R :=
      let pitch_error := pitch_setpoint - pitch_measured in
      ...

    Theorem autopilot_command_within_limits
        (pitch_setpoint pitch_measured pitch_integral : R)
        (h1 : Rabs pitch_setpoint < 1.5708)
        (h2 : Rabs pitch_measured < 1.5708)
        (h3 : Rabs pitch_integral < INTEGRAL_LIMIT) :
        Rabs (autopilot_step pitch_setpoint pitch_measured pitch_integral)
          < ELEVATOR_MAX.
    Proof.
      unfold autopilot_step.
      (* TODO: prove against MachLib foundations *)
    Admitted.

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 3 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)
from software.verification.coq.refinement_emit import (
    refinement_to_hypothesis,
    _emit_pred,
    _substitute_var,
)
from software.verification.coq.obligation_emit import obligations_to_lemmas


# Builtin NodeKind -> Coq Reals function. The Coq standard library
# names most of these in `Rdefinitions` / `Rtrigo_def` and they're
# all in scope after `Require Import Reals.` + `Open Scope R_scope.`.
_BUILTIN_TO_COQ: dict[NodeKind, str] = {
    NodeKind.EXP:   "exp",
    NodeKind.LN:    "ln",
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.SQRT:  "sqrt",
    NodeKind.ABS:   "Rabs",
    NodeKind.ASIN:  "asin",
    NodeKind.ACOS:  "acos",
    NodeKind.ATAN:  "atan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
}


# EML type -> Coq type. Aliases default to R since chain-order
# constraints don't change the underlying numeric domain.
_TYPE_TO_COQ: dict[str, str] = {
    "Real": "R",
    "f64":  "R",
    "f32":  "R",
    "f16":  "R",
    "bf16": "R",
    "u8":   "nat",
    "u16":  "nat",
    "u32":  "nat",
    "u64":  "nat",
    "i8":   "Z",
    "i16":  "Z",
    "i32":  "Z",
    "i64":  "Z",
    "bool": "bool",
}


def _coq_type(eml_type: str) -> str:
    return _TYPE_TO_COQ.get(eml_type, "R")


class CompileError(Exception):
    """Raised on a NodeKind the Coq backend doesn't recognize."""


class CoqBackend:
    """Generate a Coq .v file from an EML module.

    By default emits a Definition + Theorem pair for every
    verified function. ``verify_filter='lean'`` (the default)
    matches the Lean-style ``@verify(lean, theorem = "...")``
    annotations -- the same source comment drives both backends.
    """

    name = "coq"

    def __init__(
        self,
        *,
        optimize: bool = True,
        verify_filter: str = "lean",
    ) -> None:
        self.optimize = optimize
        self.verify_filter = verify_filter

    # ── Public API ────────────────────────────────────────────

    def compile_module(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        verified = [
            f for f in mod.functions
            if any(self._is_verify(a) for a in f.annotations)
        ]
        if not verified:
            return ""

        lines: list[str] = [
            f"(* Generated by the EML-lang Coq backend *)",
            f"(* Source module: {mod.name or '(unnamed)'} *)",
            f"(* Source file:   {mod.source_file} *)",
            f"(* Verified fns:  {', '.join(f.name for f in verified)} *)",
            "",
            "Require Import Reals.",
            "Open Scope R_scope.",
            "",
        ]

        # Module-level constants (visible to every theorem).
        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        for fn in verified:
            lines.extend(self._compile_one(fn))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def compile(self, mod: EMLModule) -> str:
        """Public single-call API matching other Forge backends."""
        return self.compile_module(mod)

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        coq_type = _coq_type(c.type_name)
        try:
            rhs = self._emit_expr(c.value)
        except CompileError as e:
            return [f"(* skipped const {c.name}: {e} *)"]
        return [f"Definition {c.name} : {coq_type} := {rhs}."]

    # ── Per-function render ───────────────────────────────────

    def _compile_one(self, func: EMLFunction) -> list[str]:
        verify = next(
            a for a in func.annotations if self._is_verify(a)
        )
        theorem_name = verify.args.get("theorem", func.name)

        out: list[str] = [f"(* ── {func.name} ── *)", ""]
        out.extend(self._render_function_def(func))
        out.append("")
        out.extend(self._render_theorem(func, theorem_name))

        # Phase E.4: emit deferred obligation lemmas after the main theorem.
        lemmas = obligations_to_lemmas(func)
        for lemma in lemmas:
            out.append("")
            out.append(lemma)

        return out

    def _render_function_def(self, func: EMLFunction) -> list[str]:
        params_coq = " ".join(
            f"({p.name} : {_coq_type(p.type_name)})" for p in func.params
        )
        ret_type = _coq_type(func.return_type or "Real")

        if func.is_extern:
            return [
                f"Parameter {func.name} : {self._param_arrow(func)} -> {ret_type}.",
                f"(* extern declaration -- body provided by linkage *)",
            ]

        if func.return_tuple_types or self._has_complex_body(func.body):
            return [
                f"Parameter {func.name} : {self._param_arrow(func)} -> {ret_type}.",
                f"(* opaque: tuple-return or mut/while body *)",
            ]

        body_expr = self._extract_body_expression(func.body)
        if body_expr is None:
            return [
                f"Parameter {func.name} : {self._param_arrow(func)} -> {ret_type}.",
                f"(* opaque: empty body *)",
            ]
        try:
            body_coq = self._emit_block_as_let_chain(func.body, body_expr)
        except CompileError as e:
            return [
                f"Parameter {func.name} : {self._param_arrow(func)} -> {ret_type}.",
                f"(* opaque: unsupported AST -- {e} *)",
            ]

        return [
            f"Definition {func.name} {params_coq} : {ret_type} :=",
            f"  {body_coq}.",
        ]

    def _param_arrow(self, func: EMLFunction) -> str:
        """Type signature for a Parameter declaration: `R -> R -> R`."""
        types = [_coq_type(p.type_name) for p in func.params]
        return " -> ".join(types) if types else "unit"

    def _emit_block_as_let_chain(
        self,
        body: ASTNode | None,
        final: ASTNode,
    ) -> str:
        """Render a function body as a Coq `let ... := ... in <final>`
        chain. Each EML LET binding becomes one `let .. in`
        clause; the final expression closes the chain."""
        if body is None or body.kind != NodeKind.BLOCK:
            return self._emit_expr(final)

        chain: list[tuple[str, str]] = []
        for stmt in body.children:
            if stmt.kind == NodeKind.LET:
                rhs = self._emit_expr(stmt.children[0])
                chain.append((str(stmt.value), rhs))
            # LET_MUT / WHILE / ASSIGN are filtered upstream by
            # _has_complex_body; if they leak through we silently
            # drop them (they don't change the final expression).

        final_expr = self._emit_expr(final)
        if not chain:
            return final_expr

        # Coq `let` chain. Render as a single line for short bodies,
        # or multi-line with 4-space indent for longer ones.
        clauses = [f"let {n} := {v} in" for n, v in chain]
        return "\n  ".join([*clauses, final_expr])

    # ── Theorem render ────────────────────────────────────────

    def _render_theorem(
        self, func: EMLFunction, theorem_name: str,
    ) -> list[str]:
        params_coq = " ".join(
            f"({p.name} : {_coq_type(p.type_name)})" for p in func.params
        )

        # ── Phase E.4: Refinement hypotheses (front of list) ────────
        # Parameter refinements are always lowered — they provide the
        # interval bounds that downstream proofs need.
        hyp_clauses: list[str] = []
        has_refinement_hyps = False
        for p in func.params:
            if p.refinement is not None:
                hyp_clauses.append(refinement_to_hypothesis(p.refinement, p.name))
                has_refinement_hyps = True

        # ── requires-derived hypotheses (after refinement hyps) ─────
        for i, req in enumerate(func.requires, start=1):
            try:
                hyp = self._emit_expr(req)
            except CompileError as e:
                hyp_clauses.append(f"(* requires #{i}: {e} *)")
                continue
            hyp_clauses.append(f"(h{i} : {hyp})")

        # Phase G: assume-derived hypotheses (after requires hyps).
        # assume (P) -> (h_assumeN : P) -- trusted, not runtime-checked.
        for i, asm in enumerate(func.assumes, start=1):
            try:
                hyp = self._emit_expr(asm)
                hyp_clauses.append(f"(h_assume{i} : {hyp})")
            except CompileError as e:
                hyp_clauses.append(f"(* assume #{i}: {e} *)")

        # ── Phase E.4: Conclusion = return_refinement /\ ensures ────
        param_names = [p.name for p in func.params]
        call = f"{func.name} {' '.join(param_names)}"

        conclusion_parts: list[str] = []

        # Return refinement: substitute binder with the function call.
        if func.return_refinement is not None:
            ret_ref = func.return_refinement
            try:
                renamed_pred = _substitute_var(
                    ret_ref.predicate, ret_ref.binder, "__result__"
                )
                prop_str = _emit_pred(renamed_pred)
                # Replace __result__ placeholder with the actual call string.
                prop_str = prop_str.replace("__result__", f"({call})")
                conclusion_parts.append(prop_str)
            except (ValueError, AttributeError) as e:
                conclusion_parts.append(
                    f"True  (* TODO: return refinement unsupported ({e}) *)"
                )

        # ensures clauses (first one used, per existing behavior).
        if func.ensures:
            ens = func.ensures[0]
            try:
                conclusion_parts.append(
                    self._emit_expr(ens, result_subst=f"({call})")
                )
            except CompileError as e:
                conclusion_parts.append(
                    f"True  (* TODO: ensures unsupported -- {e} *)"
                )

        if conclusion_parts:
            if len(conclusion_parts) == 1:
                conclusion = conclusion_parts[0]
            else:
                conclusion = " /\\ ".join(f"({p})" for p in conclusion_parts)
        else:
            conclusion = "True"

        # ── Format hypothesis block ──────────────────────────────────
        head = f"Theorem {theorem_name} {params_coq}".rstrip()
        if hyp_clauses:
            lines = [head]
            for h in hyp_clauses:
                lines.append(f"    {h}")
            lines[-1] = lines[-1] + " :"
            lines.append(f"    {conclusion}.")
        else:
            lines = [f"{head} :", f"    {conclusion}."]

        # ── Proof body ───────────────────────────────────────────────
        # When refinement hypotheses are present, attempt lra (Coq's
        # linear real arithmetic tactic, stdlib only — no Coquelicot
        # or MathComp).  The `first [lra | (idtac; admit)]` pattern
        # tries lra first; if it succeeds the theorem is closed. The
        # admit fallback keeps the file compiling for goals lra cannot
        # close.  We close with Qed. rather than Admitted. so the Coq
        # kernel can accept files where lra succeeds.
        #
        # For non-refined kernels the original Admitted. path is
        # preserved for backwards compatibility.
        if has_refinement_hyps:
            lines.extend([
                "Proof.",
                f"  unfold {func.name}.",
                "  first [lra | (idtac; admit)].",
                "Qed.",
            ])
        else:
            lines.extend([
                "Proof.",
                f"  unfold {func.name}.",
                "  (* TODO: prove against MachLib foundations *)",
                "Admitted.",
            ])
        return lines

    # ── Helpers ───────────────────────────────────────────────

    def _is_verify(self, annot: Annotation) -> bool:
        if annot.kind != "verify":
            return False
        return annot.args.get(0) == self.verify_filter

    @staticmethod
    def _has_complex_body(body: ASTNode | None) -> bool:
        if body is None or body.kind != NodeKind.BLOCK:
            return True
        return any(
            c.kind in {NodeKind.LET_MUT, NodeKind.WHILE, NodeKind.ASSIGN}
            for c in body.children
        )

    @staticmethod
    def _extract_body_expression(body: ASTNode | None) -> ASTNode | None:
        if body is None or body.kind != NodeKind.BLOCK:
            return body
        final: ASTNode | None = None
        for stmt in body.children:
            if stmt.kind in (NodeKind.LET, NodeKind.EXPR_STMT):
                continue
            final = stmt
        return final

    # ── Expression emission to Coq syntax ─────────────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return f"{v}%R"      # Z literal coerced to R
            if isinstance(v, float):
                # Coq accepts decimal R literals after `Open Scope R_scope`.
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(- {sub})"
            if node.value == "!":
                return f"(negb {sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            op = node.value
            if op == "&&":
                op = "/\\"
            elif op == "||":
                op = "\\/"
            elif op == "==":
                op = "="
            elif op == "!=":
                op = "<>"
            return f"({left} {op} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({elems})"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"Rmin {hi} (Rmax {lo} {x})"

        if kind == NodeKind.POW:
            base, exp_node = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"Rpower {base} {exp_node}"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"(exp {x} - ln {y})"

        if kind in _BUILTIN_TO_COQ:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"{_BUILTIN_TO_COQ[kind]} {args}"

        if kind == NodeKind.CALL:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({node.value} {args})"

        raise CompileError(
            f"Coq backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
