"""End-to-end tests for the EML-lang standard library.

For every `.eml` file under `lang/spec/stdlib/`:

  1. The file parses without error
  2. Every function profiles cleanly (status `ok` or `tuple`)
  3. The profiler-inferred chain order respects the function's
     declared `where chain_order <= N` upper bound (or its lack
     thereof)
  4. The whole module compiles to C99 source via CBackend
  5. The whole module compiles to Rust source via RustBackend

This is the foundation gate: any change to a stdlib function or
to a backend must keep this set of tests green. The integration
test for cross-target equivalence (running C + Rust + Verilog
sims and asserting identical outputs) belongs in a separate
file once the simulation harness gains pure-stdlib coverage.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from lang.parser.parser import parse_file
from lang.profiler.profiler import Profiler
from software.backends.c_backend import CBackend
from software.backends.rust_backend import RustBackend


REPO_ROOT = Path(__file__).resolve().parents[2]
STDLIB_DIR = REPO_ROOT / "lang" / "spec" / "stdlib"


def _stdlib_paths() -> list[Path]:
    return sorted(STDLIB_DIR.glob("*.eml"))


# ── 1. Parse ──────────────────────────────────────────────────


@pytest.mark.parametrize(
    "path",
    _stdlib_paths(),
    ids=lambda p: p.name,
)
def test_stdlib_file_parses(path: Path) -> None:
    mod = parse_file(str(path))
    # Module declaration must match the file basename for clarity.
    assert mod.name == path.stem, (
        f"{path.name}: module name {mod.name!r} != file stem"
    )


# ── 2. Profile ────────────────────────────────────────────────


@pytest.mark.parametrize(
    "path",
    _stdlib_paths(),
    ids=lambda p: p.name,
)
def test_stdlib_module_profiles(path: Path) -> None:
    mod = parse_file(str(path))
    Profiler().profile_module(mod)

    failures: list[str] = []
    for fn in mod.functions:
        prof = fn.profile or {}
        status = prof.get("status", "missing")
        if status not in ("ok", "tuple", "complex_body"):
            failures.append(f"{fn.name}: status={status}")

    assert not failures, "\n".join(failures)


# ── 3. Declared chain order respects inference ────────────────


def _declared_upper(fn) -> int | None:
    """Highest chain_order this function declares it conforms to."""
    for w in fn.where_clauses:
        if w.kind == "chain_order" and w.op in ("<=", "<", "==", "!="):
            return w.value
    return None


def _max_inferred(prof: dict) -> int:
    """Profiler's inferred chain order. Tuple returns store the
    same key but the value is the max over the tuple components."""
    val = prof.get("chain_order")
    if val is None:
        return 0
    if isinstance(val, (list, tuple)):
        return max(val)
    return int(val)


@pytest.mark.parametrize(
    "path",
    _stdlib_paths(),
    ids=lambda p: p.name,
)
def test_stdlib_chain_order_declarations_hold(path: Path) -> None:
    mod = parse_file(str(path))
    Profiler().profile_module(mod)

    failures: list[str] = []
    for fn in mod.functions:
        upper = _declared_upper(fn)
        if upper is None:
            continue
        inferred = _max_inferred(fn.profile or {})
        if inferred > upper:
            failures.append(
                f"{fn.name}: declared <= {upper}, inferred {inferred}",
            )
    assert not failures, "\n".join(failures)


# ── 4. C-backend compile ──────────────────────────────────────


@pytest.mark.parametrize(
    "path",
    _stdlib_paths(),
    ids=lambda p: p.name,
)
def test_stdlib_compiles_to_c(path: Path) -> None:
    mod = parse_file(str(path))
    Profiler().profile_module(mod)
    src = CBackend().compile(mod)
    # Sanity: header + at least one function definition for non-empty
    # modules. constants.eml has zero functions so we only check the
    # header.
    assert "Generated by EML-lang C backend" in src
    if mod.functions:
        # Each function's name should appear at least once.
        for fn in mod.functions:
            assert fn.name in src, (
                f"{path.name}: C source missing function {fn.name}"
            )


# ── 5. Rust-backend compile ───────────────────────────────────


@pytest.mark.parametrize(
    "path",
    _stdlib_paths(),
    ids=lambda p: p.name,
)
def test_stdlib_compiles_to_rust(path: Path) -> None:
    mod = parse_file(str(path))
    Profiler().profile_module(mod)
    src = RustBackend().compile(mod)
    assert "Generated by EML-lang Rust backend" in src or \
           "monogate_sys" in src, (
        f"{path.name}: Rust source header looks wrong"
    )
    if mod.functions:
        for fn in mod.functions:
            assert fn.name in src, (
                f"{path.name}: Rust source missing function {fn.name}"
            )


# ── 6. Function-count regression guard ────────────────────────


def test_stdlib_function_count_documented() -> None:
    """The STDLIB.md table claims a function count per module.
    Drift between the .eml files and the table is a documentation
    bug. This test pins the totals so a change to either side
    forces a deliberate update."""
    expected = {
        "math.eml":      21,
        "control.eml":   12,
        "signal.eml":    11,
        "linalg.eml":    13,
        "constants.eml":  0,
    }
    actual: dict[str, int] = {}
    for path in _stdlib_paths():
        mod = parse_file(str(path))
        actual[path.name] = len(mod.functions)
    assert actual == expected, (
        f"stdlib function counts drifted from STDLIB.md:\n"
        f"  expected: {expected}\n"
        f"  actual:   {actual}"
    )
