"""Tests for the Coq verification backend (Phase 3)."""

from __future__ import annotations

from pathlib import Path

import pytest

from lang.parser import parse_file, parse_source
from lang.profiler import Profiler
from software.verification.coq.coq_backend import CoqBackend


REPO_ROOT = Path(__file__).resolve().parents[4]
AUTOPILOT = REPO_ROOT / "industries" / "aerospace" / "flight_control" / "autopilot.eml"


@pytest.fixture
def backend() -> CoqBackend:
    return CoqBackend()


def _compile_file(path: Path, backend: CoqBackend) -> str:
    mod = parse_file(path)
    Profiler().profile_module(mod)
    return backend.compile_module(mod)


# ── Header / imports ─────────────────────────────────────────


def test_no_verify_returns_empty_string(backend):
    src = "fn f(x: Real) -> Real { x }\n"
    mod = parse_source(src)
    Profiler().profile_module(mod)
    assert backend.compile_module(mod) == ""


def test_header_imports_reals(backend):
    out = _compile_file(AUTOPILOT, backend)
    assert "Require Import Reals." in out
    assert "Open Scope R_scope." in out
    assert "Generated by the EML-lang Coq backend" in out


# ── Constants ────────────────────────────────────────────────


def test_module_constants_emit_definitions(backend):
    out = _compile_file(AUTOPILOT, backend)
    assert "Definition Kp : R := 2.5." in out
    assert "Definition INTEGRAL_LIMIT : R := 5.0." in out
    assert "Definition ELEVATOR_MAX : R := 0.349." in out


# ── Function definition + theorem ───────────────────────────


def test_autopilot_function_definition_emits_let_chain(backend):
    out = _compile_file(AUTOPILOT, backend)
    assert "Definition autopilot_step" in out
    assert "let pitch_error := " in out
    assert "let rate_target := " in out
    assert "Rmin ELEVATOR_MAX (Rmax ELEVATOR_MIN" in out


def test_autopilot_theorem_with_hypotheses(backend):
    out = _compile_file(AUTOPILOT, backend)

    # Theorem name from @verify(theorem = ...).
    assert "Theorem autopilot_command_within_limits" in out

    # Three input refinements -> h_<param> hypotheses (Phase F's
    # refinement-aware Lean/Coq lowering names hypotheses after the
    # parameter rather than h1, h2, h3).
    assert "(h_pitch_setpoint :" in out
    assert "(h_pitch_measured :" in out
    assert "(h_pitch_integral :" in out
    # Rabs is the Coq Reals absolute value -- but post-Phase-F the
    # refinements `Real{p | abs(p) < 1.5708}` lower to a conjunction
    # `(- 1.5708 < p /\ p < 1.5708)` (no `Rabs` on the parameter
    # itself; `Rabs` still appears in the ensures conclusion).
    assert "pitch_setpoint" in out
    assert "pitch_measured" in out
    assert "pitch_integral" in out

    # Conclusion has the function call substituted for `result`.
    assert "Rabs (autopilot_step pitch_setpoint pitch_measured pitch_integral)" in out
    assert "< ELEVATOR_MAX" in out


def test_proof_body_is_admitted(backend):
    out = _compile_file(AUTOPILOT, backend)
    assert "Proof." in out
    assert "unfold autopilot_step." in out
    # Phase F's refinement lowering uses the proof prelude
    # `first [lra | (idtac; admit)]` followed by Qed (the hypothesis
    # is in scope so trivial linear-real-arithmetic discharges close
    # quickly when the predicate is decidable; otherwise admit).
    # Both `Admitted.` and the lra/admit + Qed shape are valid.
    assert ("Admitted." in out) or ("admit" in out)


# ── Builtin mapping ─────────────────────────────────────────


def test_clamp_lowers_to_rmin_rmax():
    src = (
        "@verify(lean, theorem = \"cl_bound\")\n"
        "fn cl(x: Real, lo: Real, hi: Real) -> Real "
        "ensures (abs(result) <= 1.0)\n"
        "{ clamp(x, lo, hi) }\n"
    )
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = CoqBackend().compile_module(mod)
    assert "Rmin hi (Rmax lo x)" in out


def test_eml_lowers_to_exp_minus_ln():
    src = (
        "@verify(lean, theorem = \"e_pos\")\n"
        "fn e(x: Real, y: Real) -> Real "
        "ensures (result >= 0.0)\n"
        "{ eml(x, y) }\n"
    )
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = CoqBackend().compile_module(mod)
    assert "(exp x - ln y)" in out


def test_logical_ops_lower_to_coq_form():
    src = (
        "@verify(lean, theorem = \"both_pos\")\n"
        "fn f(x: Real, y: Real) -> Real "
        "requires (x > 0.0 && y > 0.0)\n"
        "{ x + y }\n"
    )
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = CoqBackend().compile_module(mod)
    # `&&` becomes Coq `/\`.
    assert "/\\" in out


# ── Custom verify_filter ────────────────────────────────────


def test_filter_only_emits_lean_verify_blocks_by_default():
    src = (
        "@verify(coq, theorem = \"only_for_coq\")\n"
        "fn f(x: Real) -> Real ensures (result >= 0.0) { x }\n"
        "@verify(lean, theorem = \"only_for_lean\")\n"
        "fn g(x: Real) -> Real ensures (result >= 0.0) { x }\n"
    )
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = CoqBackend().compile_module(mod)
    # Default filter is 'lean' (so the same source feeds both backends).
    assert "Theorem only_for_lean" in out
    assert "Theorem only_for_coq" not in out


def test_explicit_coq_filter():
    src = (
        "@verify(coq, theorem = \"only_for_coq\")\n"
        "fn f(x: Real) -> Real ensures (result >= 0.0) { x }\n"
    )
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = CoqBackend(verify_filter="coq").compile_module(mod)
    assert "Theorem only_for_coq" in out
