"""Quantitative-finance vertical integration tests.

Exercises every `.eml` file under `industries/finance/`:

  - parser produces a clean module
  - profiler labels every function with status `ok` (no `complex_body`)
  - Black-Scholes, the Greeks, and the risk kernels compile to C and Rust
  - the SR 11-7 / FRTB certification docs are in place

The headline regulator-facing claim is "one .eml source compiles to
multiple targets bit-exactly"; the cross-target equivalence harness
in `tools/equivalence/` is the natural place to push numerical
agreement; this file gates only the structural pieces (a CI failure
in the cross-target harness is far more expensive than a parse
regression caught here).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from lang.parser import parse_file
from lang.profiler import Profiler
from software.backends.c_backend import CBackend
from software.backends.rust_backend import RustBackend
from software.verification.lean.LeanBackend import LeanBackend


REPO_ROOT = Path(__file__).resolve().parents[2]
FINANCE_DIR = REPO_ROOT / "industries" / "finance"


# Every .eml file the vertical ships, with the @verify(lean) theorem
# the headline function carries (or None when the file is a kernel
# library with no top-level @verify).
_FINANCE_FILES: list[tuple[str, str | None]] = [
    ("pricing/black_scholes.eml",   "black_scholes_call_no_arb"),
    ("pricing/heston.eml",          "heston_log_spot_step_stable"),
    ("pricing/sabr.eml",            "sabr_atm_vol_positive"),
    ("greeks/delta.eml",            "bs_call_delta_in_zero_one"),
    ("greeks/gamma.eml",            "bs_gamma_non_negative"),
    ("greeks/vega.eml",             "bs_vega_non_negative"),
    ("greeks/theta.eml",            "bs_call_theta_negative_in_money"),
    ("risk/var_monte_carlo.eml",    "parametric_var_monotone_in_sigma"),
    ("risk/cva.eml",                "cva_cell_non_negative"),
    ("risk/stress_test.eml",        "stress_pnl_linear"),
]


# ── 1. Source files exist ───────────────────────────────────────────


@pytest.mark.parametrize(
    "rel_path,_thm",
    _FINANCE_FILES,
    ids=[f[0] for f in _FINANCE_FILES],
)
def test_finance_eml_file_exists(rel_path: str, _thm: str | None) -> None:
    p = FINANCE_DIR / rel_path
    assert p.exists(), f"missing finance vertical file: {p}"


# ── 2. Parse + profile ──────────────────────────────────────────────


@pytest.mark.parametrize(
    "rel_path,_thm",
    _FINANCE_FILES,
    ids=[f[0] for f in _FINANCE_FILES],
)
def test_finance_eml_parses_and_profiles(
    rel_path: str, _thm: str | None,
) -> None:
    mod = parse_file(str(FINANCE_DIR / rel_path))
    Profiler().profile_module(mod)
    assert mod.functions, f"{rel_path}: no functions parsed"
    failures: list[str] = []
    for fn in mod.functions:
        prof = fn.profile or {}
        status = prof.get("status", "missing")
        if status not in ("ok", "tuple"):
            failures.append(f"{fn.name}: status={status}")
    assert not failures, "\n".join(failures)


# ── 3. Headline @verify(lean) annotation in place ───────────────────


@pytest.mark.parametrize(
    "rel_path,thm",
    [(p, t) for p, t in _FINANCE_FILES if t is not None],
    ids=[f[0] for f in _FINANCE_FILES if f[1] is not None],
)
def test_finance_verify_annotation_present(
    rel_path: str, thm: str,
) -> None:
    mod = parse_file(str(FINANCE_DIR / rel_path))
    found = False
    for fn in mod.functions:
        for ann in fn.annotations:
            if ann.kind == "verify" and ann.args.get("theorem") == thm:
                found = True
                break
        if found:
            break
    assert found, (
        f"{rel_path}: expected @verify(lean, theorem = {thm!r}) "
        f"on some function, but no annotation matched"
    )


# ── 4. C + Rust + Lean compile cleanly for every file ───────────────


@pytest.mark.parametrize(
    "rel_path,_thm",
    _FINANCE_FILES,
    ids=[f[0] for f in _FINANCE_FILES],
)
def test_finance_compiles_to_c(rel_path: str, _thm: str | None) -> None:
    mod = parse_file(str(FINANCE_DIR / rel_path))
    Profiler().profile_module(mod)
    src = CBackend().compile(mod)
    assert "Generated by EML-lang C backend" in src
    for fn in mod.functions:
        assert fn.name in src, f"{rel_path}: C source missing {fn.name}"


@pytest.mark.parametrize(
    "rel_path,_thm",
    _FINANCE_FILES,
    ids=[f[0] for f in _FINANCE_FILES],
)
def test_finance_compiles_to_rust(rel_path: str, _thm: str | None) -> None:
    mod = parse_file(str(FINANCE_DIR / rel_path))
    Profiler().profile_module(mod)
    src = RustBackend().compile(mod)
    for fn in mod.functions:
        assert fn.name in src, f"{rel_path}: Rust source missing {fn.name}"


@pytest.mark.parametrize(
    "rel_path,thm",
    [(p, t) for p, t in _FINANCE_FILES if t is not None],
    ids=[f[0] for f in _FINANCE_FILES if f[1] is not None],
)
def test_finance_compiles_to_lean(rel_path: str, thm: str) -> None:
    mod = parse_file(str(FINANCE_DIR / rel_path))
    Profiler().profile_module(mod)
    src = LeanBackend().compile_module(mod)
    assert f"theorem {thm}" in src, (
        f"{rel_path}: Lean output missing theorem {thm!r}"
    )


# ── 5. Spot-check chain orders match the documented expectation ─────


def test_black_scholes_call_chain_order_at_most_3():
    """The Black-Scholes call has chain order at most 3 once
    norm_cdf inlines (ln + sqrt + tanh on the worst arm)."""
    mod = parse_file(str(FINANCE_DIR / "pricing/black_scholes.eml"))
    Profiler().profile_module(mod)
    fn = next(f for f in mod.functions if f.name == "black_scholes_call")
    chain = fn.profile["chain_order"]
    assert chain is not None
    assert chain <= 3, f"black_scholes_call chain={chain}, expected <= 3"


def test_stress_pnl_is_polynomial():
    """linear_pnl + quadratic_pnl are pure polynomial — chain 0.
    FRTB SBA's curvature charge can therefore deploy at FP32."""
    mod = parse_file(str(FINANCE_DIR / "risk/stress_test.eml"))
    Profiler().profile_module(mod)
    for name in ("linear_pnl", "quadratic_pnl", "worst_scenario_pnl"):
        fn = next(f for f in mod.functions if f.name == name)
        assert fn.profile["chain_order"] == 0, (
            f"{name}: chain={fn.profile['chain_order']}, expected 0"
        )


# ── 6. Certification docs in place ──────────────────────────────────


def test_model_validation_doc_exists():
    p = FINANCE_DIR / "certification" / "MODEL_VALIDATION.md"
    assert p.exists(), f"missing {p}"
    text = p.read_text(encoding="utf-8")
    # SR 11-7 is the headline regulator framework for model risk.
    assert "SR 11-7" in text
    # The theorem index lists every @verify name.
    for _path, thm in _FINANCE_FILES:
        if thm is None:
            continue
        assert thm in text, f"MODEL_VALIDATION.md missing theorem {thm}"


def test_frtb_compliance_doc_exists():
    p = FINANCE_DIR / "certification" / "FRTB_COMPLIANCE.md"
    assert p.exists(), f"missing {p}"
    text = p.read_text(encoding="utf-8")
    # FRTB pillars + the SBA / IMA distinction must both be present.
    assert "FRTB" in text
    assert "SBA" in text and "IMA" in text


def test_finance_readme_lists_subdirs():
    p = FINANCE_DIR / "README.md"
    assert p.exists(), f"missing {p}"
    text = p.read_text(encoding="utf-8")
    for sub in ("pricing", "greeks", "risk", "certification"):
        assert sub in text, f"finance/README.md missing reference to {sub}/"
