"""Isabelle / HOL verification backend.

Compiles `@verify` blocks into an Isabelle ``.thy`` theory file
using the ``Complex_Main`` theory of the standard HOL distribution.
Each verified function emits a ``definition``; each contract emits
a ``theorem`` with a ``sorry`` proof body (the equivalent of Lean's
``sorry`` / Coq's ``Admitted``).

Output shape
============

::

    (* Generated by the EML-lang Isabelle/HOL backend *)
    theory Autopilot
      imports Complex_Main
    begin

    definition Kp :: real where "Kp = 2.5"
    ...

    definition autopilot_step ::
      "real ⇒ real ⇒ real ⇒ real" where
      "autopilot_step pitch_setpoint pitch_measured pitch_integral =
         (let pitch_error = pitch_setpoint - pitch_measured;
              rate_target = ...
          in min ELEVATOR_MAX (max ELEVATOR_MIN (Kr * rate_target)))"

    theorem autopilot_command_within_limits:
      assumes "abs pitch_setpoint < 1.5708"
              "abs pitch_measured < 1.5708"
              "abs pitch_integral < INTEGRAL_LIMIT"
      shows "abs (autopilot_step pitch_setpoint pitch_measured pitch_integral)
              < ELEVATOR_MAX"
      sorry

    end

We use plain ASCII operators (``=>`` rather than ``\\<Rightarrow>``)
so the file works in both ASCII and Isabelle/jEdit's pretty-print
mode. Conversion happens automatically when the user opens the
file in Isabelle.

Reference: lang/spec/EML_LANG_DESIGN.md + Phase 3 backend roadmap.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLConstant,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> Isabelle/HOL name. ``Complex_Main`` exports
# the elementary functions over ``real``; their names match the
# common-mathematics convention except for ln→ln (HOL also uses
# ``ln`` for natural log).
_BUILTIN_TO_ISA: dict[NodeKind, str] = {
    NodeKind.EXP:   "exp",
    NodeKind.LN:    "ln",
    NodeKind.SIN:   "sin",
    NodeKind.COS:   "cos",
    NodeKind.TAN:   "tan",
    NodeKind.SQRT:  "sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "arcsin",
    NodeKind.ACOS:  "arccos",
    NodeKind.ATAN:  "arctan",
    NodeKind.SINH:  "sinh",
    NodeKind.COSH:  "cosh",
    NodeKind.TANH:  "tanh",
}


# EML type -> Isabelle/HOL type. Aliases default to real.
_TYPE_TO_ISA: dict[str, str] = {
    "Real": "real",
    "f64":  "real",
    "f32":  "real",
    "f16":  "real",
    "bf16": "real",
    "u8":   "nat",
    "u16":  "nat",
    "u32":  "nat",
    "u64":  "nat",
    "i8":   "int",
    "i16":  "int",
    "i32":  "int",
    "i64":  "int",
    "bool": "bool",
}


def _isa_type(eml_type: str) -> str:
    return _TYPE_TO_ISA.get(eml_type, "real")


def _theory_name(mod: EMLModule) -> str:
    """Isabelle theory names are conventionally Title_Case and must
    match the .thy filename. EML modules are snake_case; Title-case
    it for the Isabelle convention."""
    base = mod.name or "Forge_Module"
    parts = base.split("_")
    return "_".join(p[:1].upper() + p[1:].lower() for p in parts) or "Forge_Module"


class CompileError(Exception):
    """Raised on a NodeKind the Isabelle backend doesn't recognize."""


class IsabelleBackend:
    """Generate an Isabelle/HOL .thy file from an EML module."""

    name = "isabelle"

    def __init__(
        self,
        *,
        optimize: bool = True,
        verify_filter: str = "lean",
    ) -> None:
        self.optimize = optimize
        self.verify_filter = verify_filter

    # ── Public API ────────────────────────────────────────────

    def compile_module(self, mod: EMLModule) -> str:
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        verified = [
            f for f in mod.functions
            if any(self._is_verify(a) for a in f.annotations)
        ]
        if not verified:
            return ""

        thy = _theory_name(mod)
        lines: list[str] = [
            f"(* Generated by the EML-lang Isabelle/HOL backend *)",
            f"(* Source module: {mod.name or '(unnamed)'} *)",
            f"(* Source file:   {mod.source_file} *)",
            f"(* Verified fns:  {', '.join(f.name for f in verified)} *)",
            "",
            f"theory {thy}",
            "  imports Complex_Main",
            "begin",
            "",
        ]

        for c in mod.constants:
            lines.extend(self._emit_constant(c))
        if mod.constants:
            lines.append("")

        for fn in verified:
            lines.extend(self._compile_one(fn))
            lines.append("")

        lines.append("end")
        return "\n".join(lines).rstrip() + "\n"

    def compile(self, mod: EMLModule) -> str:
        return self.compile_module(mod)

    # ── Constants ─────────────────────────────────────────────

    def _emit_constant(self, c: EMLConstant) -> list[str]:
        isa_type = _isa_type(c.type_name)
        try:
            rhs = self._emit_expr(c.value)
        except CompileError as e:
            return [f"(* skipped const {c.name}: {e} *)"]
        return [f'definition {c.name} :: {isa_type} where "{c.name} = {rhs}"']

    # ── Per-function render ───────────────────────────────────

    def _compile_one(self, func: EMLFunction) -> list[str]:
        verify = next(
            a for a in func.annotations if self._is_verify(a)
        )
        theorem_name = verify.args.get("theorem", func.name)

        out: list[str] = [f"(* ── {func.name} ── *)", ""]
        out.extend(self._render_function_def(func))
        out.append("")
        out.extend(self._render_theorem(func, theorem_name))
        return out

    def _render_function_def(self, func: EMLFunction) -> list[str]:
        # Type signature: each param type, then ⇒, then return type.
        # We use the ASCII `=>` form -- Isabelle accepts both.
        param_types = [_isa_type(p.type_name) for p in func.params]
        ret_type = _isa_type(func.return_type or "Real")
        sig_types = " => ".join([*param_types, ret_type]) or ret_type
        sig = f'"{sig_types}"'

        params = " ".join(p.name for p in func.params)

        if func.is_extern:
            return [
                f"axiomatization {func.name} :: {sig}",
                f"(* extern declaration -- body provided by linkage *)",
            ]

        if func.return_tuple_types or self._has_complex_body(func.body):
            return [
                f"axiomatization {func.name} :: {sig}",
                f"(* opaque: tuple-return or mut/while body *)",
            ]

        body_expr = self._extract_body_expression(func.body)
        if body_expr is None:
            return [
                f"axiomatization {func.name} :: {sig}",
                f"(* opaque: empty body *)",
            ]

        try:
            body_isa = self._emit_block_as_let_chain(func.body, body_expr)
        except CompileError as e:
            return [
                f"axiomatization {func.name} :: {sig}",
                f"(* opaque: unsupported AST -- {e} *)",
            ]

        return [
            f"definition {func.name} :: {sig} where",
            f'  "{func.name} {params} =',
            f"     {body_isa}\"",
        ]

    def _emit_block_as_let_chain(
        self,
        body: ASTNode | None,
        final: ASTNode,
    ) -> str:
        """Render a function body as Isabelle's `let .. ; .. in <e>` form.

        Multiple bindings are semicolon-separated within a single
        ``let`` keyword (Isabelle/HOL syntax)::

            (let pitch_error = ...;
                 rate_target = ...
             in <final>)
        """
        if body is None or body.kind != NodeKind.BLOCK:
            return self._emit_expr(final)

        chain: list[tuple[str, str]] = []
        for stmt in body.children:
            if stmt.kind == NodeKind.LET:
                rhs = self._emit_expr(stmt.children[0])
                chain.append((str(stmt.value), rhs))

        final_expr = self._emit_expr(final)
        if not chain:
            return final_expr

        clauses = ";\n          ".join(f"{n} = {v}" for n, v in chain)
        return f"(let {clauses}\n      in {final_expr})"

    # ── Theorem render ────────────────────────────────────────

    def _render_theorem(
        self, func: EMLFunction, theorem_name: str,
    ) -> list[str]:
        # Hypotheses go under `assumes`; conclusion under `shows`.
        hyp_clauses: list[str] = []
        for i, req in enumerate(func.requires, start=1):
            try:
                hyp = self._emit_expr(req)
            except CompileError as e:
                hyp_clauses.append(f"(* requires #{i}: {e} *)")
                continue
            hyp_clauses.append(f'"{hyp}"')

        if func.ensures:
            ens = func.ensures[0]
            param_names = [p.name for p in func.params]
            call = f"{func.name} {' '.join(param_names)}"
            try:
                conclusion = self._emit_expr(ens, result_subst=f"({call})")
            except CompileError as e:
                conclusion = f"True (* TODO: ensures unsupported -- {e} *)"
        else:
            conclusion = "True"

        lines = [f"theorem {theorem_name}:"]
        if hyp_clauses:
            lines.append(f"  assumes {hyp_clauses[0]}")
            for h in hyp_clauses[1:]:
                lines.append(f"          {h}")
            lines.append(f'  shows "{conclusion}"')
        else:
            lines.append(f'  shows "{conclusion}"')
        lines.append("  sorry")
        return lines

    # ── Helpers ───────────────────────────────────────────────

    def _is_verify(self, annot: Annotation) -> bool:
        if annot.kind != "verify":
            return False
        return annot.args.get(0) == self.verify_filter

    @staticmethod
    def _has_complex_body(body: ASTNode | None) -> bool:
        if body is None or body.kind != NodeKind.BLOCK:
            return True
        return any(
            c.kind in {NodeKind.LET_MUT, NodeKind.WHILE, NodeKind.ASSIGN}
            for c in body.children
        )

    @staticmethod
    def _extract_body_expression(body: ASTNode | None) -> ASTNode | None:
        if body is None or body.kind != NodeKind.BLOCK:
            return body
        final: ASTNode | None = None
        for stmt in body.children:
            if stmt.kind in (NodeKind.LET, NodeKind.EXPR_STMT):
                continue
            final = stmt
        return final

    # ── Expression emission to Isabelle/HOL syntax ────────────

    def _emit_expr(
        self,
        node: ASTNode,
        *,
        result_subst: str | None = None,
    ) -> str:
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "True" if v else "False"
            if isinstance(v, int):
                return str(v)
            if isinstance(v, float):
                # Isabelle accepts decimal real literals when
                # Complex_Main is loaded.
                s = repr(v)
                if "." not in s and "e" not in s and "E" not in s:
                    s += ".0"
                return s
            raise CompileError(f"unsupported literal: {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if result_subst is not None and name == "result":
                return result_subst
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0], result_subst=result_subst)
            if node.value == "-":
                return f"(- {sub})"
            if node.value == "!":
                return f"(\\<not> {sub})"
            raise CompileError(f"unsupported unary op: {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0], result_subst=result_subst)
            right = self._emit_expr(node.children[1], result_subst=result_subst)
            op = node.value
            if op == "&&":
                op = "\\<and>"
            elif op == "||":
                op = "\\<or>"
            elif op == "==":
                op = "="
            elif op == "!=":
                op = "\\<noteq>"
            return f"({left} {op} {right})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({elems})"

        if kind == NodeKind.CLAMP:
            x, lo, hi = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"min {hi} (max {lo} {x})"

        if kind == NodeKind.POW:
            base, exp_node = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            # `powr` is Isabelle's real-power operator over `real`.
            return f"({base} powr {exp_node})"

        if kind == NodeKind.EML:
            x, y = (
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"(exp {x} - ln {y})"

        if kind in _BUILTIN_TO_ISA:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({_BUILTIN_TO_ISA[kind]} {args})"

        if kind == NodeKind.CALL:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({node.value} {args})"

        raise CompileError(
            f"Isabelle backend: unsupported NodeKind {kind} "
            f"(at line {node.line}:{node.col})"
        )
