"""Generate `eml-compile.1` man page from the argparse parser.

Outputs roff(7) compatible with `man -l <file>` and `groff -man`.
Run via:

    eml-compile manpage > eml-compile.1

The man page covers the same surface as `eml-compile --help` plus
the `init` and `manpage` subcommands.

Reference: lang/spec/EML_LANG_DESIGN.md section 4.2.
"""

from __future__ import annotations

from datetime import date


_HEADER = r""".\" Generated by tools/cli/manpage.py -- do not edit by hand.
.TH EML-COMPILE 1 "{date}" "Monogate Forge" "Forge Manual"
.SH NAME
eml\-compile \- compile EML\-lang source to C, Rust, Python, LLVM IR,
WebAssembly, Verilog, VHDL, Chisel, or Lean.
.SH SYNOPSIS
.B eml\-compile
[\fB\-\-target\fR \fITARGET\fR]
[\fB\-o\fR \fIOUTPUT\fR]
[\fB\-\-profile\-only\fR]
[\fB\-\-allocate\fR]
[\fB\-\-fpga\-target\fR \fITARGET\fR]
[\fB\-\-fmt\fR [\fB\-\-write\fR | \fB\-\-check\fR]]
[\fB\-\-explain\fR [\fB\-\-json\fR] [\fB\-\-backend\-stats\fR]]
[\fB\-\-no\-optimize\fR]
.IR FILE.eml
.PP
.B eml\-compile init
[\fIDIRECTORY\fR] [\fB\-\-name\fR \fINAME\fR] [\fB\-\-force\fR]
.PP
.B eml\-compile manpage
"""


_BODY = r""".SH DESCRIPTION
.B eml\-compile
is the front-end to the Monogate Forge compiler. It parses an
EML\-lang source file, runs the Pfaffian profiler, applies the
optimizer pipeline (constant folding, CSE, SuperBEST routing, and
import tree-shaking), and emits code for the chosen target.
.PP
EML\-lang is a domain-specific language for numerically stable
real-valued pipelines. Each function carries a chain-order
constraint that the type checker enforces against the inferred
profile, so a function declared
.IR "where chain_order <= 2"
that an inadvertent change pushes to chain order 3 fails to compile.
.SH OPTIONS
.TP
.BI \-\-target= TARGET
Output target. Choices: \fIc\fR, \fIrust\fR, \fIpython\fR,
\fIllvm\fR, \fIwasm\fR, \fIverilog\fR, \fIvhdl\fR, \fIchisel\fR,
\fIlean\fR, \fIall\fR.
The \fIall\fR target runs every backend and writes
\fI<stem>.<ext>\fR alongside the source.
.TP
.BI \-o " OUTPUT" ", \-\-output=" OUTPUT
Output file path. Defaults to stdout. With \fB\-\-target=all\fR
this is interpreted as a directory.
.TP
.B \-\-profile\-only
Print the Pfaffian profile summary and exit. No code is emitted.
.TP
.B \-\-allocate
Run the FPGA resource allocator (Patent #14) and print the
allocation plan. Requires at least one
.IR @target(fpga) " function."
.TP
.BI \-\-fpga\-target= TARGET
FPGA target identifier (e.g. \fIxilinx.artix7\fR,
\fIlattice.ice40\fR, \fIintel.cyclone10\fR, \fIasic.sky130\fR).
Default: \fIxilinx.artix7\fR.
.TP
.B \-\-fmt
Print canonically-formatted source to stdout. Combine with
\fB\-\-write\fR to rewrite the file in place, or \fB\-\-check\fR
to gate CI on canonical form (exit 1 if the file is not formatted).
.TP
.B \-\-explain
Print a per-function diff showing which optimizer passes fired,
before/after node counts, the SuperBEST family + digits saved,
and CSE bindings introduced. Combine with \fB\-\-json\fR for
machine-readable output and \fB\-\-backend\-stats\fR to also
report per-target emitted-source size.
.TP
.B \-\-no\-optimize
Disable the optimizer pass sequence. Useful when comparing
optimized vs unoptimized output.
.TP
.B \-\-version
Print the version string and exit.
.SH SUBCOMMANDS
.TP
.BR init " [\fIDIRECTORY\fR] [\fB\-\-name\fR \fINAME\fR] [\fB\-\-force\fR]"
Scaffold a new EML-lang project. Creates
.IR pyproject.toml ", " main.eml ", " .vscode/settings.json
and a starter
.IR .gitignore .
Existing files are skipped unless
.B \-\-force
is passed.
.TP
.B manpage
Print this man page in roff(7) format. Pipe to a file and
install via your distribution's man path.
.SH EXAMPLES
.PP
Profile a single file:
.PP
.RS
.nf
$ eml\-compile sigmoid.eml \-\-profile\-only
.fi
.RE
.PP
Compile to C and write to file:
.PP
.RS
.nf
$ eml\-compile sigmoid.eml \-\-target c \-o sigmoid.c
.fi
.RE
.PP
Run every backend at once:
.PP
.RS
.nf
$ eml\-compile sigmoid.eml \-\-target all \-o build/
.fi
.RE
.PP
Allocate FPGA resources for a Lattice iCE40 target:
.PP
.RS
.nf
$ eml\-compile motor_foc.eml \-\-allocate \-\-fpga\-target lattice.ice40
.fi
.RE
.PP
Scaffold a new project:
.PP
.RS
.nf
$ eml\-compile init my_project
$ cd my_project
$ eml\-compile main.eml \-\-target c \-o main.c
.fi
.RE
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Compile error, parse error, or invalid arguments.
.TP
.B 2
Target requested is not built yet (legacy; no current targets).
.SH SEE ALSO
.BR eml\-fmt (1),
.BR python (1),
.BR cargo (1),
.BR verilator (1).
.PP
Online documentation: https://monogate.dev/forge/
.SH AUTHOR
Monogate Forge contributors.
"""


def emit_manpage() -> str:
    """Return the rendered man page text."""
    return (
        _HEADER.replace("{date}", date.today().isoformat())
        + _BODY
    )


if __name__ == "__main__":
    import sys
    sys.stdout.write(emit_manpage())
