"""Tests for the MATLAB / Simulink backend
(`software.backends.matlab_backend`)."""

from __future__ import annotations

from pathlib import Path

import pytest

from lang.parser import parse_file, parse_source
from lang.profiler import Profiler
from software.backends.matlab_backend import MatlabBackend


REPO_ROOT = Path(__file__).resolve().parents[3]
EXAMPLES_DIR = REPO_ROOT / "lang" / "spec" / "grammar" / "examples"
AUTOPILOT = REPO_ROOT / "industries" / "aerospace" / "flight_control" / "autopilot.eml"


@pytest.fixture(scope="module")
def profiler() -> Profiler:
    return Profiler()


@pytest.fixture
def backend() -> MatlabBackend:
    # Fresh backend per test -- the backend caches the constants
    # table per compile() call so a fixture-scoped instance can
    # leak state when tests run in parallel.
    return MatlabBackend()


def _compile(path: Path, profiler: Profiler, backend: MatlabBackend) -> str:
    mod = parse_file(path)
    profiler.profile_module(mod)
    return backend.compile(mod)


# ── Smoke: every grammar example compiles ─────────────────────


@pytest.mark.parametrize(
    "filename",
    sorted(p.name for p in EXAMPLES_DIR.glob("*.eml")),
)
def test_demo_compiles(filename, profiler, backend):
    out = _compile(EXAMPLES_DIR / filename, profiler, backend)
    # Header is always present.
    assert "Generated by EML-lang MATLAB backend" in out
    # MATLAB function declarations end with `end` lines.
    assert out.rstrip().endswith("end")


# ── Autopilot: contracts → assert + verify cross-link ─────────


def test_autopilot_emits_asserts_from_requires_ensures(profiler, backend):
    out = _compile(AUTOPILOT, profiler, backend)

    # Three requires become three entry-asserts.
    assert out.count("requires violated") == 3
    assert "abs(pitch_setpoint) < 1.5708" in out
    assert "abs(pitch_measured) < 1.5708" in out
    assert "abs(pitch_integral) < 5.0" in out  # INTEGRAL_LIMIT inlined

    # One ensures becomes one before-return assert.
    assert "ensures violated" in out
    # Ensures references `r` (the function's return variable),
    # not `result` -- the EML keyword gets rewritten.
    assert "abs(r) < 0.349" in out


def test_autopilot_lean_cross_link_present(profiler, backend):
    out = _compile(AUTOPILOT, profiler, backend)
    assert '@verify(lean, theorem = "autopilot_command_within_limits")' in out


def test_autopilot_primary_function_matches_module(profiler, backend):
    """MATLAB requires the file's first function to share the
    file's name. EML's `module autopilot;` doesn't have an
    `autopilot()` function (just `autopilot_step`), so the
    backend synthesises a wrapper."""
    out = _compile(AUTOPILOT, profiler, backend)
    assert "function r = autopilot(" in out
    assert "delegates to autopilot_step" in out


# ── Constant inlining ─────────────────────────────────────────


def test_module_constants_are_inlined_not_referenced(profiler, backend):
    """MATLAB has no clean module-scope const facility, so the
    backend must inline numeric values at use-sites; otherwise
    the function bodies would reference unbound names."""
    out = _compile(AUTOPILOT, profiler, backend)
    # A sample of inlined values.
    assert "0.196 * cos" in out             # GRAVITY_GAIN inlined
    assert "1.8 * rate_target" in out       # Kr inlined
    assert "0.349" in out                    # ELEVATOR_MAX inlined
    # The bare name forms must NOT appear in any function body
    # (they're allowed in the header comment, which is filtered).
    body_text = "\n".join(
        ln for ln in out.splitlines() if not ln.lstrip().startswith("%")
    )
    assert "GRAVITY_GAIN" not in body_text
    assert "ELEVATOR_MAX" not in body_text
    assert " Kp " not in body_text  # word-boundary check


# ── Builtin mapping ───────────────────────────────────────────


def test_clamp_lowers_to_min_max() -> None:
    src = "fn cl(x: Real, lo: Real, hi: Real) -> Real { clamp(x, lo, hi) }\n"
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = MatlabBackend().compile(mod)
    assert "min(hi, max(lo, x))" in out


def test_eml_lowers_to_exp_minus_log() -> None:
    src = "fn e(x: Real, y: Real) -> Real { eml(x, y) }\n"
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = MatlabBackend().compile(mod)
    assert "(exp(x) - log(y))" in out


def test_pow_uses_dot_caret() -> None:
    src = "fn p(x: Real, y: Real) -> Real { pow(x, y) }\n"
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = MatlabBackend().compile(mod)
    # `.^` is element-wise; safe for scalars too.
    assert ").^(" in out


def test_not_equal_rewrites_to_tilde_eq() -> None:
    src = "fn ne(a: Real, b: Real) -> bool { a != b }\n"
    mod = parse_source(src)
    Profiler().profile_module(mod)
    out = MatlabBackend().compile(mod)
    assert "a ~= b" in out
