"""Lean 4 verification backend.

Compiles `@verify(lean, theorem = "<name>")` blocks into Lean 4
theorem files. Each verified function produces:

  1. A Lean function definition mirroring the EML body (when the
     body is a single expression without mut/while; complex bodies
     are declared as `opaque` placeholders).
  2. A theorem statement built from `requires` (hypotheses) +
     `ensures` (conclusion), with `result` rewritten to refer to
     the function's return value.
  3. A proof attempt that tries `eml_auto` (from
     `monogate-lean/MonogateEML/Tactics.lean`), then falls back
     to `simp; sorry` with a TODO marker.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.4.
"""

from __future__ import annotations

from lang.parser.ast_nodes import (
    Annotation,
    ASTNode,
    EMLFunction,
    EMLModule,
    NodeKind,
)


# Builtin NodeKind -> Lean function call. Lean uses Real.foo for
# real-valued versions of transcendentals.
_BUILTIN_TO_LEAN: dict[NodeKind, str] = {
    NodeKind.EXP:   "Real.exp",
    NodeKind.LN:    "Real.log",
    NodeKind.SIN:   "Real.sin",
    NodeKind.COS:   "Real.cos",
    NodeKind.TAN:   "Real.tan",
    NodeKind.SQRT:  "Real.sqrt",
    NodeKind.ABS:   "abs",
    NodeKind.ASIN:  "Real.arcsin",
    NodeKind.ACOS:  "Real.arccos",
    NodeKind.ATAN:  "Real.arctan",
    NodeKind.SINH:  "Real.sinh",
    NodeKind.COSH:  "Real.cosh",
    NodeKind.TANH:  "Real.tanh",
}


# Stdlib function name -> MonogateEML.Runtime symbol. When the AST
# contains a CALL to a stdlib activation/growth function, resolve it
# through the runtime namespace so generated theorems compile cleanly.
_STDLIB_TO_RUNTIME: dict[str, str] = {
    "sigmoid":  "MonogateEML.Runtime.mg_sigmoid",
    "softplus": "MonogateEML.Runtime.mg_softplus",
    "relu":     "MonogateEML.Runtime.mg_relu",
    "logistic": "MonogateEML.Runtime.mg_logistic",
    "gompertz": "MonogateEML.Runtime.mg_gompertz",
    "eml":      "MonogateEML.Runtime.mg_eml",
    "eal":      "MonogateEML.Runtime.mg_eal",
    "exl":      "MonogateEML.Runtime.mg_exl",
    "edl":      "MonogateEML.Runtime.mg_edl",
    "lediv":    "MonogateEML.Runtime.mg_lediv",
    "elsb":     "MonogateEML.Runtime.mg_elsb",
    "elad":     "MonogateEML.Runtime.mg_elad",
    "deml":     "MonogateEML.Runtime.mg_deml",
}


# Map EML-lang type names to Lean type names. Aliases default to
# `Real` since chain-order constraints don't change the underlying
# numeric domain.
_TYPE_TO_LEAN: dict[str, str] = {
    "Real": "Real",
    "f64":  "Real",
    "f32":  "Real",
    "f16":  "Real",
    "bf16": "Real",
    "u8":   "Nat",
    "u16":  "Nat",
    "u32":  "Nat",
    "u64":  "Nat",
    "i8":   "Int",
    "i16":  "Int",
    "i32":  "Int",
    "i64":  "Int",
    "bool": "Bool",
}


def _lean_type(eml_type: str) -> str:
    return _TYPE_TO_LEAN.get(eml_type, "Real")


class LeanBackend:
    """Generate Lean 4 theorems from `@verify` blocks."""

    name = "lean"

    def __init__(self, *, optimize: bool = True) -> None:
        self.optimize = optimize

    # ── Public API ────────────────────────────────────────────

    def compile_module(self, mod: EMLModule) -> str:
        """Emit a full .lean file for every @verify-annotated
        function in the module. Returns the empty string if no
        function carries a Lean verification annotation."""
        if self.optimize:
            from lang.optimizer import optimize_module
            mod = optimize_module(mod)
        verified = [
            f for f in mod.functions
            if any(self._is_lean_verify(a) for a in f.annotations)
        ]
        if not verified:
            return ""

        # Header + imports.
        lines = [
            "-- Generated by the EML-lang Lean backend",
            f"-- Source module: {mod.name or '(unnamed)'}",
            f"-- Source file:   {mod.source_file}",
            f"-- Verified fns:  {', '.join(f.name for f in verified)}",
            "",
            "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic",
            "import Mathlib.Analysis.SpecialFunctions.Exp",
            "import Mathlib.Analysis.SpecialFunctions.Log.Basic",
            "import MonogateEML.Tactics",
            "import MonogateEML.Runtime",
            "",
            "open Real",
            "open MonogateEML.Runtime",
            "",
        ]
        for fn in verified:
            lines.extend(self._compile_one(fn, mod))
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def compile(self, func: EMLFunction) -> str:
        """Emit Lean for a single @verify-annotated function.
        Returns empty string when the function has no @verify."""
        if not any(self._is_lean_verify(a) for a in func.annotations):
            return ""
        # Synthesize a wrapper module so compile_module's header runs.
        mod = EMLModule(name="_single", functions=[func])
        return self.compile_module(mod)

    # ── Internal: per-function render ─────────────────────────

    def _compile_one(self, func: EMLFunction, mod: EMLModule) -> list[str]:
        verify_annot = next(
            a for a in func.annotations if self._is_lean_verify(a)
        )
        theorem_name = verify_annot.args.get("theorem", func.name)

        out: list[str] = []
        out.append(f"-- ── {func.name} ──")
        out.append("")
        out.extend(self._render_function_def(func))
        out.append("")
        out.extend(self._render_theorem(func, theorem_name))
        return out

    def _render_function_def(self, func: EMLFunction) -> list[str]:
        """Emit a Lean `def` matching the EML function. For complex
        bodies (mut / while), emit `opaque` instead so the theorem
        can still talk about the function symbolically."""
        params_lean = " ".join(
            f"({p.name} : {_lean_type(p.type_name)})" for p in func.params
        )
        ret_type = (
            "Real" if func.return_tuple_types
            else _lean_type(func.return_type or "Real")
        )

        # Extern fns are opaque declarations by definition -- the
        # implementation lives outside EML-lang's reach.
        if func.is_extern:
            return [
                f"opaque {func.name} {params_lean} : {ret_type}"
                f"  -- extern declaration",
            ]

        # Tuple returns and complex bodies become opaque declarations
        # so the theorem can still refer to them by name.
        complex_body = self._has_complex_body(func.body)
        if func.return_tuple_types or complex_body:
            tuple_note = (" -- tuple-return; opaque for now"
                          if func.return_tuple_types else "")
            complex_note = ("\n-- (body has mut / while -- opaque "
                            "until Phase 2.5 control-flow analyzer)"
                            if complex_body else "")
            return [
                f"opaque {func.name} {params_lean} : {ret_type}"
                f"{tuple_note}{complex_note}",
            ]

        # Single-expression body -- inline the AST.
        body_expr = self._extract_body_expression(func.body)
        if body_expr is None:
            return [f"opaque {func.name} {params_lean} : {ret_type}"
                    f"  -- empty body"]
        try:
            lean_body = self._emit_expr(body_expr)
        except _UnsupportedNode as e:
            return [
                f"opaque {func.name} {params_lean} : {ret_type}"
                f"  -- unsupported AST: {e}",
            ]
        return [
            f"def {func.name} {params_lean} : {ret_type} :=",
            f"  {lean_body}",
        ]

    def _render_theorem(self, func: EMLFunction,
                        theorem_name: str) -> list[str]:
        params_lean = " ".join(
            f"({p.name} : {_lean_type(p.type_name)})" for p in func.params
        )
        # Hypotheses
        hyp_clauses: list[str] = []
        for i, req in enumerate(func.requires):
            try:
                hyp = self._emit_expr(req)
                hyp_clauses.append(f"(h{i+1} : {hyp})")
            except _UnsupportedNode as e:
                hyp_clauses.append(f"-- TODO: requires #{i+1} ({e})")
        # Conclusion
        if func.ensures:
            ens = func.ensures[0]
            # `result` in ensures refers to the function's output.
            param_names = [p.name for p in func.params]
            call = f"{func.name} {' '.join(param_names)}"
            try:
                conclusion = self._emit_expr(ens, result_subst=call)
            except _UnsupportedNode as e:
                conclusion = f"True  -- TODO: ensures unsupported ({e})"
        else:
            conclusion = "True"

        hyp_block = "\n    ".join(hyp_clauses) if hyp_clauses else ""

        proof_lines = [
            f"theorem {theorem_name} {params_lean}",
        ]
        if hyp_block:
            proof_lines.append(f"    {hyp_block} :")
        else:
            proof_lines[-1] += " :"
        proof_lines.append(f"    {conclusion} := by")
        # Proof attempt: try eml_auto, then unfold + simp, then sorry.
        proof_lines.extend([
            f"  -- Auto-attempt: eml_auto, then unfold + simp.",
            f"  -- Falls through to `sorry` if neither closes the goal.",
            f"  first",
            f"  | exact MonogateEML.Tactics.eml_auto",
            f"  | (unfold {func.name}; simp; sorry)",
            f"  | sorry  -- TODO: hand-prove or strengthen eml_auto",
        ])
        return proof_lines

    # ── Helpers ───────────────────────────────────────────────

    @staticmethod
    def _is_lean_verify(annot: Annotation) -> bool:
        if annot.kind != "verify":
            return False
        # The first positional arg should be 'lean'.
        return annot.args.get(0) == "lean"

    @staticmethod
    def _has_complex_body(body: ASTNode | None) -> bool:
        if body is None or body.kind != NodeKind.BLOCK:
            return True
        return any(
            c.kind in {NodeKind.LET_MUT, NodeKind.WHILE, NodeKind.ASSIGN}
            for c in body.children
        )

    @staticmethod
    def _extract_body_expression(body: ASTNode | None) -> ASTNode | None:
        """Try to reduce the body to a single expression by inlining
        `let` bindings via substitution. Returns None when the body
        has no final expression."""
        if body is None or body.kind != NodeKind.BLOCK:
            return body
        # If the only non-LET stmt is the final expression, inline lets.
        bindings: dict[str, ASTNode] = {}
        final: ASTNode | None = None
        for stmt in body.children:
            if stmt.kind == NodeKind.LET:
                bindings[stmt.value] = stmt.children[0]
            elif stmt.kind == NodeKind.EXPR_STMT:
                continue
            else:
                final = stmt
        if final is None:
            return None
        if not bindings:
            return final
        return _inline_bindings(final, bindings)

    # ── Expression emission to Lean syntax ────────────────────

    def _emit_expr(self, node: ASTNode, *,
                   result_subst: str | None = None) -> str:
        """Render an EML AST expression as a Lean expression string."""
        kind = node.kind

        if kind == NodeKind.LITERAL:
            v = node.value
            if isinstance(v, bool):
                return "true" if v else "false"
            if isinstance(v, int):
                return f"({v} : Real)"
            if isinstance(v, float):
                return f"({v} : Real)"
            raise _UnsupportedNode(f"literal {v!r}")

        if kind == NodeKind.VAR:
            name = str(node.value)
            if name == "result" and result_subst is not None:
                return f"({result_subst})"
            return name

        if kind == NodeKind.UNARYOP:
            sub = self._emit_expr(node.children[0],
                                  result_subst=result_subst)
            if node.value == "-":
                return f"(-{sub})"
            if node.value == "!":
                return f"(¬ {sub})"
            raise _UnsupportedNode(f"unary {node.value!r}")

        if kind == NodeKind.BINOP:
            left = self._emit_expr(node.children[0],
                                   result_subst=result_subst)
            right = self._emit_expr(node.children[1],
                                    result_subst=result_subst)
            op = node.value
            # Lean binop spelling matches except for boolean ops.
            lean_op = {
                "&&": "∧",
                "||": "∨",
            }.get(op, op)
            return f"({left} {lean_op} {right})"

        if kind in _BUILTIN_TO_LEAN:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({_BUILTIN_TO_LEAN[kind]} {args})"

        if kind == NodeKind.POW:
            base = self._emit_expr(node.children[0],
                                   result_subst=result_subst)
            exp = self._emit_expr(node.children[1],
                                  result_subst=result_subst)
            return f"({base} ^ {exp})"

        if kind == NodeKind.EML:
            x = self._emit_expr(node.children[0],
                                result_subst=result_subst)
            y = self._emit_expr(node.children[1],
                                result_subst=result_subst)
            return f"((Real.exp {x}) - (Real.log {y}))"

        if kind == NodeKind.CLAMP:
            x = self._emit_expr(node.children[0],
                                result_subst=result_subst)
            lo = self._emit_expr(node.children[1],
                                 result_subst=result_subst)
            hi = self._emit_expr(node.children[2],
                                 result_subst=result_subst)
            return f"(min (max {x} {lo}) {hi})"

        if kind == NodeKind.CALL:
            args = " ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            # Stdlib activation/growth/EML-family calls resolve through
            # the MonogateEML.Runtime namespace (opened at file scope,
            # so the short name suffices when there's no collision).
            name = str(node.value)
            if name in _STDLIB_TO_RUNTIME:
                return f"(mg_{name} {args})"
            return f"({name} {args})"

        if kind == NodeKind.TUPLE:
            elems = ", ".join(
                self._emit_expr(c, result_subst=result_subst)
                for c in node.children
            )
            return f"({elems})"

        raise _UnsupportedNode(
            f"NodeKind {kind} (line {node.line}:{node.col})"
        )


class _UnsupportedNode(Exception):
    """Internal: a node the Lean backend doesn't know how to render."""


def _inline_bindings(
    node: ASTNode, bindings: dict[str, ASTNode],
) -> ASTNode:
    """Substitute let-binding variables with their RHS expressions.
    Returns a new ASTNode tree (the original is not mutated)."""
    if node.kind == NodeKind.VAR and node.value in bindings:
        return _inline_bindings(bindings[node.value], bindings)
    new_children = [_inline_bindings(c, bindings) for c in node.children]
    return ASTNode(
        kind=node.kind,
        value=node.value,
        children=new_children,
        type_annotation=node.type_annotation,
        chain_constraint=node.chain_constraint,
        line=node.line,
        col=node.col,
    )
