"""Lean 4 verification backend.

Compiles `@verify(lean, theorem = "<name>")` blocks into Lean 4
theorem files. The proof tail is auto-attempted via the
`eml_auto` tactic from monogate-lean/MonogateEML/Tactics.lean;
falls back to `sorry` with a TODO when not closeable.

Reference: lang/spec/EML_LANG_DESIGN.md section 2.4.
SCAFFOLD.
"""

from __future__ import annotations

from lang.parser.ast_nodes import EMLFunction


class LeanBackend:
    """Generate Lean 4 theorems from `@verify` blocks."""

    name = "lean"

    def compile(self, func: EMLFunction) -> str:
        """Emit one .lean file body for a verify-annotated function."""
        verify = next(
            (a for a in func.annotations
             if a.get("kind") == "verify"),
            None,
        )
        if verify is None:
            return ""

        theorem_name = verify.get("args", {}).get("theorem", func.name)
        return self._render_theorem(func, theorem_name)

    def _render_theorem(self, func: EMLFunction, theorem_name: str) -> str:
        """Skeleton template; real templating + proof attempt
        lands in Phase 2.4."""
        return (
            f"-- Generated by EML-lang Lean backend\n"
            f"-- SCAFFOLD: real theorem rendering lands in Phase 2.4\n"
            f"\n"
            f"theorem {theorem_name} : True := by\n"
            f"  trivial  -- TODO: render requires/ensures clauses\n"
        )
